### ISSUE TITLE
Python variables obscur ipdb commands

### ISSUE THREAD

**Issue by tkossak** [ipython/ipython#10037]
This PR: #https://github.com/ipython/ipython/pull/9449 introduced annoying problem: I couldn't step through the following code (execute line 3):

```
n = 1
next = 1
print('end')
```

Because n/next commands weren't working:

```
$ ipdb test.py
> /tmp/test.py(1)<module>()
----> 1 n = 1
      2 next = 1
      3 print('end')

ipdb> next
> /tmp/test.py(2)<module>()
      1 n = 1
----> 2 next = 1
      3 print('end')

ipdb> next
> /tmp/test.py(3)<module>()
      1 n = 1
      2 next = 1
----> 3 print('end')

ipdb> next
1
ipdb> n
1
ipdb> !n
1
ipdb> !next
1
```

I discovered that in this case I can use standard pdb or I can get it to work in ipdb by using `!!n` (it still has a bug that @tcztzy tried to solve in https://github.com/ipython/ipython/pull/10035) but what do you think about changing this behavior: all ipdb builtin commands should work as they meant to and if we want to see python variables we use i.e.: `!n` instead of `n`. Variables' names that are not ipdb commands could still be displayed by just writing their name.

[StackOverflow thread](http://stackoverflow.com/questions/40224066/ipdb-commands-obscured-by-variables)

**Comment by takluyver** [comment]
@anntzer, you wrote PR #9449, do you want to make the case for that behaviour?

Everyone: let's try using the Github 'reactions' to vote on this. Add a 'thumbs up' on this issue to vote for the original behaviour (`n` always being the debugger 'next' command), or 'thumbs down' to vote for the 'smart command mode' from #9449 (`n` shows the variable n if it exists, otherwise acts as the 'next' command).

We'll take votes as an indicator, not a binding decision.

**Comment by anntzer** [comment]
My personal experience with debugging (which may be different from other people's...) is that in the vast majority of cases, I call `pdb.set_trace()` at the right place or `pdb.pm() / %debug` after an exception bubbles out, check where I am, inspect a few variables, and leave.  I very rarely step the debugger.  Especially in the context of IPython, I'd guess that most users also enter the debugger via `%debug` and use it for post-mortem'ing.

Thus, the choice of favoring printing variables rather than executing commands (which I did not invent: I got the idea from https://pypi.python.org/pypi/pdbpp/#smart-command-parsing) simply reflects my usage pattern: most of the times, printing the variable value is what I want to do.

**Comment by takluyver** [comment]
So far, there are three votes to go back to the old behaviour, and one for the current behaviour. Anyone else? I'll also ask on the mailing list.

**Comment by nbastin** [comment]
This...is horrible.  I guess we needed to be on the mailing list or something, but I can't believe anyone thought this was a good idea.

**Comment by denfromufa** [comment]
@takluyver why not make this variable vs debug command configurable interactively when the first conflict is hit? both behaviors are confusing anyway.

**Comment by nbastin** [comment]
Since I was sitting here when the previous comment came in - not showing variables is NOT confusing, or at least is not inconsistent.  Every other python debugger prefers commands over variables - ipython is doing something very unpythonic. (And very un-any-language-ic - I know of no debugger that auto-prints in any language that will prefer variables over internal commands)

**Comment by denfromufa** [comment]
or at least print a warning with a note about clash and suggest syntax to avoid the clash.

**Comment by takluyver** [comment]
> Every other python debugger prefers commands over variables

That's apparently not true of pdb++, which is where this idea came from.

**Comment by denfromufa** [comment]
@nbastin I have not used any other command-line debugger and only use this one in ipython/jupyter because there is no graphical alternative that works reliably.

**Comment by nbastin** [comment]
@takluyver : not to be pedantic, but pdb++ is a piece of software that hasn't seen a release in over a year and seems to be completely unmaintained.  (Yes I missed this in my survey, but I was looking for things with releases in this calendar year)

**Comment by nbastin** [comment]
@denfromufa: WingWare seems to be more useful and reliable?  I'm not sure what criteria you're judging this on, so I could be missing something significant.

**Comment by anntzer** [comment]
Clearly, no one likes this idea.  Let's just get rid of it -- possibly with @denfromufa's "let the user choose the first time this is hit" option.

**Comment by matthew-brett** [comment]
Can this be configured somewhere in IPython?  I think it would be fine to revert this if it could be re-enabled with a configuration option for those who like it.

**Comment by Carreau** [comment]
I would be in favor of reverting to the more usual debugger behavior. Potentially investigating configurability later. Also keep in mind that IPython is not trying to be the best debugger, there are likely a number of packages that do a better job.

**Comment by takluyver** [comment]
#10050 reverts it. As the voting is currently 11-1 for reverting, I haven't made it configurable at present - every config option adds complexity and potential bugs, so I'm reluctant to add them without a certain level of support.

We could also look at providing options to plug in externally developed debuggers - I don't think our debugger is particularly great, and there are projects like [pudb](https://pypi.python.org/pypi/pudb) out there which have spent much more time than us on debugger UI.

**Comment by fperez** [comment]
Late to the party, but I wanted to say that I strongly support the reversion.  Over and over we've encountered that customizations that try to be overly smart, even though well-intentioned, typically cause more confusion than they are worth.  Over the years we've backed off on a number of those (made them optional when it's easy to do in a simple way), and I think this falls in that category.

Thanks!
