### ISSUE TITLE
wish: inline animation for %matplotlib inline

### ISSUE THREAD

**Issue by godaygo** [ipython/ipython#10081]
I think when someone use `%matplotlib inline` magic, it is reasonable to make matplotlib's animation to play by default in Jupyter notebook without explicit  `mpl.rc('animation', html='html5')`. And at the current time they are rendered as png, svg or something else. When I modify this value in matplolibrc file it does not seem to change anything...only `mpl.rc('animation', html='html5')` helps.

**Comment by takluyver** [comment]
@tacaswell I don't understand what's being requested here. Does it make sense to you?

**Comment by Carreau** [comment]
can you try `%matplotlib notebook` as well ?

**Comment by tacaswell** [comment]
`Animation` objects have a `_rerp_html_` method that setting that rcparam effectively enables.

It is not clear to me why modifying the `matplotlibrc` is not working, that should probably go to matplotlib-users@python.org

I think the other ask is for `inline` to support updating animations, which I do not think is possible because inline closes the figure after it renders.  Using `nbagg` or `ipympl` are the way to go with that.

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one.

Thanks everyone and happy hacking! :bowtie:
