### ISSUE TITLE
python3.6 dict printing

### ISSUE THREAD

**Issue by brendene** [ipython/ipython#10110]
IPython's sorting of dictionary keys before pretty printing them made sense before Python 3.6 dictionaries.

Now that dictionaries in 3.6 preserve insertion order, is it still necessary to sort them?

This would prevent odd behavior such as:

```
In [1]: d = dict(a = 1, z = 2, c = 3)

In [2]: d
Out[2]: {'a': 1, 'c': 3, 'z': 2}

In [3]: print(d)
{'a': 1, 'z': 2, 'c': 3}

```

**Comment by srinivasreddy** [comment]
Short answer:

I suppose so at least until 3.6  becomes the minimum version we support in 3.x series.

Long answer:

Since this was introduced in 3.6, we also support 3.4,3.5, i think it is better to keep the behavior as is. On the other hand, we anyway have an ordered dict, and a user can always use that.

**Comment by njsmith** [comment]
Apparently this can make teaching more complicated:
https://mastodon.social/@aparrish/13011522

**Comment by Carreau** [comment]
Reopening, I got complaints at PyCon as well from Mike Muller. I think we are trying to be friendly enough with teaching that we can consider removing the sorting.

**Comment by smarnach** [comment]
While the reasoning that the dictionary order should be considered an implementation detail makes sense, the current behaviour has definitely confused a lot of people.  Latest evidence: [this question on StackOverflow|https://stackoverflow.com/questions/45347084/how-can-ordereddict-know-about-the-element-order-of-an-already-instantiated-dict].

How about checking whether the Python implementation maintains dictionary order, and only sorting the keys if it doesn't?  This should give reasonable behaviour in all versions of Python.

**Comment by Carreau** [comment]
I'd like to not have an implementation that depends on the Python version. Then you can show "Hey on 3.4 order is arbitrary", and "on 3.6 it's not".

**Comment by Carreau** [comment]
cc @pya which I believe will be for deactivating sorting.

**Comment by fterbo** [comment]
Displaying objects, in both IPython REPL and CPython REPL, has never shown you various vagaries of their *internal* structure.  This is for a lot of reasons (character set problems when displaying bytes, no `__str__`/`__repr__` methods, etc.), but the fact remains - you should never rely on the user-consumable *printed* version of an object to be a 100% faithful representation, regardless of where you're printing it.

Displayed objects are not a replacement for reading the documentation.  If you are surprised that `.items()`, `.values()`, and `.keys()` return in a different sequence than what is displayed, that is not the fault of IPython.

**Comment by Carreau** [comment]
> Displaying objects, in both IPython REPL and CPython REPL, has never shown you various vagaries of their internal structure. This is for a lot of reasons (character set problems when displaying bytes, no __str__/__repr__ methods, etc.), 

Though the current Python REPL does display dict with their keys ordered, and not random. So the implementation details do leak. 

> but the fact remains - you should never rely on the user-consumable printed version of an object to be a 100% faithful representation, regardless of where you're printing it.

We not asking to rely, I think it is a question of _convenience_. Having consistent representation of object that map to the behavior of  `.items()`, `.values()`, and `.keys()`  is helpful for beginners. 
 

> Displayed objects are not a replacement for reading the documentation. If you are surprised that .items(), .values(), and .keys() return in a different sequence than what is displayed, that is not the fault of IPython.

Well in this specific case it is, we do call a `sorted()` explicitly. I've submitted PR https://github.com/ipython/ipython/pull/10730 which remove the key sorting, so the order of the displayed keys will be the one of `.keys()`.  After asking `@fperez` he thinks that we might want to wait a bit more to know wether order is really an implementation details, or wether it will be promoted as a language feature.

Cf also https://github.com/ipython/ipython/issues/10581 which gives workarounds.

**Comment by Carreau** [comment]
There seem to a majority of people against removing the sorting of keys. See #10581 and [thread on the mailing list](https://mail.python.org/pipermail/ipython-dev/2017-August/016283.html), so I'm going to post-pone changing the default repr for now, and we can revisit that later if necessary.

**Comment by njsmith** [comment]
It's time to revisit this, because Python dicts are now officially ordered: https://mail.python.org/pipermail/python-dev/2017-December/151283.html

**Comment by takluyver** [comment]
I've clicked through that thread, and there's a similar discussion going on for the stdlib `pprint` module, with no clear consensus yet.

One the one hand, showing dictionaries in insertion order makes it easier to explain how Python dictionaries (now) work. On the other hand, dicts are used in many scenarios where insertion order does not matter, and it may not be under the user's control (e.g. HTTP headers). Showing them sorted by key is still more convenient for humans to quickly see things like "what's the value for transfer-encoding?" or "does it have a content-length field?"

We'll probably end up making an option for this, but it's still going to be tough to decide on the default. My gut feeling is that displaying dicts in sorted order is more useful the vast majority of the time, but the times when you want them to appear in insertion order (teaching people Python) are exactly the times when you don't want to have to fiddle with config.

**Comment by njsmith** [comment]
I'm kind of disturbed at the idea that IPython's repr would not default to
accurately representing the objects I'm working with. If dict iteration
order is part of their semantics – which it is now – then I want my REPL to
show me that order. It's true that this is particularly important for
teaching (see the link above to Allison Parrish's experience with this),
but it's not just students who rely on IPython to accurately describe the
objects they're working with.

Not sorting also gives very intuitive output in lots of cases, e.g.
'json.load(...)' will print the keys in the same order they are in the file
I'm looking at in the next window over. HTTP headers are printed in the
same order they appear on the wire. Etc.

AFAICT the entire argument about pprint in that thread is "the pprint docs
said we sort the keys, therefore there can never be any discussion about
whether that's still a good default, for our docs are forever inscribed in
stone". Pretty sure IPython hasn't made any similar commitments about its
implicit repr() output.

I agree it'd be nice to have some way to sort the keys in some situations.
Rather than making this a piece of global configuration though, I'd be more
interested in if there was a quick and easy way to request it for a
particular situation.

**Comment by takluyver** [comment]
Yeah, I think showing them in insertion order in 3.7 is probably the right thing to do. I just don't think it's as clear cut as you're suggesting. And I fully expect to get bugs filed by people who like the existing behaviour.

**Comment by takluyver** [comment]
Does anyone know if the pronouncement for dicts in 3.7 also applies to sets? IIRC in CPython they share most of their implementation, but I don't know if the change in language definition applies to sets as well.

**Comment by njsmith** [comment]
I don't think sets and dicts actually share any implementation in CPython (surprisingly), and sets haven't become ordered either in theory or in practice.

**Comment by takluyver** [comment]
PR #10958
