### ISSUE TITLE
Blinking prompt on OSX 10.6

### ISSUE THREAD

**Issue by savage13** [ipython/ipython#10187]
The default terminal prompt for ipython blinks for the OSX 10.6 Terminal.app
% ipython --colors=NoColor 
makes for a non-blinking session, but a set of parentheses still blinks as does the prompt after pressing Ctrl-D and a green line appears over the prompt.  
colors schemes of Linux and LightBG have the same problem as Neutral.
For example:
In [1]: a = 10
In [2]: a = [10,20,30]

The prompts In[#]: blinks, as do the numbers, but the 'a' and '[', ']', and ',' do not blink

I do not see this behavior with OSX 10.9 Terminal

**Comment by Carreau** [comment]
Hum, I don't have 10.6 available (I'm on 10.10), you can try to go to TerminalApp preferences and play with the profile configuration. You should be able to uncheck "allow blinking text" as a workaround.

**Comment by savage13** [comment]
Disabling "Allow blinking text" in Terminal.app Preferences/Settings (Under Text) eliminates blinking text.  Curious as to why it is blinking?

**Comment by Carreau** [comment]
> Disabling "Allow blinking text" in Terminal.app Preferences/Settings (Under Text) eliminates blinking text. Curious as to why it is blinking?

That seem to be a mishandling (?) of the terminal.app in 10.6.  It may confuse some color information with blinking. I can't say _for sure_  but it seem to be a [known issue](https://github.com/fish-shell/fish-shell/issues/963) that may be fixed by changing terminal type. 

Also I would recommend to try another terminal emulator (like iTerm 2) on OSX. Terminal.app is one of the worst you can have.

**Comment by Carreau** [comment]
I'm going to close as I doubt there is anything we can do, please let us know if you find an alternative solution.

**Comment by savage13** [comment]
Changing the TERM environment variable does not help (sadly)
env TERM=rvxt ipython  (blinking)
env TERM=vt100 ipython (blinking)
env TERM=dumb ipython (blinking)

Turning off "Allow blinking text" in the Preferences / Setting does work

**Comment by takluyver** [comment]
I don't think there's anything we can do, but @jonathanslenders might have some idea of what's going wrong or how to work it out.

**Comment by savage13** [comment]
I am fine with the solution as is.  Thanks for the help with this.

**Comment by rajikalk** [comment]
Hi there, 

I realise this issue is closed, but I'm having the exact same issue on another server that I don't have root access to. I did an update to some software (yt) on my user and after that update I guess ipython changed?

This is one of those systems where I load modules using "module load". The version of python I load is python/2.7.11 and the version of ipython that is used is IPython 5.3.0. Could there be some conflict between the versions?

This blinking is very frustrating. All the things that savage13 mentioned is happening, and most of what I type is blinking as well at tab options.

**Comment by rajikalk** [comment]
So I've just reverted back to version 4.2.1 because that seems to be the latest version I can use without having this problem.
