### ISSUE TITLE
Can't Reverse Search History Even though it's in history.sqlite file

### ISSUE THREAD

**Issue by akras-apixio** [ipython/ipython#10287]
I am on Mac OSX,

Have been using ipython for about 6 months with no problem.

Now the reverse search in history only shows some recent items.

When I look into the `history.sqlite` file I see the data there.

Not sure if it's a bug or a feature. May be I had too much history and it limited search? 

Would really appreciate your guy's feedback.

```
{'commit_hash': u'5be56c7',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/usr/local/lib/python2.7/site-packages/IPython',
 'ipython_version': '5.2.2',
 'os_name': 'posix',
 'platform': 'Darwin-15.6.0-x86_64-i386-64bit',
 'sys_executable': '/usr/local/opt/python/bin/python2.7',
 'sys_platform': 'darwin',
 'sys_version': '2.7.12 (default, Jun 29 2016, 14:05:02) \n[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)]'}
```

**Comment by takluyver** [comment]
I'm assuming that the reverse search feature you mean is either Ctrl-R or up-arrow? We load the last 1000 inputs into that search mechanism. There are a couple of workarounds available:

- Use a magic function `%history -g pattern` to search the history database. It will show you numbers like `763/70` to identify inputs. You can use these with the `%recall` magic to bring a previous input to the prompt.
- Increase the number of inputs loaded for rapid lookup by configuring `InteractiveShell.history_load_length` to e.g. 10000. Loading a lot of history may slow down startup; I haven't experimented with it.

Historically, we had no choice but to pre-load the terminal search when IPython started, because that was what readline required. Since IPython 5, we've switched to prompt_toolkit, which might make it possible to plug terminal history search into the database more directly. But it's probably fiddly, and we're used to living with the limitations I explained, so we haven't tried to do it yet.

**Comment by akras-apixio** [comment]
Ah, I c. That explains it. I assumed that it search full history. Seem to work as if it did with my current use case.

Please close the issue.

**Comment by alphaCTzo7G** [comment]
@akras-apixio @takluyver , thanks so much for this... I thought I had somehow messed up my ipython config, which resulted in Ctrl-R working only for recent inputs :)

I will use the `InteractiveShell.history_load_length = 100000` to see if it works.
