### ISSUE TITLE
simplegeneric is super out of date, vendor the library or take over maintainership of a fork

### ISSUE THREAD

**Issue by graingert** [ipython/ipython#10293]
last uploaded in 2012, and no wheel.

**Comment by takluyver** [comment]
Once we drop Python 3.3 support, we can use [functools.singledispatch](https://docs.python.org/3.5/library/functools.html#functools.singledispatch). I don't think there's any urgency to move away from simplegeneric, though.

**Comment by graingert** [comment]
@takluyver might be worth using https://pypi.python.org/pypi/singledispatch with a extras_require

**Comment by takluyver** [comment]
Unless there's a problem with simplegeneric, I'm inclined to say no. Changing stuff always comes at a cost, and there's no upside I can see until we can get rid of a dependency.

We're planning to drop Python 3.3 when it reaches EOL, which is around this Autumn, IIRC.

**Comment by graingert** [comment]
@takluyver with a conditional extras_require you would be getting rid of a dependency on most installs.

**Comment by takluyver** [comment]
Right, but a conditional dependency can bring its own issues. I don't see
any problems with simplegeneric, so I think it's simplest to leave it as is
for a few more months.

On 14 Feb 2017 6:32 p.m., "Thomas Grainger" <notifications@github.com>
wrote:

@takluyver <https://github.com/takluyver> with a conditional extras_require
you would be getting rid of a dependency on most installs.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/ipython/ipython/issues/10293#issuecomment-279793691>,
or mute the thread
