### ISSUE TITLE
Using tabs in Jupyter notebook cells

### ISSUE THREAD

**Issue by keldLundgaard** [ipython/ipython#10423]
I would like to be able to use tabs in Jupyter Notebook cells. It is currently not possible as far as I know to type in a tab in a cell as it will automatically be converted into spaces. My codebase uses tabs, so I would like to use tabs in my notebooks too. 

This related issue was closed without a resolution to the problem:   https://github.com/ipython/ipython/issues/2888/
Just visualizing tabs with ---> in Jupyter notebook cells is not a solution to the problem. We should be allowed to toggle the code that converts tabs to spaces. 

Please advice.

**Comment by willingc** [comment]
Hi @keldLundgaard,

Thanks for your question here and on #2888; also, thanks for using Jupyter and IPython.

Reading the comments on the other issue, @Carreau's response lays out the technical reasons why this hasn't been implemented. I would like to be both responsive and practical as I look at your request. Tabs are a bit problematic since straightforward handling of them in the notebook (i.e. toggle) isn't trivial both due to architecture and the use for completion as well.

I asked another core developer on the project, and this "may" be possible in a future post-beta JupyterLab release. It "may" also be possible for you to use 'nbconfig' to customize your personal profile for the notebook (https://jupyter-notebook.readthedocs.io/en/latest/frontend_config.html).

Is there a particular use case for why tabs are needed in the notebook cells (beyond convenience/consistency for you)? Perhaps a bit more information about your use case would generate other options.

Thanks! - Carol

**Comment by keldLundgaard** [comment]
Hi @willingc

I’ve managed to convert our team to the space religion with the help of your reply. And as a result, I can now easily hit my LOC target for the year! 

Thanks!
Keld

**Comment by willingc** [comment]
@keldLundgaard Thanks! Happy to help :smile: Congrats too. :cake:

**Comment by esternin** [comment]
```
%%file Makefile
hello: hello.c
    cc -o hello hello.c
```
is why we need TABs instead of spaces: make assumes tabs, and ONLY tabs, as valid separators and crashes out if this is not done. 

I use workaround
```
%%bash
echo    "hello: hello.c" > Makefile
echo -e "\tcc -o hello hello.c" >> Makefile
```
but in a teaching environment - where I use jupyter notebook, this is inadequate.

**Comment by esternin** [comment]
I see no way to re-open the issue, so posting as new.
