### ISSUE TITLE
peculiar behavior in round in ipython 3.5.2

### ISSUE THREAD

**Issue by irairglow** [ipython/ipython#10424]
After importing numpy as np
b = round(np.cos(np.pi/4), 4)  results in:
b = 0.70709999999999995
What I expect is what I get from ipython 2.7.12
b = round(np.cos(np.pi/4), 4) resulting in:
b = 0.7071
Is there some reason for this behavior that I am not recognizing?
(both run on 4.4.0-57-generic #78-Ubuntu SMP Fri Dec 9 23:50:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
with python and ipython both 2.7 and 3.5 - obtained from Ubuntu registries python and python3
round works correctly with np.pi and np.e on both (also irrational number, as should be cos(pi/4), but works incorrectly again with sqrt(2.0)  which would be expected since the above is sqrt(2.0)/2

**Comment by Carreau** [comment]
I'm unsure I understand in what way IPython's behavior differs from Python:

```
python
Python 3.6.0 |Continuum Analytics, Inc.| (default, Dec 23 2016, 13:19:00)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> b = round(np.cos(np.pi/4), 4)^C
KeyboardInterrupt
>>> import numpy as np
>>> b = round(np.cos(np.pi/4), 4)
>>> b
0.70709999999999995
>>>
 ~/dev/notebook master $ python2
Python 2.7.13 (default, Dec 18 2016, 07:03:34)
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as  np
>>> b = round(np.cos(np.pi/4), 4)
>>> b
0.7071
>>>
```

(same result with IPython) SO if this is an issue it's an Python issue, not IPython as for as I understand.

**Comment by irairglow** [comment]
You are correct, it seems a python problem that I can't find the reason 
for. But it is strange, that Internet search I can't find someone 
mentioning it. I am fairly new to python programming but I don't think I 
am missing anything here. The change in round() from python 2.7 to 3 was 
in rounding up for 0.5, nothing mentioned on this score where the number 
of digits is obviously wrong. I am trying to find this on python.org, 
but having trouble.

**Comment by takluyver** [comment]
Looks like a [floating point error](http://0.30000000000000004.com/). See this SO answer:

http://stackoverflow.com/questions/25898733/why-does-strfloat-return-more-digits-in-python-3-than-python-2

It's not computing a different number, it's just a change in how the number is displayed.

**Comment by Carreau** [comment]
(I replied yesterday but github ate my reply, here is it again, it's more than just a floating point computing. )

> You are correct, it seems a python problem that I can't find the reason
> for. But it is strange, that Internet search I can't find someone
> mentioning it. I am fairly new to python programming but I don't think I
> am missing anything here. The change in round() from python 2.7 to 3 was
> in rounding up for 0.5, nothing mentioned on this score where the number
> of digits is obviously wrong. I am trying to find this on python.org,
> but having trouble.

Well that's how floating point arithmetic works, so I'm not surprised by the behavior. It seem like just a difference in the number of bytes used: 

http://0.30000000000000004.com/

So let's check the type returned by `round`... and on python 2 it's `float`, on python 3 it's `numpy.float64`... Let's look at `round` documentation on [python2](https://docs.python.org/2/library/functions.html#round) and [python3](https://docs.python.org/3/library/functions.html#round) ... ha python 3 now have `__round__(...)` special method you can define for number, that might be it. let see numpy often reimplement some python function for efficiency and consistency... lets use `numpy.round` instead of builtin round...


```
$ python
Python 3.6.0 |Continuum Analytics, Inc.| (default, Dec 23 2016, 13:19:00)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from numpy import round as nround
>>> import numpy as np
>>> b = round(np.cos(np.pi/4), 4)
>>> b, type(b)
(0.70709999999999995, <class 'numpy.float64'>)
>>>
$ python2
Python 2.7.13 (default, Dec 18 2016, 07:03:34)
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from numpy import round as nround
>>> import numpy as np
>>> b = round(np.cos(np.pi/4), 4)
>>> nb = nround(np.cos(np.pi/4), 4)
>>> b, type(b), nb, type(nb)
(0.7071, <type 'float'>, 0.70709999999999995, <type 'numpy.float64'>)
```

Tada, it works ! (except for the number of __displayed__ digits, but that's due to the fact that the value cannot be exactly represented in binary to decimal notation) but that's still truncated at 4 digits and that's how floating point number behave regardless of language.

**Comment by irairglow** [comment]
Matthias,

I thank you for your time. I agree that there are subtleties in floating 
point computing, but if the round() does what it says it should, it 
should take the string form of the floating point representation and 
only display the number of digits (elements past the decimal) correctly 
and in python 3 it doesn't do that. That might be because the floating 
to string changed, but how the did the string extraction in the new case 
doesn't work correctly. I don't want to be pedantic here, but when I 
round to 4 digits I shouldn't get 17. I guess one can print things out 
with formats, but what is the purpose of round() or numpy round()? Since 
the number in the case of cosine of pi/4 is irrational and can't be 
represented by the 15 or 17 digits trying to round it doesn't work 
correctly. If I set another variable equal to just the 17 digits printed 
out, then take round() it works fine.

Here is another peculiarity:
c = np.arccos(-1.0)
c
3.1415926535897931
(of course arccos of -1.0 should be pi)
c == np.pi
True
round(c, 4)
3.1415999999999999
round(np.pi, 4)
3.1416
Now if they are equal as the comparison indicates, why does round to 4 
digits NOT give the same answer?

Jeremy

**Comment by takluyver** [comment]
The `round()` function gives you a float, it's not responsible for how the float is displayed. If you want to control how it's displayed, use string formatting:

```python
print("{:.4g}".format(np.cos(np.pi/4)))  # prints 0.7071
```

This is about the way Python itself works, though, not specific to IPython. So if you want to argue about it, we're not the people to argue with. ;-)

**Comment by Carreau** [comment]
> it
> should take the string form of the floating point representation and
> only display the number of digits (elements past the decimal) correctly
> and in python 3 it doesn't do that

Well it does... if you round a _float_, but in Python 3 if you don't explicitly ask for a float, you get a `numpy.float64`. You need to cast it if you want to have this behavior.
```
In [3]: b = round(float(np.cos(np.pi/4)), 4)
In [4]: b
Out[4]: 0.7071
```

same for `np.pi`, `np.pi` is a float, not a `numpy.float64`. `arccos(-1.0)`  though is a `numpy.float64`, so indeed you do not get the same. It _may_ be a bug (or a missing feature) of numpy that mis-round (I doubt it). It's likely that you see a behavior of 16/32 bits vs 64 bits. 

If you cast explicitly as 16 bits it works as expected: 

```
In [22]: round(np.float16(np.arccos(-1.0)), 4)
Out[22]: 3.1406
```

Same if you take your np.pi float and cast it to a float64:

```
>>> round(np.float64(np.pi), 4)
3.1415999999999999
```

So you *are* seeing floating point arithmetic and the use of the binary base to represent numbers. 

Note that the round docs does not say that it prints, it says that it rounds in decimal digits:

```
round(number[, ndigits]) -> number

Round a number to a given precision in decimal digits (default 0 digits).
This returns an int when called with one argument, otherwise the
same type as the number. ndigits may be negative.
```

So round does: float16/32/64/128 -> decimal -> rounded-decimal -> same float type as originally.

You have 2 loss of precision: the conversion from binary to decimal, and the conversion from decimal to binary. So you do round to 4 digits in your case, but the conversion back to binary can only convert to the closest binary number available. Printing floating point number in decimal base is still an [active research subject](http://www.serpentine.com/blog/2011/06/29/here-be-dragons-advances-in-problems-you-didnt-even-know-you-had/) with still major improvements that are less than 15 years old.

> Now if they are equal as the comparison indicates, why does round to 4
> digits NOT give the same answer?

That's because comparison are made using the [machine epsilon](https://en.wikipedia.org/wiki/Machine_epsilon) for the given types, which finfo can give you: 

```
In [28]: np.finfo(np.float32)
Out[28]: finfo(resolution=1e-06, min=-3.4028235e+38, max=3.4028235e+38, dtype=float32)
```

I'm not familiar with the internal details but to compare number we are likely casting them to the same type before comparison (for numbers). That's what's allow you to compare int and floats:

```
>>> 1 == 1.0
True
```

Not all languages allow you to compare different types, and in C IIRC you need to to explicit conversion. 

You can try to bring that to the numpy and or Python folks, but this likely is a behavior standard with [IEEE 754](https://en.wikipedia.org/wiki/IEEE_floating_point) which is how computer are supposed to represent binary floating point. 

You can look at the floating point tutorial of Python as well : https://docs.python.org/3/tutorial/floatingpoint.html

So we don't disagree that this might be confusing at first, but that's how computer works, and it is a perfectly reasonable behavior.
