### ISSUE TITLE
No browser entry in ipython_notebook_config.py.

### ISSUE THREAD

**Issue by obiii** [ipython/ipython#10430]
When the container runs, it throws error that no runnable web browser found.
I checked in container bin/bash and ipython_notebook_config.py contains:
c.NotebookApp.browser=' '
and I am unable to change it because everytime i exit the container it loses all the changes i made through bin/bash.

Please help regarding this.

**Comment by takluyver** [comment]
You probably want to run the browser outside the docker container anyway, because it runs in a GUI environment. If you're starting the server inside a container, it can't start a browser for you outside the container, so you'll need to start the browser and navigate to the server address separately.

If you want to avoid it trying to start a browser, you can use the `--no-browser` command line option.

**Comment by ivanov** [comment]
Hi @obiii  - It sounds like you're running into just a feature of docker, and not specific to the notebook  - docker runs exactly the image you specify, so all files, including the config file, return to their original state every time you restart the container. Perhaps you need to run something like `docker commit` to persist your changes. Another option might be to mount a directory with your custom config.

If you used https://hub.docker.com/r/jupyter/notebook/ - you should know that it was deprecated in favor of one of the `*-notebook`  versions in [jupyter/docker-stacks](https://github.com/jupyter/docker-stacks).  If you want to propose changes to those stacks, [you can open an issue there](https://github.com/jupyter/docker-stacks/issues), but I am going to go ahead and close this one.

Thank you and happy hacking! :bowtie:
