### ISSUE TITLE
Distribute IPython as a Snap

### ISSUE THREAD

**Issue by flexiondotorg** [ipython/ipython#10525]
As requested in an email exchange with @takluyver I'm raising this as an issue. I used IPython and Jupyter in a previous role, both are great tools :-)

### Issue Description

Linux users would benefit from having Snap packages of IPython available for easy installs and updates.

Snaps are self-contained application bundles that can be installed on the most popular Linux distributions, such as Ubuntu, Debian, Fedora, openSUSE and Arch, without having to build separate versions for each one. They give users immediate updates as soon as you publish a new release, without them having to manually download and unpack it, and will automatically create systemd services for managing daemons including restarting when updates are applied.

The Snapcraft tool makes it easy to build snaps from source referencing `requirements.txt` or python modules that already exist in the Ubuntu archive. The [Snap Store](https://dashboard.snapcraft.io) lets you publish directly to users, without a manual review or approval process, so you can release on your own schedule and give you access to install metrics.

If anybody is interested, you can find documentation and examples on [snapcraft.io](https://snapcraft.io) and ask questions on [forum.snapcraft.io](https://forum.snapcraft.io)

#### Expected Results

The latest version of IPython is available to install as a Snap with `snap install ipython`

**Comment by takluyver** [comment]
Thanks Martin :smiley: 

I'm taking an interest in the new Linux application packaging systems, Snap & Flatpak, and I've had a go at building packages for both. Traditional Linux distro packaging has been problematic for us, especially with Jupyter moving fast and relying on a range of Javascript packages; versions available from `apt` in particular are usually out of date, and on occasion the changes made by packagers have introduced bugs. We no longer recommend that anyone install IPython/Jupyter from Linux distro repositories.

My questions about making a Snap package would be:

1. **Sandboxing**: My understanding of both Snap & Flatpak is that they're centred around sandboxing applications for security. I'm definitely :+1: to this in general, but an interactive shell that runs code entered by the user needs to be able to do whatever the user wants. Is it practical to distribute an application without sandboxing?
2. **Composition**: Particularly for Jupyter, there are parts which can be added to give the system new capabilities, such as kernels for different languages. This doesn't fit neatly with the model of installing a standalone application. How do snaps deal with such composition, both with components in other snaps and components that may be installed by other methods?
3. **Advantages**: If we're not using the sandboxing, in what situation would a user want to install IPython/Jupyter via snap rather than the options we current recommend (pip or conda)? A user running Python code is highly likely to want one of those tools to install Python packages anyway. They're both cross platform, and we can do a decent job of keeping the packages of our software up to date. To recommend an installation option specific to one operating system, I think we'd need a fairly clear advantage. There are enough packaging systems around now that I don't think we should support a system just because it's there. Obviously this doesn't stop people building third-party packages of our code, though.
