### ISSUE TITLE
No (Qt5) GUI event loop integration with `--simple-prompt`

### ISSUE THREAD

**Issue by pe224** [ipython/ipython#10710]
Hi. When I open IPython with the `--simple-prompt` flag and try the following
```python
%gui qt5
from PyQt5.QtWidgets import QMainWindow
win = QMainWindow()
win.show()
```
IPython crashes with `QWidget: Must construct a QApplication before a QWidget`.
If I construct a QApplication the GUI remains unresponsive until I call `QApplication.exec()` blocking the IPython shell.
This has implications for the interactive mode of `matplotlib` (with Qt5 backend) which fails as well despite `%matplotlib qt5`.

I'm calling IPython with Python 3.5.2 (32bit) from Windows 10 `cmd.exe`, please tell me if you need more info.

Is it possible to get the event loop integration together with `simple-prompt`?

I'm aware that Jupyter works differently, but FYI the above code runs properly with
`jupyter console --simple-prompt`.

**Comment by takluyver** [comment]
The GUI integration in terminal IPython is not compatible with `--simple-prompt`, because it relies on prompt_toolkit. It works with `jupyter console --simple-prompt`, because that is using the separate GUI integration for IPython's *kernel* interface. From the point of view of the kernel, it doesn't matter whether you use `--simple-prompt` for the frontend, or even which frontend you use.

**Comment by jdtsmith** [comment]
And yet, strangely, `--simple-prompt` can and does process matplotlib events, entirely independent of prompt_toolkit.  How is a mystery: #13898.
