### ISSUE TITLE
ImportError: cannot import name 'shadowns'

### ISSUE THREAD

**Issue by kevinlu1211** [ipython/ipython#10741]
I'm trying to run the command  ipython kernel install and I am getting the error specified in the title, here is the stack trace:

```
  File "<stdin>", line 1, in <module>
  File "/Users/kevinlu/miniconda3/envs/pytorch/lib/python3.6/site-packages/IPython/__init__.py", line 55, in <module>
    from .terminal.embed import embed
  File "/Users/kevinlu/miniconda3/envs/pytorch/lib/python3.6/site-packages/IPython/terminal/embed.py", line 15, in <module>
    from IPython.core.interactiveshell import DummyMod, InteractiveShell
  File "/Users/kevinlu/miniconda3/envs/pytorch/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 37, in <module>
    from IPython.core import shadowns
ImportError: cannot import name 'shadowns'
>>> from IPython.core import shadows
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'shadows'
>>> from IPython.core import shadow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'shadow'
>>> from IPython.core import shadow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'shadow'
```

**Comment by Carreau** [comment]
This is likely stales pyc files on your side. 

These lines have been removed from IPython [a couple of month ago](https://github.com/ipython/ipython/pull/10604/files)

try:

```
$ cd /Users/kevinlu/miniconda3/envs/pytorch/lib/python3.6/site-packages/IPython
$ find . -name '*.pyc' -delete
```

Otherwise try uninstalling IPython and reinstalling. Make sure the `/Users/kevinlu/miniconda3/envs/pytorch/lib/python3.6/site-packages/IPython/core/interactiveshell.py` file does not have the "import shoadowns" line or something is wrong. Maybe conda messed up the updating.

**Comment by kevinlu1211** [comment]
Hmm I tried deleting all the `*.pyc` files and also reinstall with conda, but both don't seem to work any other ideas? Here is what my conda is installing:

```
(pytorch) kevinlu@Kevins-MBP:~/Documents/Learning/Pytorch $ conda install ipython
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /Users/kevinlu/miniconda3/envs/pytorch:

The following NEW packages will be INSTALLED:

    ipython: 6.1.0-py36_0

Proceed ([y]/n)? y
```

**Comment by Carreau** [comment]
Can you do `IPythin.core??` to figure out which file it is picking up ?

On Aug 12, 2017 3:07 AM, "kevinlu1211" <notifications@github.com> wrote:

Hmm I tried deleting all the *.pyc files and also reinstall with conda, but
both don't seem to work any other ideas? Here is what my conda is
installing:

(pytorch) kevinlu@Kevins-MBP:~/Documents/Learning/Pytorch $ conda
install ipython
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment
/Users/kevinlu/miniconda3/envs/pytorch:

The following NEW packages will be INSTALLED:

    ipython: 6.1.0-py36_0

Proceed ([y]/n)? y

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/ipython/ipython/issues/10741#issuecomment-321971447>,
or mute the thread

**Comment by kevinlu1211** [comment]
What do you mean by that? Do you mean something like `python -c import IPython.core`? If so I did it and everything is fine. Also it seems like conda has fixed the problem I am able to install a kernel fine now, very weird...

**Comment by Carreau** [comment]
I meant somthing like this, sorry fr the delay I was away this WE: 

```

In [1]: import IPython

In [2]: IPython.core??
Type:        module
String form: <module 'IPython.core' from '/usr/local/lib/python2.7/site-packages/IPython/core/__init__.pyc'>
File:        /usr/local/lib/python2.7/site-packages/IPython/core/__init__.py
```

If reinstalling with conda work, it was probably stale file. So i'm going to close for now, but feel free to reopen or comment.
