### ISSUE TITLE
`post_execute` and `post_run_cell` hooks not always triggered

### ISSUE THREAD

**Issue by fniephaus** [ipython/ipython#10774]
Due to various early returns in the code below, `post_execute` and `post_run_cell` hooks are not triggered in some cases. Since the pre hooks are always called, this is either a bug or the [docs](http://ipython.readthedocs.io/en/stable/config/callbacks.html#post-run-cell) should mention that post hooks are not guaranteed to be triggered.

https://github.com/ipython/ipython/blob/ca86b79bfd5cdd633ea6cb9c18bb2c1c493402a1/IPython/core/interactiveshell.py#L2694-L2739

/cc @craigcitro

**Comment by Carreau** [comment]
Thanks for the report, you are right that we should split the post_execution hooks into hooks that execute after every requests, or only after every valid Python request. I don't think we should fix the current ones, but provide variants that also trigger even when the pre-execute fails.

**Comment by craigcitro** [comment]
Hey @Carreau -- I'm curious about the details of what you're proposing.

* Do you mean that you want to allow users to set separate hooks for the various ways a cell can fail, eg `post_syntax_error_hook`, `post_preprocessing_error_hook`, that sort of thing? I feel like that's a lot of complexity. For my money, I'd rather provide a way to customize the `error_before_exec` function that gets used.

* Is the motivation for adding a new hook simply to avoid a subtle behavior change? As it is, I'm betting that most (if not all) users of the `post_*` hooks actually *expect* that they're always being executed, and would be surprised by the behavior @fniephaus ran into here. But of course I'm saying that based on 0 data. 😀 😀 😀  Do you know of a use case for the current behavior?

* If we do go the route of new hooks, do you imagine having something like a `post_execute_exception_hook`, where we know exactly one of that and `post_execute_hook` will be triggered? Or something more like a `finally_hook`, where it's executed no matter what?

Thinking it through, I could see an argument that the right answer here is to say "we will be explicit about documenting and sticking to the current behavior, because it's a subtle behavior change. If you want something else, you should override `run_cell` yourself." I think that would work for our use case, but I bet we aren't the first and won't be the last to stumble on this, so we wanted to look at fixing it at the root first. 😉

**Comment by Carreau** [comment]
> Do you mean that you want to allow users to set separate hooks for the various ways a cell can fail

Probably not _that_ granular. 

> Is the motivation for adding a new hook simply to avoid a subtle behavior change?

Yes. 

> But of course I'm saying that based on 0 data

I see you are 0-indexed. And so we have at least 1 more data point: I would have expected these hooks to not trigger on failure :-) 

> If we do go the route of new hooks, do you imagine having something like a post_execute_exception_hook, where we know exactly one of that and post_execute_hook will be triggered? Or something more like a finally_hook, where it's executed no matter what?

Yes, probably a `finally_hook`, that get a parameter with whether things failed and how. Then it's explicit to user when it is called and give you all the flexibility you can get.

We'll better document anyway !

Thanks !
