### ISSUE TITLE
Build Documentation in Travis 

### ISSUE THREAD

**Issue by jzf2101** [ipython/ipython#10895]
Based on #10891, we are not currently catching documenation build issues in our CI.  As in Jupyter notebook https://github.com/jupyter/notebook/issues/1749 , we should be both building the documentation and documenting https://github.com/jupyter/notebook/issues/1749 how to build the docs. 

@Carreau should we also get Appveyor to build?

**Comment by jzf2101** [comment]
@lesley2958 are you interested in taking this on?

**Comment by Carreau** [comment]
No getting things to work on appveyor is generally complex. Travis is
enough and closer to readthedocs setup.

**Comment by takluyver** [comment]
We should check whether something like the markdown fenced code block syntax actually produces an error. I would guess Sphinx issues a warning and carries on.

We can tell Sphinx to fail on warnings, so we check that the docs build with no warnings. But people might find that strictness irritating. I got four warnings building the docs just now, for instance.

**Comment by Carreau** [comment]
Let's get it to build first, then we can make it more restrictive progressively (like check links do not 404...etc).

**Comment by takluyver** [comment]
Sounds good.

**Comment by douglatornell** [comment]
Summarizing today's flurry of activity on this issue:

This is work that was done at the PyCon Canada sprints under the guidance of @jzf2101.

In #10911 @olesyabar and @syutbai added the Sphinx docs build to Travis-CI.

In #10912 I added docs for contributors to tell them how to build the docs locally.

The test of the Travis-CI docs build, and local docs builds produce 6 warnings at this time [1].
#10913 fixes markup in docstrings to resolve 2 of those warnings.
326f41b adds the `docrepr` package to the docs build dependencies to resolve another warning.
Two more are caused by the way that a docstring in python/cpython/Lib/pdb.py is written [3] and the possible resolution may lie in Sphinx [4].

The remaining warning is::
```
WARNING: dot command 'dot' cannot be run (needed for graphviz output), check the graphviz_dot setting
```
and @olesyabar is working on that.

[1] https://github.com/ipython/ipython/pull/10911#issuecomment-345769322
[2] https://github.com/python/cpython/blob/423fd362f8e4d6c867a5afc8ac7cbeeb66cac19c/Lib/pdb.py#L1107
[3] https://github.com/ipython/ipython/pull/10911#issuecomment-345827420
[4] sphinx-doc/sphinx/issues/4251

**Comment by Carreau** [comment]
Oh thanks @douglatornell for the summary and he crosslinks this is extremely useful and appreciated. I'm on european timezone so will try to review some of that in the next few hours before PyConCa wakes up !

**Comment by jzf2101** [comment]
@Carreau Are we ready to close this for now?

**Comment by takluyver** [comment]
I think so. Thanks to all the PyconCA sprinters who worked on this and related issues.

The next steps for the docs in CI are to clear up the remaining warnings, and then use the Sphinx option which causes an error if any warning occurs.
