### ISSUE TITLE
Using tabs in Jupyter notebook cells (re-open #10423)

### ISSUE THREAD

**Issue by esternin** [ipython/ipython#10994]
```
%%file Makefile
hello: hello.c
    cc -o hello hello.c
```
is why we need TABs instead of spaces: make assumes tabs, and ONLY tabs, as valid separators and crashes out if this is not done. 

I use workaround
```
%%bash
echo    "hello: hello.c" > Makefile
echo -e "\tcc -o hello hello.c" >> Makefile
```
but in a teaching environment - where I use jupyter notebook, this is inadequate.

I added editor-tabs nbextension to the Home, and disabled "disable configuration for nbextensions without explicit compatibility" check mark in the console, but it did not change the behaviour of the notebook, even after a kernel restart.  This functionality is desperately needed in %%file cells, and TAB-as-completion is unnecessary in those.

**Comment by Carreau** [comment]
This is an issue with Jupyter/Notebook , or jupyterlab/jupyterlab not ipython/ipython, but we are aware of it, and jupyterlab (that should be officially released soon, but is already available) allows you to choose whether indent is done with space or tab.

**Comment by esternin** [comment]
I did not realize ipython is still a thing, I assumed jupyter was a rebrand/replacement.

But I also see that your comment betrays a continuous misunderstanding, so perhaps I better elaborate. Every time an issue of tabs comes up, everyone assumes it's about the automatic indentation style.  It is not! - and in fact I personally prefer and always use spaces, not tabs, to indent code.  But the **ability** to enter a TAB character when desired must be available, as other programs and environments may require it (Makefile being one example).

So, for example, including somewhere in the notebook this:
```
%%javascript

IPython.tab_as_tab_everywhere = function(use_tabs) {
    if (use_tabs === undefined) {
        use_tabs = true; 
    }

    // apply setting to all current CodeMirror instances
    IPython.notebook.get_cells().map(
        function(c) {  return c.code_mirror.options.indentWithTabs=use_tabs;  }
    );
    // make sure new CodeMirror instances created in the future also use this setting
    CodeMirror.defaults.indentWithTabs=use_tabs;

    };

IPython.tab_as_tab_everywhere()
```
converts ALL cells to tabs. This is a poor solution, distracts from the flow of the notebook, and not at all what I am asking for.

I would like to have, say, Alt-TAB or Ctl-TAB generate a raw tab and not be replaced with 4 spaces, but only when I need that.  It's not even a per-cell control, it's just one special character. 

Is there an equivalent to vi's Ctl-v entry mode in ipython/Jupyter/jupyterlab (what is that? and how is it different from jupyter?).

**Comment by Carreau** [comment]
> I did not realize ipython is still a thing,

No worries

> I assumed jupyter was a rebrand/replacement.

Yes and No. Jupyter is the language agnostic part. IPython is still the tiny part that does Python execution. That is to say you can use Jupyter+IPython , Jupyter+Scala,  Jupyter+Haskell...

And Yes, I understood your problem, that you want to have a tab in a specific location, but not generally. The reason you can't get tabs is indeed because we replace by 4 spaces as many user copy past and end up with mix of tab and space. Of course there are cases where you want to insert tabs. 

It's a tiny bit harder than in vim, emacs or any "native" application because of browser limitation. Typically we have to stay away from any alt- or shift- related shortcut as otherwise we'll break non-english layout. You may think "it's ok if a tine portion of user can't use some shortcut", and we may agree that this may not be a big issue, though in general each time we've tried to extend shortcuts, we've hit roadblock, from the top of my head:
  - typing `-` (minus) on a german keyboard was splitting cells, because minus needs `alt-` to be pressed. 
  - preventing French users from typing `|` 
  - preventing French users  from typing numbers

(Yes I used to have a french keyboard so I remember those one).

We are thus relatively restricted. 

There are some plans to provide "localized keymaps", disable by default, but a click away, and then we can add more convenient shortcuts we know work on some layouts. 

For now I believe in JupyterLab(more info below) going to the "Edit" menu and deactivate "Indent with space" (or whatever the menu is named), should allow you to insert tabs, at least temporarily, then you can revert to "indent with space". Yes it is inconvenient, and why I'm only suggesting it as a workaround. 

Notebook 5.3 should already allow custom commands and keyboard shortcuts (Help > edit Keyboard shortcut). The commands can be registerd by `custom.js` or notebook extensions, so I believed you should ba able to include that with custom keybinding on your system, and if it works we'll be happy to include it. We would have to discuss the exact keyboard shortcut but worst case it's still `Ctrl-P` then search for `insert a tab character` and then `Enter` in the command palette.


As for [JupyterLab](https://github.com/jupyterlab/jupyterlab) it's the new frontend (completely compatible with current notebook), that has been in dev for quite some time, and should be released soon (already unofficially released you can pip-install it). The team is currently polishing the docs.
Here is a not-so-recent screenshot to give you an idea:

![1_nlqmkeckc7u70j-5ynpk0a](https://user-images.githubusercontent.com/335567/35403787-af136244-01b5-11e8-8574-68dce477bf3f.png)


Almost no code is shared with current notebook and most of the keyboard handling has been redone, so most tricky things should be fixed or easier to fix.

**Comment by esternin** [comment]
Thanks for your explanations, @Carreau.  I am probably a rare user, as I know very little about python, so my use is Jupyter+gnuplot, Jupyter+octave, Jupyter+bash/file/fortran, for teaching purposes.

Because of that I must stick to the current versions that my sysadmin installs for me, cluster-wide, otherwise what I see and what the students see would not be the same. When Jupyterlab is released, I may make use of it - next year.

So the answer to my original question - is there a way to enter a raw TAB into a `%%file` - is NO.

I appreciate the difficulties of encoding and I would not want to impose an English keyboard on French users.  But being in a browser offers a different opportunity, of using markup, to bypass local keyboard bindings.  Is there a `%%file -translate-html ` option, so I could enter &#9; when I wanted a TAB and have it translate into a raw TAB when the file is written out?

Again, I am not looking for a universal handling of TAB vs. space, just something specific to %%file cell, which is effectively a built-in text editor.  TAB-based auto completion should not be enabled in those cells anyway, and so TAB handling is a purely stylistic issue in those cells. Whatever one's choice, an editor should enable the user to enter any character possible into the file, hence my asking for a Ctl-v-like mode.

Finally, I do not understand that bit about custom.js. Ctl-P (? you probably meant Ctl-F to search) searches in the page, not in the pop-up that Help->Edit Keyboard Shortcuts generates, but in any case, "insert a tab character" is not one of the available options.

Where should custom.js be, to be noticed? - in the Home ? somewhere in the .local or .config before the `jupyter notebook` server is launched? What should it contain to generate a toggle-like option in the menu?  If this route works, I would happily use it now, by telling students to download and place this file in their home spaces - a one-time operation.  Or are you talking about options only available in the future (Jupyterlab) ?

**Comment by esternin** [comment]
One other thought.  I just looked up the list of Edit Mode keystrokes:

- Tab : code completion or indent
- Shift-Tab : tooltip
- Ctrl-] : indent
- Ctrl-[ : dedent
- Ctrl-A : select all
- Ctrl-Z : undo
etc.  And I see there is room for `Ctrl-V : enter next character as-is. `

**Comment by Carreau** [comment]
> So the answer to my original question - is there a way to enter a raw TAB into a %%file - is NO.

Unfortunately, without custom modification indeed, the answer is no. (but see below it might work on "recent enough" notebooks)

> I appreciate the difficulties of encoding and I would not want to impose an English keyboard on French users. But being in a browser offers a different opportunity, of using markup, to bypass local keyboard bindings. Is there a %%file -translate-html option, so I could enter &#9; when I wanted a TAB and have it translate into a raw TAB when the file is written out?

There is not, but it is not hard to do either execute that in a notebook, or create a file and have it imported:

```
from IPython.core.magic import register_cell_magic

@register_cell_magic
def hfile(line, cell):
    with open(line.strip(), 'w') as f:
        f.write(cell.replace('&#9;', '\t'))
```

Now use `%%hfile`


> Again, I am not looking for a universal handling of TAB vs. space, just something specific to %%file cell, which is effectively a built-in text editor. TAB-based auto completion should not be enabled in those cells anyway, and so TAB handling is a purely stylistic issue in those cells.

Yes, that's in progress, the fill content of the `%%file` cell is sent to IPython which decide how to complete. in `%file`, I agree that it might not be always useful (unless you are actually creating a python file on disc).

I'll investivate Ctrl-V on Mac (we have to be careful on windows/linux  it may be the "Past" action.

> Finally, I do not understand that bit about custom.js. Ctl-P (? you probably meant Ctl-F to search) searches in the page, not in the pop-up that Help->Edit Keyboard Shortcuts generates, but in any case, "insert a tab character" is not one of the available options.

Sorry let me take a step bak,

Jupyter notebook allow user to drop a files named `custom.js` in their config folder (for me ~/.jupyter/custom/custom.js, but that may differ, try `jupyter --config-dir` to know yours). This javascript file allow to customize whatever (no guarantied API, but you can poke at, or replace , any existing methods to experiment). One thing you can do is defined custom command, for example insert a tab at current cursor position, the good thing is the underlying library already have a hook for "insertTab" which make things quite easy:

```
require(['base/js/namespace'], function (Jupyter) { // roughly of "wait for Jupyter to be loaded"
  var insert_tab  = {
        help: 'Insert tab at current cursor position',
        icon : 'fa-long-arrow-right',
        help_index : '',
        handler : function (env) {
            console.info("Inserting tab")
            var cell = env.notebook.get_selected_cell(); 
            var cur = cell.code_mirror.execCommand('insertTab') 
      }
  }
  Jupyter.notebook.keyboard_manager.actions.register(insert_tab, 'insert-tab-at-cursor', 'my-prefix')
  console.info('insert-tab-extension loaded')
})
```

These commands (previously named `actions` hence the above api, are automatically listed  in the command palette (Cmd-Shift-P, on mac, that I rebinded to Ctrl-P, sorry for the confusion). So the above looks like the following: 

![com1](https://user-images.githubusercontent.com/335567/35456376-12fa62d8-028a-11e8-99d8-eb8dcbaec612.gif)

You can then bind it to a _command mode_ keyboard shortcut:

<img width="686" alt="screen shot 2018-01-26 at 11 15 45" src="https://user-images.githubusercontent.com/335567/35456450-561823fc-028a-11e8-8c64-bf79906dd3d9.png">


There are way to change keymaps _in edit mode_ but that requires messing with [codemirror keymaps](https://codemirror.net/doc/manual.html#keymaps), (codemirror being the underlying library that edit code) and can be a bit brittle. You are also limited to predefined Codemirror commands which list you can find [here](https://codemirror.net/doc/manual.html#commands) instead of arbitrary programatic functions.

In our case we are lucky I was not aware but "insertTab" is one of these.
There is no official API or UI to change that so we're going to modify a config file by hand from a Python script, not sure how reliable or which version of the notebook that requires.

```
import os
conffile = os.path.expanduser('~/.jupyter/nbconfig/notebook.json')
import json
with open(conffile, 'r') as f:
    data = json.loads(f.read())
sub = data
for path in ['CodeCell','cm_config', 'extraKeys']:  # replace CodeCell by Cell to do that in all cells.
    val = sub.get(path)
    if not val:
        sub[path] = {}
    sub = sub[path]
sub['Ctrl-T'] = 'insertTab'
with open(conffile, 'w') as f:
    f.write(json.dumps(data, indent=2))
```

Be careful and backup your `~/.jupyter/nbconfig/notebook.json` in case you have other configuration. You'll see  that it stores other informations from the notebook, here is mine, with comments:

```
{
  "Cell": {
    "cm_config": {
      "lineNumbers": true   // line numbers for all cells by default
    }
  },
  "CodeCell": {
    "cm_config": {
      "extraKeys": {
        "Ctrl-T": "insertTab"   // Code cell only have Ctrl-T bind to insert tab see codemirror docs for which modifiers (Ctrl-Cmd... are alllowed)
      }
    }
  },
  "Header": false,
  "Notebook": {
    "Header": true,
    "Toolbar": false
  },
  "keys": {
    "command": { // command mode extra bindings. This section is automatically updated when you change things in "Help > Edit keyboard shortcuts."
      "bind": {
        "0,9": "jupyter-notebook:restart-kernel-and-run-all-cells",
        "ctrl-[": "jupyter-notebook:close-pager",
        "ctrl-r,t,l": "jupyter-notebook:toggle-rtl-layout",
        "ctrl-shift-o": "jupyter-notebook:clear-all-cells-output",
        "ctrl-x,meta-c,meta-b,u,t,t,e,r,f,l,y": "jupyter-notebook:edit-command-mode-keyboard-shortcuts",
        "space": "jupyter-notebook:scroll-notebook-down",
        "t": "my-prefix:insert-tab-at-cursor"
      },
      "unbind": [
        "space"  // unbind some default actions.
      ]
    }
  },
  "load_extensions": {
    "jupyter-js-widgets/extension": true
  }
}
```


As you can see all the pieces are actually there (I am surprised, I did not remembered all of that) and need a bit of documentation and UI work to be more accessible.

Does that help a bit more and make things clearer ? We could try the `Ctrl-V`, `Tab` trick but it may be a bit harder as it would require keeping track as to whether we are in raw mode or not.

**Comment by dturaev** [comment]
Wow, the problem of inserting a literal tab in Jupyter reminds me of [this xkcd cartoon](https://xkcd.com/1425/). So, what is currently the easiest way to do this in the editor? It's not for indenting, but for a tab in a here doc, that will go to a config file. A user-specific configuration with a custom `custom.js` is not a good solution for teaching. Also, I didn't find an "inserttab" command in the Jupyterlab `Commands` tab. At the moment, I'm copy-pasting a literal tab from someplace else.

**Comment by esternin** [comment]
This reminds me: I never thanked @Carreau  for a detailed and thoughtful workaround, a tour de force. Thank you!

But lust like @dturaev I adopted the two-click (left button select, middle button paste) solution to entering the TAB characters, for those rare occasions I need them.

I would still welcome the vi-inspired Ctl-V option (for verbatim) one-keystroke prefix (no mode switching, just one composite character), if it ever makes it into the interface.  There is no way I can suggest any of the approaches discussed here to a class of novice users, where I use jupyter notebooks, they would be overwhelmed.

**Comment by dgrigonis** [comment]
Would it be sensible to have an option to:

not invoke auto-complete if last character is space, but do a space-based tab instead?

I find that autocompleting space is not very useful to me personally and I miss the tab.

**Comment by Carreau** [comment]
Locking conversation, as pointed out earlier, this is not an issue in IPython and any improvement request need to be made on relevant repo.
