### ISSUE TITLE
IPython console shows no output (Out[n])

### ISSUE THREAD

**Issue by ttrang-tran** [ipython/ipython#10998]
Hi

I am trying to follow some Udemy courses on plotting a data matrix. When the lecturer defines the x and y value from data.csv then on his console, IPython shows the values under Out[n].  Mine doesn't. In my console I can only see In[n] which repeats my code. 

I have checked but cannot find solutions available elsewhere. Could you please help?
I am new to Computer Science so please be easy on me...

I am using Spyder with Anaconda and Qt console too... Just updated using conda to latest version and nothing's changed.

Thanks,
Chanie

**Comment by takluyver** [comment]
If you do e.g. `a = 1`, you normally have to then run `a` afterwards to see the value.

It's possible that your lecturer has set [a config option](http://ipython.readthedocs.io/en/stable/config/options/terminal.html#configtrait-InteractiveShell.ast_node_interactivity) which can make assignments like `a = 1` show the value as well. I wouldn't recommend using that for teaching, because of precisely this confusion.
