### ISSUE TITLE
Allow specifying the name of the root node in _repr_json_

### ISSUE THREAD

**Issue by dhirschfeld** [ipython/ipython#11015]
The example given in #6710 does seem to work for me!
```python
class Foo(object):
    def _repr_json_(self):
        return {"foo": 3, "bar": 4}, {'expanded': True}

foo = Foo()
foo
```
![image](https://user-images.githubusercontent.com/881019/36358976-1e3ab928-1562-11e8-929d-49733d3fb2c2.png)

However, rather than having the root node always labeled `root` I'd like to be able to specify the name. In particular I would like the root node to be named `self.__class__.__name__`

Ideally, you would be able to pass in the name of the root node as part of the metadata but it seems the only metadata it understands currently is `expanded`

**Comment by dhirschfeld** [comment]
Happy to put in a PR myself, but I'll need some pointers as to how to implement it as it's not immediately obvious to me :|

**Comment by ivanov** [comment]
Hi @dhirschfeld, thanks for your report. 

I've re-filed it as an issue on @nteract/nteract#2580 - it looks like that's what you're using in your screenshot. I'll go ahead and close this here, since the classic Jupyter notebook UI does not have a representation for just JSON mime types, your example will render as `<__main__.Foo at 0x107d48b70>` in the classic notebook (and in jupyterlab's notebook component).

**Comment by dhirschfeld** [comment]
@ivanov - it's not an interact issue. You get the same result in jupyterlab:

![image](https://user-images.githubusercontent.com/881019/36573320-ffdd2966-188b-11e8-8902-cdb2076a4b00.png)

It *might* be an issue in jupyterlab - https://github.com/jupyterlab/jupyterlab/tree/master/packages/json-extension

...but I was under the impression that the underlying machinery was in ipython itself and the jupyterlab extension just to the output from ipython and displayed it.
