### ISSUE TITLE
Install ipython error

### ISSUE THREAD

**Issue by BakaYang** [ipython/ipython#11096]
I use `pip install ipython`
errors appear 

![snip20180414_5](https://user-images.githubusercontent.com/23470990/38764153-19191134-3fdc-11e8-9e79-2ac00a3fcedb.png)

**Comment by takluyver** [comment]
That looks like pip is warning you about some packages that aren't installed and some that are installed but too old. If those warnings are right, then that's expected behaviour - though I haven't seen it before. Are you using a beta version of pip 10? If the warnings are wrong (i.e. you do have those packages installed, or you have newer versions than pip says), that's a bug in pip.
