### ISSUE TITLE
Resolution order for _repr_*_

### ISSUE THREAD

**Issue by ColCarroll** [ipython/ipython#11202]
Apologies if this is documented somewhere (or if the question belongs in a different project), but I can not find it:

In case an object has multiple `_repr_*_` defined, what happens?  In particular, can I try to set the representation in a notebook to an image, but fall back to text in case of a missing dependency?

I have tried the following example (in Jupyter Lab):

```
from IPython.display import display

class TryRepr(object):
    def _repr_latex_(self):
        return '$x^2$'
    
    def _repr_html_(self):
        return '<h2>Wow!</h2>'
    
    def __repr__(self):
        return 'boring'
    
    def _repr_png_(self):
        return display(plt.plot(np.arange(10), 10 - np.arange(10)))
    
    def _repr_pretty_(self, *args, **kwargs):
        return display(plt.plot(np.arange(10), np.arange(10)))
    
TryRepr()
```

The output is:

![image](https://user-images.githubusercontent.com/2295568/41812128-01ef126a-76eb-11e8-88af-1a97adc0f51d.png)

**Comment by takluyver** [comment]
Yes, it will try to compute the representation in all formats the object provides; you can `return None` from a repr method to indicate that that format is not available. Then the frontend picks which of the available formats it wants to display.

Your repr methods shouldn't call `display()`; that function displays an object as a side effect - it's be like having a `__repr__` method that calls `print()`.

It's probably best to avoid matplotlib for experimenting with this machinery, because we have some special cases to display matplotlib figures. If you want to play around with a png image, have a png file on disk and read from it in `_repr_png_`.

**Comment by ColCarroll** [comment]
Thanks much, that's very helpful.
