### ISSUE TITLE
completions of (multi)column kind do not respect color theme

### ISSUE THREAD

**Issue by ingvar-lynn** [ipython/ipython#11209]
![nopython](https://user-images.githubusercontent.com/23612903/42038096-c05ef192-7af2-11e8-9806-e5a4707ddac1.png)

```
user$ python3 -c "import IPython; print(IPython.sys_info())"
{'commit_hash': '7f10f7bb3',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/home/user/.local/lib/python3.5/site-packages/IPython',
 'ipython_version': '6.4.0',
 'os_name': 'posix',
 'platform': 'Linux-4.4.0-128-generic-x86_64-with-Ubuntu-16.04-xenial',
 'sys_executable': '/usr/bin/python3',
 'sys_platform': 'linux',
 'sys_version': '3.5.2 (default, Nov 23 2017, 16:37:01) \n[GCC 5.4.0 20160609]'}
```

workaround: use `--TerminalInteractiveShell.display_completions=readlinelike`

**Comment by gbishop** [comment]
I see this same issue with 7.1.1 and your workaround at least makes them readable. In my case they are orange on white if I don't workaround.

**Comment by gbishop** [comment]
A bit more background that I **hope** will help someone who knows more figure out what is going wrong.

If I hack interactiveshell.py and insert the following just above the call to `PromptSession` I can set the colors. When I look at the style rules the code is create rules like `pygments.menu.completions.completion` where the prompt_toolkit seems to be looking for rules like `completion-menu.completion`

```
        from prompt_toolkit.styles import Style as PTStyle       
        mystyle = PTStyle.from_dict({
            'completion-menu.completion': 'bg:#383830 #a59f85',
            'completion-menu.completion.current': 'bg:#a59f85 #383830'
        })
        self._style = merge_styles([self._style, mystyle])
 ```

**Comment by tomyun** [comment]
I also have a similar issue like @gbishop and it seems to be related with a recent change in `prompt-toolkit` that affects 256 color terminal scheme: prompt-toolkit/python-prompt-toolkit#766

That said, IPython users currently have no means to override `completion-menu.completion.*` styles because any Pygments tokens would be prefixed with `pygments.` string and that's not what the menu widgets would expect to work with. For example, `string_to_tokentype('Completion-Menu.Completion.*')` would be internally converted to `pygments.completion-menu.completion.*` during `merge_styles()`.

**Comment by tomyun** [comment]
FYI, try setting `c.TerminalInteractiveShell.true_color = True` in `ipython_config.py` if you have color issue especially when your terminal is something like `xterm-256color`. It worked for me.

**Comment by ingvar-lynn** [comment]
I believe the issue is resolved.
