### ISSUE TITLE
IPython.display.Javascript fails to execute when run from imported module

### ISSUE THREAD

**Issue by j6k4m8** [ipython/ipython#11339]
IPython 7.0.1 (latest as of this writing)

If I create a notebook with the contents:

```python
from IPython.display import Javascript
Javascript("console.log('foo')")
```

and execute the cell, then it logs "foo" to the browser console, no issue.

But if I create a file `foo.py` with the same contents and _import_ it:

```python
import foo
```

...the code does not execute.

If I replace the code in the standalone file with:

```python
from IPython.display import Javascript, display
display(Javascript("console.log('foo')"))
```

Then it _does_ print `foo` to the console.

---

I tried to do a search of existing issues — don't believe this has been reported before. Apologies if this is a dup.

**Comment by tonyfast** [comment]
This behavior is expected.  When the notebook cells are executed the last expression in the cell is sent to be displayed.  For example, the following will not write to the console because of the trailing semi colon:

```
from IPython.display import Javascript
Javascript("console.log('foo')");
```

When you import the code as module you must explicitly call `display` to show rich display objects.

In the notebook, the cell display behavior is configurable with [`ast_node_interactivity`](https://ipython.readthedocs.io/en/stable/config/options/terminal.html#configtrait-InteractiveShell.ast_node_interactivity).

**Comment by minrk** [comment]
@tonyfast thanks for the explanation!

**Comment by j6k4m8** [comment]
Thank you for explaining, @tonyfast! That definitely wasn't what I expected to happen, but certainly makes a lot of sense!
