### ISSUE TITLE
IPython 5 with prompt_toolkit 2

### ISSUE THREAD

**Issue by hroncok** [ipython/ipython#11341]
Hello,

in Fedora, we are discussing to update prompt_toolik to 2.x in order to update our (Python 3 only) ipython package to 7. However we also have python2-ipython (version 5) that would most likely get broken by the upgrade.

IPython 5.x explicitly says:

https://github.com/ipython/ipython/blob/2b56bcb6c12de1e333700a3a3cf7ea43d47b4fa4/setup.py#L199
    
Is this something that might eventually change?

Would IPython 5.x ever work with prompt_toolkit 2.x? I.e. would a PR be accepted in that branch?

Thanks for info.

See also https://python-prompt-toolkit.readthedocs.io/en/stable/pages/upgrading.html

cc @carlwgeorge

**Comment by Carreau** [comment]
A couple of questions first:

> update prompt_toolik to 2.x

Both on your python2- and python3- packages ? Do you have any other reasons to update to ptk 2.x for Python 2 ?  Aren't the site_packages separated ? (sorry if these are dumb questions, i'm not familiar with fedora.


> Would IPython **5.x** ever work with prompt_toolkit 2.x

We have to define exactly what you mean but as I understand it, 
most likely no – as least not as a default to prompt_toolkit 2.x . For a couple of reason. 
1) That would almost certainly be a change of API of the 5.x branch – which will deeply annoy other redistributors.
2) That would riple to jupyter_console, and other (non-jupyter) packages that are using ptk 1 and we know are compatible with IPython 5.x so forcing Ptk2, or saying that's it's a possibility would be extra work.
3) 5.x is LTS – because we care about Python 2 user – but mostly volunteers moving to Python 3 only. We  thus try to avoid heavy changes and wind it down so we can't expect much work from current core maintainers.

Now if you want to upstream patches to a 5.x-ptk2 branch that we release under a variant name on PyPI, or can make 5.x work conditionally with both ptk1 or 2 with no consumer API changes, I think that could work and we would accept the changes.
I guess if that works well we can give you maintainership of this branch as well.

There is another potential solution but IANAL. When we dropped python 2 support we actually had the question of whether LTS/5.x could be made proprietary/closed source/commercial with a vendor. My understanding is that yes it can, but not under the IPython name, which is too close to Python (we can't own the IPython trademark), but that may also be something that may be arranged with PSF.

Crosslink #11177 which is most of the work that made IPython 7 compatible with Ptk2

Hoping that answer some of your questions.

**Comment by hroncok** [comment]
We Fedora, we usually ship python3-foo and python2-foo packages from single source. We certainly have a way to split those, that we utilize when upstream updates to Python 3 only. For example we did that with IPython and quite recently with matplotlib as well. However prompt_toolkit 2 still supports Python 2, so I wanted to know if we can update both (2, 3) packages at the same time (keeping the single source thing). But we might need to keep python2-prompt-toolkit at 1.x and only update the python 3 part. Things are getting complicated, we try hard to kick all the unneeded python 2 packages out of the distro, but there are still a lot of dependent packages. Thanks for the answer, we'll try to figure out what's the best move here.

**Comment by carlwgeorge** [comment]
> But we might need to keep python2-prompt-toolkit at 1.x and only update the python 3 part.

That work for me.

**Comment by hroncok** [comment]
We did exactly that. Thanks @Carreau for the explanation.
