### ISSUE TITLE
In Win10,cann't use ctrl+enter to programmulti-line function block.

### ISSUE THREAD

**Issue by Ircon** [ipython/ipython#11413]
I use Ipython in win10's cmd and powershell.
when i program a function in ipython,just can program one line in funcition block.
It is disable to Using ctrl+enter to create second line in function block.
But,in spyder console,i can use ctrl+entrl to program multi-line code in function block.

My English is  poor,please Cheinese friend translate context for other.

在win10的命令台里面 想通过 ctrl+enter 在函数里面编写多行语句，但是 win10的命令台似乎不识别 ctrl+enter 这个快捷键。我按下 ctrl + enter 函数的编写就结束了。
但是在 spyder 的命令台里面 可以通过 ctrl+enter 实现函数的多行编写。

**Comment by Carreau** [comment]
Thanks for the report, If I understand correctly you are referring to the same as #11334 and #11346. 

This should have been fixed in `master` as of #11358 , and will be released in 7.1, I hope soon. 

Let me know if this is what you were talking about, and if so if we can close the issue.

In the meantime you should be able to use `ctrl-o` to force a newline.

**Comment by cfortiz** [comment]
Had the same issue.  Wrote in the files and I can finally use IPython on Windows 10 with Python 3.7 again.

**Comment by Ircon** [comment]
> Thanks for the report, If I understand correctly you are referring to the same as #11334 and #11346.
> 
> This should have been fixed in `master` as of #11358 , and will be released in 7.1, I hope soon.
> 
> Let me know if this is what you were talking about, and if so if we can close the issue.
> 
> In the meantime you should be able to use `ctrl-o` to force a newline.

Thanks! Using your advise i can program function which is multi-line.

**Comment by Carreau** [comment]
> Thanks! Using your advise i can program function which is multi-line.

Good, closing.
