### ISSUE TITLE
FileNotFoundError in getdist (JUPYTER)

### ISSUE THREAD

**Issue by esadri21** [ipython/ipython#11634]
I was using jupyter and getdist similar to past, but once I installed GIT-BASH and GNU parallel, the plotting part of getdist does not work (g.trangle_plot). Is there any advice?
**_FileNotFoundError: [WinError 2] The system cannot find the file specified_**
for test I am using tutorial of [getdist gallery](https://getdist.readthedocs.io/en/latest/plot_gallery.html).

`FileNotFoundError                         Traceback (most recent call last)`
`<ipython-input-4-4292ffe3ab0a> in <module>'
 '     1 #Triangle plot`
   ` 2 g = plots.getSubplotPlotter()`
`----> 3 g.triangle_plot([samples, samples2], filled=True)`

`C:\Python36-32\lib\site-packages\getdist\plots.py in triangle_plot(self, roots, params, legend_labels, plot_3d_with_param, filled, shaded, contour_args, contour_colors, contour_ls, contour_lws, line_args, label_order, legend_ncol, legend_loc, upper_roots, upper_kwargs, diag1d_kwargs, param_limits, **kwargs)`

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository if this is an actual bug or code proposal. For general help use [discourse](https://discourse.jupyter.org).  This will allow to keep the number of opened issue on the IPython repo under control and allow you to get faster response.
