### ISSUE TITLE
Jupyter notebook is not showing any files after home is opened.Its my first time opening it and the browser is not showing any files.

### ISSUE THREAD

**Issue by GunaDhannarapu** [ipython/ipython#11648]
![Screenshot (149)](https://user-images.githubusercontent.com/44300926/54412637-886b5200-4719-11e9-8b4b-2495f86b2b9b.png)

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository if this is an actual bug or code proposal. For general help use [discourse](https://discourse.jupyter.org).  This will allow to keep the number of opened issue on the IPython repo under control and allow you to get faster response.
