### ISSUE TITLE
after putting from ggplot import *, error coming as "ImportError: cannot import name Timestamp

### ISSUE THREAD

**Issue by hriday535** [ipython/ipython#11666]
Hi Team,

after putting from ggplot import *, error coming as 
"ImportError: cannot import name Timestamp.

please advise,

thanx

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository if this is an actual bug or code proposal. For general help use [discourse](https://discourse.jupyter.org).  This will allow to keep the number of opened issue on the IPython repo under control and allow you to get faster response.
