### ISSUE TITLE
Jupyter notebook error

### ISSUE THREAD

**Issue by waboke** [ipython/ipython#11695]
I installed Anaconda on ubuntu 18.04. When i open any file in jupyter notebook i see this error. "unknown error occurred while loading this notebook. This version can load notebook formats or earlier. See the server log for details" How do i solve the issue

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository if this is an actual bug or code proposal. For general help use [discourse](https://discourse.jupyter.org).  This will allow to keep the number of opened issue on the IPython repo under control and allow you to get faster response.
