### ISSUE TITLE
%%time cell magic suppresses cell output

### ISSUE THREAD

**Issue by angertdevsingh** [ipython/ipython#11707]
The following code does not display the value of `x` when run.
```
%%time
x = 10
x = x*2
x
```

Expected output includes the execution time and the value of `x`.

Using the `%time` line magic seems to work, even for multi-line code.

Additional info:
ipython_version: 7.5.0
os_name: nt
platform: Windows-10-10.0.17134-SP0
sys_platform': win32
sys_version: 3.7.3 [MSC v.1915 64 bit (AMD64)]

**Comment by Carreau** [comment]
I believe this is on purpose, `%timeit` may run the code several time; and does some modifications to the actual statement you run; so returning the value of the "Last" statement might not be what you expect.

**Comment by angertdevsingh** [comment]
> I believe this is on purpose, `%timeit` may run the code several time; and does some modifications to the actual statement you run; so returning the value of the "Last" statement might not be what you expect.

`%time` and `%%time` only run the code once though.

`In [1]: x = 5`

1. Using `%timeit`, `y` is not assigned a value

```
In [2]: %timeit y = x*2
# 32.6 ns ± 0.341 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
```
```
In [3]: y
# NameError: name 'y' is not defined
```

2. Using `%time` however, a value is assigned to `y`.

```
In [4]: %time y = x*2
# Wall time: 0 ns
```
```
In [5]: y
Out[5]: 10
```

3. Similarly, `%time` outputs a value in `Out[ ]` when the statement is not assigned to `y`.

```
In [6]: %time x*2
# Wall time: 0 ns
Out[6]: 10
```

4. However, `%%time`'s behaviour is inconsistent with `%time`.

- It does not output a value as in 3.:
```
In [7]: %%time
        z = x*2
        z
# Wall time: 0 ns
```
- But it does assign a value to `z` as in 2.:
```
In [8]: z
Out[8]: 10
```

Is there a reason why the behaviour of `%%time` is not consistent with `%time`?

**Comment by Pragnya02** [comment]
@Carreau  , @angertdevsingh  I am planning on working on this. This will be my very first-issue I will be contributing to.

To understand better , %%time should display the output for the last line in the cell, instead of suppressing it, like it currently does?

**Comment by angertdevsingh** [comment]
@Pragnya02 I think it should, yes.

**Comment by Carreau** [comment]
> `%time` and `%%time` only run the code once though.

Apologies, I recently worked on timit and got confused; 

> Is there a reason why the behaviour of `%%time` is not consistent with `%time`?

Yes, technically because Python does not treat single statement and multiple statement the same. 
If you compile a multi-statement it does not triggers the Python display-hook; whiel a single one does. (see [`compile()`](https://docs.python.org/3/library/functions.html#compile) ) doc. 

We have to [manually](https://github.com/ipython/ipython/blob/f14271fe2b0f9627f64848466de944befc7c29c9/IPython/core/interactiveshell.py#L3190-L3221) tweak the execution semantinc, which [`%%timeit` does](https://github.com/ipython/ipython/blob/master/IPython/core/magics/execution.py#L1124-L1137), and [`%%time` does not](https://github.com/ipython/ipython/blob/master/IPython/core/magics/execution.py#L1264-L1270). 


There is a lot of legacy code in these area, so it might be simple nowdays maybe just replace the last ast node by an interactive one ? 

It is not inherently hard, but might require quite a bit of poking around.

**Comment by Pragnya02** [comment]
@Carreau , I have tweaked the code a bit and opened a PR , please take a look whenever. 
https://github.com/ipython/ipython/pull/11716
