### ISSUE TITLE
prompt-toolkit can be upgraded

### ISSUE THREAD

**Issue by leolinf** [ipython/ipython#11703]
Third party dependencies can be upgraded prompt-toolkit>=2.0.0?

**Comment by Carreau** [comment]
We already allow prompt toolkit  between 2.0.0 and 2.1.0 I'm not quite sure what your request is.

**Comment by leolinf** [comment]
@Carreau  My ipython==5.8.0, I need support python2.x,  How can i do it?

**Comment by Carreau** [comment]
No, IPython 5.x does not support Prompt toolkit 2.

**Comment by amigrave** [comment]
Hi @Carreau , sorry to hijack this closed issue but I don't want to pollute the "Road to 8.0" issue and I found this one to be somehow appropriate.

Is there any plan to upgrade to prompt toolkit 3 in ipython 8.0 ?

I ask this because of issues encountered with the current threaded handling of keystroke in prompt toolkit 2:
https://github.com/prompt-toolkit/python-prompt-toolkit/issues/881
