### ISSUE TITLE
Jupyter Notebook is showing No pyspark kernel upon startupJupyter Notebook is showing No pyspark kernel upon startup

### ISSUE THREAD

**Issue by alankar91** [ipython/ipython#11729]
I am running pyspark scripts in jupyter notebook but the kernel is not starting. upon selecting pyspark from the dropdown the kernel loads and remains busy for some time and then shows "no kernel".

Can someone help me?

Note: upon running "$Jupyter kernelspec list" i can see pyspark kernel in the list.

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository if this is an actual bug or code proposal. For general help use [discourse](https://discourse.jupyter.org).  This will allow to keep the number of opened issue on the IPython repo under control and allow you to get faster response.
