### ISSUE TITLE
i am not able to run the cell in jupyter notebook it is going to other cell

### ISSUE THREAD

**Issue by sanketShetty** [ipython/ipython#11731]
![Screenshot (27)](https://user-images.githubusercontent.com/50712656/57871301-de15b680-77bd-11e9-9914-3d0a00464916.png)

**Comment by sanketShetty** [comment]
not able to run the cell of jupyter notebook for win platform. i dont know whter its connected to kernel or not but not able to run simple + - statements in the cell.

**Comment by sanketShetty** [comment]
![Screenshot (28)](https://user-images.githubusercontent.com/50712656/57972945-02a49680-7956-11e9-89dc-60ac35714870.png)

**Comment by sanketShetty** [comment]
can one help me what is 
 wrong

**Comment by Carreau** [comment]
Hi, this is the tracker for IPython/IPython.

Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository of the right org (in your case likely jupyter/notebook) if this is an actual bug or code proposal. For general help with Jupyter use [discourse](https://discourse.jupyter.org).  This will allow to keep the number of opened issue on the IPython repo under control and allow you to get faster response.

-- 

From what I know about  jupyter notebooks and windows, this may look like an issue with an antivirus or firewall that block websocket. 

Thanks,
