### ISSUE TITLE
WRONG_VERSION_NUMBER

### ISSUE THREAD

**Issue by NewDie** [ipython/ipython#11772]
I have trouble using the recon-ng tool.
please help me!
[!] URLError: <urlopen error [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:727)>
File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open.

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository if this is an actual bug or code proposal. For general help use [discourse](https://discourse.jupyter.org).  This will allow to keep the number of opened issue on the IPython repo under control and allow you to get faster response.
