### ISSUE TITLE
Jupyter disconnection from Kernel

### ISSUE THREAD

**Issue by Rubenbe75** [ipython/ipython#11822]
Hello, 

When I run Jupyter Notebook on my Windows 7 laptop, I loose the connection to the kernel within minutes. As I try to reconnect to the kernel using the top menu bar: Kernel --> Reconnect, I see the "Connecting to Kernel" sign pop for less than a second, but it fails to recconect. I will greatly appreciate any assistance.

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository if this is an actual bug or code proposal. For general help use [discourse](https://discourse.jupyter.org). This will allow to keep the number of opened issue on the IPython repo under control and allow you to get faster response.

Thanks,
