### ISSUE TITLE
Custom complete command leads to unwanted completions

### ISSUE THREAD

**Issue by lambdamusic** [ipython/ipython#11878]
When I use `ipython.set_hook('complete_command'` I always get extra completions, possibly inherited from a super class. But I can't figure out how to get rid of them.  

```
ip = get_ipython()

def load_ipython_custom_completers(ipython):
    def test_completers(self, event):
        return ["morning", "evening"]

    ipython.set_hook('complete_command', test_completers, str_key = 'good')

load_ipython_custom_completers(ip)
```

Then typing `good` leads to a few extra completions ie `and`, `if`, `in`, etc... 

![Screenshot 2019-09-05 at 13 52 49](https://user-images.githubusercontent.com/3493663/64343565-a6d54a80-cfe4-11e9-80d8-44d10c0135e4.png)

**Any idea where these are coming from?**

Environment:
```
{'commit_hash': '2e1cca5bc',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_version': '7.3.0',
 'os_name': 'posix',
 'platform': 'Darwin-18.7.0-x86_64-i386-64bit',
 'sys_platform': 'darwin',
 'sys_version': '3.7.4 (default, Jul  9 2019, 18:13:23) \n'
                '[Clang 10.0.1 (clang-1001.0.46.4)]'}
```

**Comment by augustogoulart** [comment]
@meeseeksdev tag tab-completion

**Comment by marcbernot** [comment]
This is due to Jedi autocompletion.
Use `ip.Completer.use_jedi = False` to deactivate it locally.

If you wan't this change to be global you can set `c.Completer.use_jedi = False` in the ipython_config.py file.

What is strange is that Completer.use_jedi is labeled "experimental" in the documentation and is set to True IF jedi is installed. Though, jedi is a requirement of the ipython conda package (both in the anaconda and conda-forge channels) so jedi IS installed and this experimental completion activated by default.

**Comment by lambdamusic** [comment]
That does work indeed! Thanks
