### ISSUE TITLE
Kernel died, restarting!

### ISSUE THREAD

**Issue by Subash33** [ipython/ipython#11880]
Hello, 
I have been trying to use Biopython module Bio.pairwise2 to align (to compare) a pair of text line by line. My python code in spyder crashes every time at different lines of texts being compared. Running it through terminal gives segmentation fault. I know this is a very generic way of asking a question and it may not be the spyder related issue. But since the code crashes at different lines in the text files everytime, I can not pinpoint the error. Any help would be appreciated. I am stuck!

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository if this is an actual bug or code proposal. For general help use [discourse](https://discourse.jupyter.org).  This will allow to keep the number of opened issue on the IPython repo under control and allow you to get faster response.
