### ISSUE TITLE
Weird memory/id management

### ISSUE THREAD

**Issue by royreznik** [ipython/ipython#11897]
hi, i found a really werid mangement
i tried to find an answer on stackoverflow and couldn't get one
https://stackoverflow.com/questions/58087537/why-does-ipython-manage-memory-differently-than-cpython-when-i-delete-a-list
why this is happend? isn't it using the cahcing system of Cpython for lists?

**Comment by Carreau** [comment]
I cannot tell you exactly why, but I can tell you what IPython does differently than CPython. 

The first things to be aware of is that IPython often caches previous results in case you forgot to assign them. So this is often a reason why id will not be the same: objects might not be freed. 

Second, IPython makes _a lot_ of potential modification to the AST, and does execute block statement one-by-one by walking the top-level of the AST (this allows for example to have top level await)

Thus when you thin you do:

```
code = """
l = [1,2,3]
l_id = id(l)
del l
g = [1,2,3]
id(g) == l_id # True"""
exec(code)
```

You are actually doing:
```
for c in code.splitlines():
     do_internal_stuff()
     kinda_exec(c)
     more_internal_stuff()
```

So it is quite likely that more objects are created "in between" your lines of code.

You can actually look at [how we execute code](https://github.com/ipython/ipython/blob/4a2240fb440c497e9e195d9ff43d96973b7ae33f/IPython/core/interactiveshell.py#L3137) ...it's quite complicated because of backward compat, but you might be able to get it down to  a couple dozen lines in a basic case to see what it is doing.

Hope that helps.

**Comment by royreznik** [comment]
thanks you
