### ISSUE TITLE
Get notebook contents from within the notebook

### ISSUE THREAD

**Issue by pavithrasv** [ipython/ipython#11924]
Is there a way to get all of the cell contents from within the notebook?

For example, i want to call an API from inside the notebook cell that would return JSON version of the current notebook.

**Comment by Carreau** [comment]
No; you can't and Jupyter make it explicitly hard. 

The reason is you can get many client attached to the same kernel at the same time. 

Some clients do set a hidden variable with the name of the notebook (I don't remember the name of this variable); and the you can try to do `open(...).read()` but that will be unreliable.
