### ISSUE TITLE
Jupyter notebook shows duplicate entries for path completion

### ISSUE THREAD

**Issue by jonilaserson** [ipython/ipython#12070]
When using jupyter notebook writing a filepath, the path completions appear twice in the list.

This does *not* happen with code completion.
This does *not* happen inside ipython.

![image](https://user-images.githubusercontent.com/5720840/71622025-d0416400-2bdb-11ea-81e5-261613dc31cc.png)

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself – you pointed out this does not appear within IPython itself –  and if still problematic and relevant should be opened on the right repository.  This will allow to keep the number of opened issue on the IPython repo under control and allow you to get faster response.
