### ISSUE TITLE
The autoreload module is not an IPython extension

### ISSUE THREAD

**Issue by kite8** [ipython/ipython#12115]
- When I input `%load_ext autoreload`
- the result is :
```
In [1]: %load_ext autoreload
The autoreload module is not an IPython extension.
```
os: win10
ipython version is 3.7.6, 
ipython version is 7.11.1

```
pip install ipython==7.0.1
pip install ipython==7.11.1
```
I try to do something, but not working.

I don't know how to deal with, please help me, thanks.

**Comment by Carreau** [comment]
do the following:

```
In [1]: import autoreload

In [2]: autoreload??
```

What do you get ?

My guess is you have something else called autoreload.

**Comment by kite8** [comment]
@Carreau Thanks, I found that another package has a file that called autoreload.py under root folder. I removed it, it's OK. Thanks again!!

**Comment by DrNickBailey** [comment]
For future visitors of this ticket, this did help me. 

I had been given code which contained this magical "%autoreload" of which I'd not heard of before. So in setting up the code I'd worked through and did a `pip install` of all the missing packaged including autoreload. So that is why I was then getting "The autoreload module is not an IPython extension" because it was trying to call that pip-installed package which is not this autoreaload.

So doing `pip uninstall autoreload` in my virtual environment I was using for the notebook solved this issue.
