### ISSUE TITLE
Rendering issue for "bin" operator in f-strings

### ISSUE THREAD

**Issue by ocdex** [ipython/ipython#12236]
Seems like there is a rendering issue with below text in Jupyter Notebook:
f'{14:#b}', f'{14:b}'
Current rendered code highlighting, assumes # as beginning of comment even though it is within quotes:
![image](https://user-images.githubusercontent.com/1331623/79267923-8d1fae00-7eb7-11ea-94fa-165d87106e48.png)
Hope this helps.

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository if this is an actual bug or code proposal. For general help use [discourse](https://discourse.jupyter.org).  This will allow to keep the number of opened issue on the IPython repo under control and allow you to get faster response.

I guess this issue is for jupyter/notebook , not here. Thanks.
