### ISSUE TITLE
Unhandled exception in event loop [ERROR] [WINDOWS] [BUG]

### ISSUE THREAD

**Issue by thewh1teagle** [ipython/ipython#12292]
## i'm getting often this error:

```
Unhandled exception in event loop:
  File "c:\users\qlorg\appdata\local\programs\python\python38-32\lib\asyncio\proactor_events.py", line 768, in _loop_self_reading
    f.result()  # may raise
  File "c:\users\qlorg\appdata\local\programs\python\python38-32\lib\asyncio\windows_events.py", line 808, in _poll
    value = callback(transferred, key, ov)
  File "c:\users\qlorg\appdata\local\programs\python\python38-32\lib\asyncio\windows_events.py", line 457, in finish_recv
    raise ConnectionResetError(*exc.args)

Exception [WinError 995] The I/O operation has been aborted because of either a thread exit or an application request
Press ENTER to continue...
```

**Comment by ExperimentalHypothesis** [comment]
me to, it pretty annoying

**Comment by jeevan449** [comment]
Unhandled exception in event loop:
  File "c:\users\jkoppura\appdata\local\programs\python\python38-32\lib\asyncio\proactor_events.py", line 768, in _loop_self_reading
    f.result()  # may raise
  File "c:\users\jkoppura\appdata\local\programs\python\python38-32\lib\asyncio\windows_events.py", line 808, in _poll
    value = callback(transferred, key, ov)
  File "c:\users\jkoppura\appdata\local\programs\python\python38-32\lib\asyncio\windows_events.py", line 457, in finish_recv
    raise ConnectionResetError(*exc.args)

Exception [WinError 995] The I/O operation has been aborted because of either a thread exit or an application request
Press ENTER to continue...

**Comment by Carreau** [comment]
try to update IPython and prompt_toolkit.

**Comment by thewh1teagle** [comment]
> 
> 
> try to update IPython and prompt_toolkit.

This is very old bug, I reinstalled python multiple times since

**Comment by theXYZT** [comment]
Getting this problem as well. I am on Windows 10 x64, Python 3.8.5 (Anaconda installation), IPython 7.18.1, prompt-toolkit 3.0.7.

**Comment by thewh1teagle** [comment]
Fixed it by downgrading ```prompt-toolkit``` to version ```2.0.10```.
```python
pip3 install prompt-toolkit==2.0.10
```

**Comment by theXYZT** [comment]
This is a premature closing of an issue that is still occurring and has nothing to do with `prompt_toolkit`. I have two conda environments on a Windows 10 system with `ipython=7.19.0` and `prompt_toolkit=3.0.8`, where one environment uses the anaconda channel and the other environment uses the conda-forge channel.

I do not get this error at all using the `conda-forge` versions of the packages.

Please open this issue. The issue is not related to `prompt-toolkit`'s version.

**Comment by thewh1teagle** [comment]
@theXYZT Are you sure? Because after I downgraded the prompt-toolkit the problem solved..

**Comment by theXYZT** [comment]
I definitely don't get the error with the latest version of prompt-toolkit if I use conda-forge.

It's possible that the issue you are having is entirely different than mine. So, I created #12722 for the specific phenomenon I am experiencing.
