### ISSUE TITLE
support for -Q switch

### ISSUE THREAD

**Issue by echu79** [ipython/ipython#1239]
It would be very useful if support for the -Q switch could be added to both the console and the qt console version of ipython such that -Qnew would turn on new division in ipython.

Thanks

**Comment by takluyver** [comment]
I don't think we can practically do this as an option on IPython, because it has to be set when the Python interpreter starts, and our command line argument handling happens inside Python.

I don't think we will do this in any Jupyter frontends, because it's something entirely specific to Python 2.

I'm therefore closing this; we can reopen it if people disagree.
