### ISSUE TITLE
jupyter notebook stuck whenever iam using any command to plot a graph

### ISSUE THREAD

**Issue by chirag-popli** [ipython/ipython#12398]
![p](https://user-images.githubusercontent.com/34339354/85234228-8ec2a080-b429-11ea-93bf-fd7b8fc9cf2a.png)
what to do please help me

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository if this is an actual bug or code proposal. For general help use [discourse](https://discourse.jupyter.org).  This will allow to keep the number of opened issue on the IPython repo under control and allow you to get faster response.
