### ISSUE TITLE
Jupiters NoteBook Application Requests are getting blocked in Azure Application Gateway

### ISSUE THREAD

**Issue by sujithre** [ipython/ipython#12444]
Hi,

SOme of ourRequests are getting blocked in Application Gateway Firewallit says the Error Message as below

Found User Agent assocaiated with scripting Generic HTTP CLient

Macthed Data : python-requests found with in REQUEST_HEADERS:USER-Agent :python-requests/2.22.0

Hiw can i remove this from my code in JupYTER or stop sending it?

Thanks,
Sujith.

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository if this is an actual bug or code proposal. For general help use [discourse](https://discourse.jupyter.org).  This will allow to keep the number of opened issue on the IPython repo under control and allow you to get faster response.
