### ISSUE TITLE
Jupyter Notebook is not showing the output of any code executed on the cell-Solution --ShutDown the previously running notebooks in the background

### ISSUE THREAD

**Issue by veena-02** [ipython/ipython#12470]
Although I am a beginner, I would like to give a solution to this issue which worked for me quite well . Some of my jupyter notebooks were running in the background which I didn't know as I simply closed the tabs on which they were running.
SOLUTION   :
1. Go to Home tab of jupyter notebook:
2. There are three tabs files, running , clusters.
3. Go to running tab.
4. It will show all the running notebooks.
5.Open each of them.
6. On opening it, on the toggle bar go to Kernel->ShutDown option, click on shutdown. 

Hence this way release all the memory and it would work fine

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository if this is an actual bug or code proposal. For general help use [discourse](https://discourse.jupyter.org).  This will allow to keep the number of opened issue on the IPython repo under control and allow you to get faster response.
