### ISSUE TITLE
traitlets version in 5.x branch needs to be pinned for Python 2 compatibility.

### ISSUE THREAD

**Issue by tirkarthi** [ipython/ipython#12498]
In the 5.x branch the traitlets version is pinned to be ">=4.2" . There is a pre-release in traitlets 5.0.0b1 which makes this Python 3 only : https://github.com/ipython/traitlets/releases/tag/5.0.0b1 . This is causing issues with tools like easy_install that seem to resolve >=4.2 as 5.0.0b1 including pre-releases meanwhile pip doesn't include the pre-release. This will eventually be an issue with pip too when traitlets make a major version release. This issue looks similar to pygments issue on 5.x branch : https://github.com/ipython/ipython/issues/12173 .

https://github.com/ipython/ipython/blob/818206a233464a223e796b6ddf7574c8876f572c/setup.py#L198

I will be glad to make a PR. Let me know if traitlets needs to be pinned ">=4.2,<5.0.".

Thanks

**Comment by Carreau** [comment]
I can try to pin but that should not be an issue, [traitlets 5.x declare itself as being 3.7+ only](https://github.com/ipython/traitlets/blob/61c7c8f5030d116de210f67d851ec9afa9f16170/setup.py#L68) so tools like pip (since pip 10+) should not consider traitlets 5.x at installation time. If they don't it's a bug in pip/easy_install.

Also IPython 5.x should be compatible 3.7, so on Python 3.7 not installing traitlets 5.x seem like a mistake if I pin.

I'm likely to end up making a fix anyway just in case; 

Did you actually got the issue when installing via pip ? or did you call `easy_install` directly ?

**Comment by Carreau** [comment]
See https://github.com/ipython/traitlets/pull/600 for clearer error message on the traitlets side.

If you make a PR against the 5.x branch to pin to <4.2 I'll be happy to merge it and release on the last friday of this month (same time at 7.18), but it would be nice to have upstream issue in pip/easy_install if they actually don't respect the requires_python.

**Comment by tirkarthi** [comment]
Thanks, I didn't know about `requires_python` and pip honoring it. In that case it's an issue with `easy_install` and this issue can be closed.

**Comment by Carreau** [comment]
> Thanks, I didn't know about `requires_python` and pip honoring it. In that case it's an issue with `easy_install` and this issue can be closed.

No problem, thanks for raising the issue; and yes `requires_python` is still not well known enough; so I'd appreciate if you can spread the word. I'm not sure if easy_install will be fixed as it's deprecated.

Personally I think that 1) requires_python should be post-release editable on warehouse, as if you forget it then it's too late and 2) you can't either a posteriori add a _maximum_ version of Python.

I'll keep open and see if I have the motivation might do a 5.x release that still pins traitlets.

**Comment by Carreau** [comment]
closed by be5c0545c36ec953db351e537792518f5ce8eaf0

**Comment by Carreau** [comment]
I've just pushed a commit, not sure I'll do a 5.x release, we'll see.
