### ISSUE TITLE
pip install -r for 7.18.1 failing with "python setup.py egg_info" failed with error

### ISSUE THREAD

**Issue by vladox** [ipython/ipython#12532]
Most probably has to do with the dependency on the trailets package that has a new version 5 published 2 days ago: 

[https://github.com/ipython/traitlets/releases/tag/5.0.0](https://github.com/ipython/traitlets/releases/tag/5.0.0)

pip.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/tmppv2y6wn3build/ipython/

**Comment by Carreau** [comment]
setuptools also released to setuptools 50 that was released this week-end
See `https://github.com/pypa/setuptools/issues/2372` for example.

Do you have more info about the error ? Like the os, or a log file ?

**Comment by diego-capyba** [comment]
Apparently it breaks because traitlets 5 is incompatible with Python 3.6. ipython should specify a maxium version for traitlets in its dependencies.

**Comment by Carreau** [comment]
> Apparently it breaks because traitlets 5 is incompatible with Python 3.6. ipython should specify a maximum version for traitlets in its dependencies.

No, IPython 7.x is 3.7+ only and traitlets [marks itself as 3.7+ only](https://github.com/ipython/traitlets/blob/2f22fb7069859411c12f9817bd622875f11444d9/setup.py). 

If whatever you are using is trying to install traitlets  Python 3.6 you are using a broken/too old version of pip or whatever else you use to install. Or you are using a Package proxy with bugs.

See https://github.com/ipython/ipython/issues/12498 and  https://github.com/ipython/ipython/pull/12538

```
$ python -V ; pip install 'traitlets>=5.0'
Python 3.6.11
ERROR: Could not find a version that satisfies the requirement traitlets>=5.0 (from versions: 0.0.1, 0.0.2, 4.0.0.dev0, 4.0.0, 4.1.0b1, 4.1.0, 4.2.0, 4.2.1, 4.2.2, 4.3.0b1, 4.3.0, 4.3.1, 4.3.2, 4.3.3.dev0, 4.3.3)
ERROR: No matching distribution found for traitlets>=5.0
```

**Comment by Carreau** [comment]
Feel free to keep commenting, I can reopen if there is an actual error or a details version report of what commands are ran/ which os version of pip, ...etc. 

But pinning traitlets is 1) the wrong things to do and 2) won't work as pip has a dependency resolver so even if I release IPython 7.18.2 it with a version patch it would happily downgrade it to 7.18.1.

**Comment by diego-capyba** [comment]
> > Apparently it breaks because traitlets 5 is incompatible with Python 3.6. ipython should specify a maximum version for traitlets in its dependencies.
> 
> No, IPython 7.x is 3.7+ only and traitlets [marks itself as 3.7+ only](https://github.com/ipython/traitlets/blob/2f22fb7069859411c12f9817bd622875f11444d9/setup.py).

I'm sorry, but IPython 7.x **is not** 3.7+. At least acoording to the docs, IPython 7.15 [still supports Python 3.6](https://ipython.readthedocs.io/en/stable/whatsnew/version7.html#nep29-last-version-to-support-python-3-6). However, in its dependecies it asks for ['traitlets>=4.2'](https://github.com/ipython/ipython/blob/7.15.0/setup.py#L192) and traitlets 5 [is incompatible with Python 3.6](https://traitlets.readthedocs.io/en/stable/changelog.html) . I don't see why this could be a problem with pip or somenthing else, I see instead a contradiction between _IPyhton_ and _traitlets_ compatibilities.

**Comment by Carreau** [comment]
> I'm sorry, but IPython 7.x **is not** 3.7+

**I** maintain IPython and **I** remove support for 3.6 and **I** updated the readme and the docs. So yes, I **know** that curent 7.x branch is 3.7 only. Use git blame to all the things you pointed to, and verify that **I wrote them**. So please, go get some coffee and make sure to be more awake before  contradicting me on that subject.

7.15 might be compatible 3.6 Yes, but that's not 7.x, that's 7.15 it was released in May, there have been 3 release since (4 if you count patch releases). If you are on 3.6 and `pip install ipython` and get IPython 7.15 or 7.16, and not 7.17, or not 7.18 (and not 7.18.1),  It's because several years ago I also wrote with the help of M Pacer and the PyPA folks the patches for Pip and Warehouse that understand the python-requires metadata. So I'm believe more qualified to understand how that works, what will work and won't work. Make an effort to understand what I am saying instead of insisting you are right and suggest a fix that is 1) incorrect and 2) does not work anyway.

Again:

- Say I accept a patch that adds `traitlets<5` in setup.py and I make a release:
   - Now we have IPython 7.19 published and 7.15  which still marks only `traitlets>4.2`.
   - That has not changed the dependencies of IPython 7.15 so the new release is moot. 
   - if you `pip install ipython` on 3.6 it will not see the new patch and anyway this new 7.19 is not compatible with 3.6 so what's the point ?


- Traitlets 5 being incompatible with Python 3.6 is irrelevant to compatibility with IPython. To be clear IPython 7.15 **works great with traitlets 5.0**. The thing you are installing with just do a bad job. It is a bug in the tool you use to install IPython. 

If it's pip then either it's an old version, or your vendor added some custom patch, or I don't know, but then you will need to show me the system/command where that fail and then we can find a _proper fix_.

An up-to date and Python 3.6 works fine, 
see below as pip **does understand that traitlets 5.0 should not be installed on Python 3.6 and install 4.3**

```
$ python -V
Python 3.6.11
$ pip install ipython --upgrade
Collecting ipython
  Using cached ipython-7.16.1-py3-none-any.whl (785 kB)
Requirement already satisfied: pygments in /.../envs/36/lib/python3.6/site-packages (from ipython) (2.6.1)
Collecting appnope; sys_platform == "darwin"
  Using cached appnope-0.1.0-py2.py3-none-any.whl (4.0 kB)
Requirement already satisfied: backcall in /.../envs/36/lib/python3.6/site-packages (from ipython) (0.2.0)
Requirement already satisfied: pexpect; sys_platform != "win32" in /.../envs/36/lib/python3.6/site-packages (from ipython) (4.8.0)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /.../envs/36/lib/python3.6/site-packages (from ipython) (3.0.7)
Collecting jedi>=0.10
  Using cached jedi-0.17.2-py2.py3-none-any.whl (1.4 MB)
Requirement already satisfied: setuptools>=18.5 in /.../envs/36/lib/python3.6/site-packages (from ipython) (49.6.0.post20200814)
Requirement already satisfied: traitlets>=4.2 in /.../envs/36/lib/python3.6/site-packages (from ipython) (4.3.3)
Requirement already satisfied: decorator in /.../envs/36/lib/python3.6/site-packages (from ipython) (4.4.2)
Collecting pickleshare
  Using cached pickleshare-0.7.5-py2.py3-none-any.whl (6.9 kB)
Requirement already satisfied: ptyprocess>=0.5 in /.../envs/36/lib/python3.6/site-packages (from pexpect; sys_platform != "win32"->ipython) (0.6.0)
Requirement already satisfied: wcwidth in /.../envs/36/lib/python3.6/site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython) (0.2.5)
Requirement already satisfied: parso<0.8.0,>=0.7.0 in /.../envs/36/lib/python3.6/site-packages (from jedi>=0.10->ipython) (0.7.1)
Requirement already satisfied: ipython-genutils in /.../envs/36/lib/python3.6/site-packages (from traitlets>=4.2->ipython) (0.2.0)
Requirement already satisfied: six in /.../envs/36/lib/python3.6/site-packages (from traitlets>=4.2->ipython) (1.15.0)
Installing collected packages: appnope, jedi, pickleshare, ipython
Successfully installed appnope-0.1.0 ipython-7.16.1 jedi-0.17.2 pickleshare-0.7.5
```

Now if you downgrade pip it does the wrong thing, but that requires a version of pip which is several years old:

```
$ pip install 'pip<9'
Collecting pip<9
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/9c/32/004ce0852e0a127f07f358b715015763273799bd798956fa930814b60f39/pip-8.1.2-py2.py3-none-any.whl (1.2MB)
    100% |████████████████████████████████| 1.2MB 379kB/s
Installing collected packages: pip
  Found existing installation: pip 9.0.3
    Uninstalling pip-9.0.3:
      Successfully uninstalled pip-9.0.3
Successfully installed pip-8.1.2

$ pip install ipython --upgrade
...
https://files.pythonhosted.org/packages/c5/b1/f0846b65d2377c934e9a9a000dcab0ae0beb85dace61020ee3daf1dad48e/traitlets-5.0.3-py3-none-any.whl (97kB)
    100% |████████████████████████████████| 102kB 8.4MB/s
Cache entry deserialization failed, entry ignored
Requirement already up-to-date: pickleshare in ...
```

Oh damned it get traitlets 5.0... yes, because the bug is present in `pip < 9.03`,

So again, unless you give me more informations :
 1) your understanding is wrong, and you look like an ass by telling people you understand better what they did than themselves.
 2) Your solution won't work
 3) I'm sure there is a reason why it fails on your system but you've shown me nothing to diagnose the root cause, so I can't help you with a actual fix.

**Comment by diego-capyba** [comment]
> **I** maintain IPython and **I** remove support for 3.6 and **I** updated the readme and the docs.

I missunderstood what you were referring to when you said "7.x". I thought you were referring to all 7._anything_ versions, which are the versions released between 7.0.0 and 7.18.1 (currently), and not the 7.x _branch_. I know that you maintain IPython and I'm sorry if it sounded like I was telling everybody that I understand better of IPython than you. This is obviously not true.

Indeed, installation via pip does not break anything with the versions we mentioned here because pip understands that traitlets 5 should not be installed with Python 3.6. However, the tool which my infrastructure provider uses does not take into account traitlets 5's python version requirement. The tool is _pip-reqs_ and I don't know for sure why it happens, but I will let my provider know about it.

Thank you for the detailed examples and explanation.

**Comment by Carreau** [comment]
Thanks, 

Apologies for the misunderstanding, written communication can be tough sometimes. 

I did not know about pip-reqs, and can't find a repository for it; so it's hard to dive into why it does what it does or know who to ping for that. 

My assumption would be that `pip-reqs` consume pypi "simple" API: https://pypi.org/simple/ipython/ but does not consider the data-requires field.

```
<a href="https://.../ipython-7.18.1.tar.gz#sha256=..." data-requires-python="&gt;=3.7">ipython-7.18.1.tar.gz</a>
```

Here with IPython, but same for any other package.

This should let it know not to try to install traitlets 5.0 on Python 3.6 before downloading it.

**Comment by vladox** [comment]
Sorry I started the thread but didn't have time to post back since, actually I'm also using the package @diego-capyba is also using. Apparently it's maintained by DIVIO AG a swiss company providing specialized dockerized Python hosting: [https://pypi.org/project/pip-reqs/](https://pypi.org/project/pip-reqs/)

I'll inform the developers about this issue to see if they can provide more information about why this utility is behaving differently to the standard pip.

@evildmp

**Comment by Carreau** [comment]
I've informed them, and pointed them to this issue, pip-reqs is part of on private code base, but from the interaction I had with them I don't think they can make the fix a priority unless this impact some divio customers.

Even if pip-reqs is not open-source it might be possible to dig in the source by unpacking the whl/sdist.
