### ISSUE TITLE
Get contents of notebook from python

### ISSUE THREAD

**Issue by vimota** [ipython/ipython#12554]
Is there an IPython API to get the contents of the current Jupyter Notebook?

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository if this is an actual bug or code proposal. For general help use [discourse](https://discourse.jupyter.org).  This will allow to keep the number of opened issue on the IPython repo under control and allow you to get faster response.

No there is None, ipykernel is not aware it is attached to a notebook.
