### ISSUE TITLE
IPython 6.5 broken with python 3.8. Missing required field "type_ignores"

### ISSUE THREAD

**Issue by antoine-gallix** [ipython/ipython#12558]
I am getting an error message when trying to import any module with the following versions combinations:

```
ipython : 6.5.0
python : 3.8.5
```
The error message is the same as in [this issue](https://github.com/ipython/ipython/issues/11590), that is:
```
In [1]: import os
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/.pyenv/versions/3.8.5/lib/python3.8/codeop.py in __call__(self, source, filename, symbol)
    139 
    140     def __call__(self, source, filename, symbol):
--> 141         codeob = compile(source, filename, symbol, self.flags, 1)
    142         for feature in _features:
    143             if codeob.co_flags & feature.compiler_flag:

TypeError: required field "type_ignores" missing from Module

```

**Comment by urianchang** [comment]
In the issue that you linked, the fix was added to iPython v7.3. Have you tried upgrading the package to v7.3+?

**Comment by antoine-gallix** [comment]
Thanks @urianchang  for your response. Nope, I use IPython 6 on purpose, because for non-us keyboard reasons, I want to configure my keybindings, which I can only do using [rlipython](https://github.com/ipython/rlipython), which in turn is broken for python 7. So until things move from one side or another I stick with IPython 6. I was hoping the fix for this problem would also be applied to IPython 6 branch. Otherwise I'll also have to limit myself to Python 3.7, which would be more difficult at work. Or come back to line editing with arrow keys. Would it be possible to also apply the fix to IPython 6 or support for this branch is already dropped?

**Comment by normanius** [comment]
Uninstalling IPython and reinstalling worked for me.

The exact reason how I ended up with this problem is not exactly clear to me. But I don't think it is related to IPython. 

In my case, it had something to do with the careless use of pip's `--force-reinstall` flag when I tried to a local Python package.

```bash
python -m pip install --force-reinstall <some/local/dist/*.tar.gz>
# I should have used this instead:
# python -m pip install --no-deps --force-reinstall <some/local/dist/*.tar.gz>
``` 

This broke some dependencies, and eventually also affected IPython. I was able to recover from this by reinstalling IPython (again with forcing the reinstallation of some packages). Be careful... :)

**Comment by normanius** [comment]
Uninstalling IPython and reinstalling worked for me.

The exact reason how I ended up with this problem is not exactly clear to me. But I don't think it is related to IPython. 

In my case, it had something to do with the careless use of pip's `--force-reinstall` flag when I tried to a local Python package.

```bash
python -m pip install --force-reinstall <some/local/dist/*.tar.gz>
# I should have used this instead:
# python -m pip install --no-deps --force-reinstall <some/local/dist/*.tar.gz>
``` 

This broke some dependencies, and eventually also affected IPython. I was able to recover from this by reinstalling IPython (again with forcing the reinstallation of some packages). Be careful... :)

**Comment by MrMino** [comment]
I think this one is old enough not to be relevant anymore.
