### ISSUE TITLE
Cannot add a picture in Jupyter Notebook

### ISSUE THREAD

**Issue by jaksylyk327** [ipython/ipython#12698]
Hi all,
I have an issue with adding a picture to the Jupyter notebook.

![Безымянный](https://user-images.githubusercontent.com/73703965/98408550-9c439480-2071-11eb-9629-6cde2ae10056.png)

**Comment by MrMino** [comment]
You'll need to provide more information for others to be able to debug your issue: which versions of Python, IPython, and Jupyter you are using?  What code have you used to add that picture, what behavior was expected? Etc.

Since this is 2 years old, I doubt this is still relevant to you, so I'm going to close this. If you still encounter this issue, don't hesitate to ping us here, we'll reopen it. But please include the aforementioned information.
