### ISSUE TITLE
MemoryError: Unable to allocate 348. KiB

### ISSUE THREAD

**Issue by Sanjeev273** [ipython/ipython#12710]
Hi  ipython team member,
 I am trying to plot the plot 1D data outcome from smilei simulation. I am getting the following error on particle tracking data: 

Return array(a, dtype, copy=False, order=order)
MemoryError: Unable to allocate 348. KiB for an array with shape (2, 22297) and data type float64

can some someone help me to remove this error?

**Comment by nmay231** [comment]
Hi @Sanjeev273

It looks like the smilei package is trying to allocate more memory than your computer has and fails. Now, 348 kb is not a lot but it probably means whatever command you ran allocated a couple of gigabytes successfully until one of the allocations failed. Honestly, I'm not too surprised since realistic particle data can be *extremely* large and easily approach terabytes or petabytes.

Regardless, I don't think this is an issue with IPython. Unfortunately, the only solution is to use a computer that has more memory (maybe you could look at a cloud option for hosting a Python Jupyter notebook). Or, depending on how the smilei package works, maybe they have an option to load a much smaller amount of the data than the full data set. I would read their documentation or maybe open an issue at their project.

I'm not an IPython maintainer, but I hope that helps :)
