### ISSUE TITLE
When running Ipython in Windows Command Prompt , there is an error which is "[TerminalIpythonAPP] WARNING | File ‘\r\n' doesn't exists."

### ISSUE THREAD

**Issue by dugunineswords** [ipython/ipython#12724]
When running ipython in Windows Command Prompt , there is an error which is "[TerminalIpythonAPP] WARNING | File ‘\r\n' doesn't exists."
How can I solve it?

D:\Package>ipython
[TerminalIpythonAPP] WARNING | File ‘\r\n' doesn't exists,

**Comment by Carreau** [comment]
can you run `python -We -m IPython` to see if it crashes IPython, that might to find where this errors comes from.

**Comment by faridcher** [comment]
I got the same error in Bash in Debian. The problem was with this alias definition:
```sh
alias ipython3='ipython3 --no-banner --no-confirm-exit'
```
I "unaliased" it and it worked fine.

**Comment by vds2212** [comment]
When running IPython on Windows I get:
```
[TerminalIPythonApp] WARNING | File not found: 'C:\\Windows\\system32\\config\\systemprofile\\env.py'
```

And my `env.py` is not read from my profile folder: `C:\Users\myusername\env.py`

**Comment by Carreau** [comment]
Please read the second comment of this thread.

**Comment by Carreau** [comment]
Please read the second comment of this thread.

**Comment by Carreau** [comment]
Not even a stack trace that tell you where/which file the warning is coming from ?

If that's the case you likely want to make a dev install of the the main IPython repo and modify the `shellapp.py` (I think), the error is likely comming from 

```
    def _exec_file(self, fname, shell_futures=False):
        try:
            full_filename = filefind(fname, [u'.', self.ipython_dir])
        except IOError:
            self.log.warning("File not found: %r"%fname) # replace this line by raise.
            return
```

And retry, so that we can start to find out why it's trying to execute `C:\\Windows\\system32\\config\\systemprofile\\env.py`

Check your configuration folder, you may have something like `TerminalInteractiveshell.exec_files=...` in it.
