### ISSUE TITLE
Github releases section misleading

### ISSUE THREAD

**Issue by miohtama** [ipython/ipython#12772]
Currently, ipython Github repository displays the latest release as 7.9.0

<img width="257" alt="image" src="https://user-images.githubusercontent.com/49922/104723384-7ac8ee00-572f-11eb-8574-8daf89e777a2.png">

This is because the authoritative release tracker is on [PyPi](https://pypi.org/project/ipython/#history). Maybe there were some Github releases in the past?

I do not know if it is possible to disable the Github Releases section, but I would try to hide it, as people looking for release history information like me get confused. 

As a suggestion maybe add a dummy release where it contains release notes that say "Please go to PyPi".

**Comment by afshin** [comment]
Hi @miohtama, thanks for posting. The releases you see in GItHub are part of the release process and are meant to be the easily discoverable/browsable/viewable source code for each release. Since this repository is the canonical home of the project, the releases do need a home here. Sorry for the confusion it caused you! I hope this clarifies why the source code repository of the project should also be the place where snapshots of the source of each release are recorded.

**Comment by Carreau** [comment]
> As a suggestion maybe add a dummy release where it contains release notes that say "Please go to PyPi".

Done.



> The releases you see in GItHub are part of the release process and are meant to be the easily discoverable/browsable/viewable source code for each release. Since this repository is the canonical home of the project, the releases do need a home here. Sorry for the confusion it caused you! I hope this clarifies why the source code repository of the project should also be the place where snapshots of the source of each release are recorded.

We dont' push releases on gh anymore the most recent is more than a year old.
