### ISSUE TITLE
How to set up a dev environment for creating tests?

### ISSUE THREAD

**Issue by illright** [ipython/ipython#12924]
I would like to contribute to the development of tests for IPython and I'm a little unsure on where to start.

Here are the steps that I took:
* Forked and cloned this repository
* (in the root of the repository) Ran `python -m venv .venv` to start a new virtual environment and activated it
* Ran `pip install -e '.[test]'` to install the dependencies for the testing environment
* Ran `iptest all`

After the last step I was presented with an error message:
```
Don't run iptest from the IPython source directory
```
which didn't really hint me towards where I should run these tests. I've also realized that I was probably running the `iptest` that came with my regular installation of IPython (which I verified to be the case with `whereis iptest`). I tried to remedy that by using the provided version of `iptest`:

```
(venv) $ python IPython/testing/iptest.py all
<...>
Traceback (most recent call last):
  File "/home/illright/work/ipython/.venv/lib/python3.9/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/illright/work/ipython/.venv/lib/python3.9/site-packages/nose/loader.py", line 407, in loadTestsFromName
    module = resolve_name(addr.module)
  File "/home/illright/work/ipython/.venv/lib/python3.9/site-packages/nose/util.py", line 312, in resolve_name
    module = __import__('.'.join(parts_copy))
ModuleNotFoundError: No module named 'all'
```

How exactly should I run the test suite?

---

On a related note, I'd also like to ask for some guidance on the test structure in this project. I wanted to focus on writing tests for magics, however, I've found a large file `IPython/core/tests/test_magic.py` which seems to be doing testing of magics (albeit a little sporadic in where things are located). Upon exploring the testing codebase I've found a file that led me to believe that `IPython/core/tests` tests are somewhat deprecated and are being transitioned into some other, more organized place. I must confess, I don't remember what that file was now, I couldn't seem to find it again. 

Questions:
1. I've seen mentions of `unittest`, `doctest`, `nose`, `py.test` in this repository. What exactly is being used for tests (or rather, what would be preferable to use)?
2. How should I structure the tests I'll be writing (which directory to put them in, what naming and grouping conventions to use, etc.)?

**Comment by MrMino** [comment]
> which didn't really hint me towards where I should run these tests.

Anywhere else, just not in the repo directory :).

> I've also realized that I was probably running the iptest that came with my regular installation of IPython (which I verified to be the case with whereis iptest)

That's because your shell didn't update its mappings of commands & their paths when the environment changed. Use `hash -r` in bash or `rehash` in zsh to fix it.

> I've seen mentions of unittest, doctest, nose, py.test in this repository. What exactly is being used for tests (or rather, what would be preferable to use)?

All of them as far as I can tell. This codebase is old & large (6f629fcc2 was 16 years ago), IIRC it predates most of these tools, that's why it's so disorderly. From my own experience - `iptest` works best, it's also the thing that CI runs.

> How should I structure the tests I'll be writing (which directory to put them in, what naming and grouping conventions to use, etc.)?

Depends on what you're testing. I'm always trying to put my tests as close to similar ones as possible, and make them consistent with the surrounding code (modulo darkening / reformatting them). Doing that means that activities such as #12840 are that bit easier to conduct.

If you have doubts - is always easier to alleviate them when we see some code, so don't hesitate to PR drafts. The worst thing that might happen is the person reviewing will suggest moving these tests to some other modules.

**Comment by Carreau** [comment]
Thanks for the question and @MrMino  for the answers. 

We are getting closer to Python 3.10 and and iptest will likely not work with it, so we are trying to move away from iptest and simply use `pytest`, though iptest tests way more things than pytest does.

Personally when running iptest I do `cd ~; iptest ; cd - ` which jumps to my home, run the test suite and then jump back but most of the time ``pytest --ff -x`` (failed first, abort after one failure) is relatively good for quick local tests.

For more details `nose` predates the more recent unittest; in theory we should get rid of every mention of it when possible, in favor of unittest; or simply using pytest when we can.

Most doctest test IPython via a subprocess; it should likely also be refactored into more explicit tests.

In general anything you believe is a improvement will likely be good, and as MrMino pointed out the code base is _really_ old; the actual dates are likely lost because pre-git, IPython was using svn, so some place of the codebase dates from when Python had no boolean types and use integers.

**Comment by MrMino** [comment]
Most of what was written here is no longer relevant. The simplest setup for testing IPython is now:

```
# Running from inside the repository root
pip install -e ".[test]"
pytest
```
