### ISSUE TITLE
Jupyter notebook doesn't run cells

### ISSUE THREAD

**Issue by fuad47** [ipython/ipython#13015]
I cant run any code cell, kernel is always busy, reinstalled jupyter, restared kernels but didn' t help.
There is also a star sign next to a cell

![Capture](https://user-images.githubusercontent.com/9503532/121312546-8a331880-c916-11eb-9b39-d70ca512867f.PNG)

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository if this is an actual bug or code proposal. For general help use [discourse](https://discourse.jupyter.org).  This will allow to keep the number of opened issue on the IPython repo under control and allow you to get faster response.
