### ISSUE TITLE
Documentation on profiles is unclear

### ISSUE THREAD

**Issue by MNRK01** [ipython/ipython#13068]
I wish to report a bug or at least an inconsistency in the documentation for how IPython finds a customized startup code in a profile_default directory that is in an alternate directory.

In the [IPython documentation on configuration and profiles](https://ipython.org/ipython-doc/3/config/intro.html#profiles), it is stated that one can have an alternate profile in the **current working directory**.

My question: what should the structure of the directory for this alternate profile be? Is it **./.ipython/profile_default/** or **./profile_default/**? I expected that it would be the former given the standard directory structure for IPython configuration. However, the following code indicates that it is the latter since IPython looks for a directory called profile_default under the current working directory:

https://github.com/ipython/ipython/blob/b3355a943823cfb24c1202bebbeb751e718ff172/IPython/core/profiledir.py#L202-L209

Maybe the documentation could be clearer on the directory structure for custom configurations, but in reality it would be nice to retain **./.ipython/profile_default/** as the directory structure for the alternate configuration since that shows the intent of that directory structure as having something related to IPython vs. some generic profile_default directory that a less familiar user might not know about.

The fix could be simple.

```python
ipy_userconfig_dir = os.path.join(os.getcwd(), u'.ipython') if os.path.split(os.getcwd())[-1] != u'.ipython' else os.getcwd()
```

Add the above code after:

https://github.com/ipython/ipython/blob/b3355a943823cfb24c1202bebbeb751e718ff172/IPython/core/profiledir.py#L202

and then replace the call to [os.getcwd()](https://github.com/ipython/ipython/blob/b3355a943823cfb24c1202bebbeb751e718ff172/IPython/core/profiledir.py#L203) with ipy_userconfig_dir.

```python
paths = [ipy_userconfig_dir, ipython_dir]
```

I believe that this recommendation is the path of least surprise. I'm hoping that this change will be accepted.

Thanks for reading and all the good IPython work!

**Comment by MrMino** [comment]
FWIW you're linking to the outdated docs. Here's the right link: [IPython documentation on configuration and profiles](https://ipython.readthedocs.io/en/stable/config/intro.html#profiles).

> My question: what should the structure of the directory for this alternate profile be?

I doubt that this is relevant to the user. IMO this should be handled by IPython, even if the profile is being created in CWD instead of a designated directory in user's home.

Having said that, the documentation is indeed unclear. I never used this feature, so I had to actually read the docs to get how it works. I've read it... and I'm confused.

- It's unclear why `ipython profile create <name>` is presented or what it does - `ipython --profile=<name>` works, with or without `profile create`, which makes it irrelevant.
- The "profile in current directory" train of thought is not elaborated on. It can be achieved via `--profile-dir`, but from the POV of someone reading the docs, it is unclear to say the least.
- `ipython profile create --profile-dir=<dir> <name>` also seems to work, but it creates a slightly different structure to that of `ipython --profule-dir <name>`.

Let's make this about clearing up the docs first. Autoloading of a profile is a good idea, but it should be an option, and implementing that option before clearing the docs will bring additional confusion, or make the new feature difficult to discover.

**Comment by Flodur871** [comment]
Can I work on this?

**Comment by MrMino** [comment]
@Flodur871 sure.

**Comment by Nrj27** [comment]
is this issue still open ??

**Comment by MNRK01** [comment]
I am the OP and have been using the Windows environment variable ```IPYTHONDIR``` successfully to point ipython to my profile directory. It works exactly as the documentation states, so I am closing the issue. Thank you.
