### ISSUE TITLE
crushed on remote server

### ISSUE THREAD

**Issue by Loglosss** [ipython/ipython#13083]
Hello.
On remote server ipython crushed when try autocomplete
![Screenshot 2021-08-05 at 14 24 44](https://user-images.githubusercontent.com/22504768/128342223-b9805578-8ed0-4ea1-be6b-d063841ea012.png)

**Comment by MrMino** [comment]
Hi. Please provide more information, otherwise it's difficult for us to help you resolve your issue.

What is your IPython version? What platform are you running on? Can you please post the output of your `pip freeze`?

I see you are using Python 3.6. Try downgrading jedi:

```
pip install jedi==0.17.2
```

... and let us know if it helps.

**Comment by MrMino** [comment]
Given that it looks like a duplicate of many other "jedi under Python 3.6" and the lack of feedback, I'm going to close this.

@Loglosss Don't hesitate to ping me if you'd like this to be reopened, but please provide some more information first.
