### ISSUE TITLE
Improve __getitem__ completions

### ISSUE THREAD

**Issue by mlucool** [ipython/ipython#13203]
Hi,

Similar to [this issue](https://mail.python.org/pipermail/ipython-dev/2016-July/016116.html), I find that auto-complete for `__getitem__` could be improved. For example, given:
```
class Foo:
    def _ipython_key_completions_(self):
        return ['foo', 'bar']

    def __getitem__(self, item):
        pass
    
foo = Foo()
```

I would expect to only show bar
```
foo['b
```

But instead it shows a lot of builtins, modules, etc. 
![image](https://user-images.githubusercontent.com/1813603/138155626-f04e6cb8-7d74-466d-878f-006b545b5619.png)

Might be good to make this change in time for 8.x, since it may be considered breaking.

**Comment by Carreau** [comment]
I'm not sure, I'll try to create a new env with the same version of Python/IPython  and investigate there.

**Comment by Carreau** [comment]
That seem to be a pyflyby side effect. I'll look into it. 

<img width="750" alt="Screen Shot 2021-10-21 at 09 46 29" src="https://user-images.githubusercontent.com/335567/138321725-c70dee9d-3b85-461b-9dd2-0a08301bd834.png">

**Comment by Carreau** [comment]
So that seem to be a fairly complex interaction between pyflyby and IPython. 

With https://github.com/deshaw/pyflyby/pull/166,and https://github.com/ipython/ipython/pull/13284, if I set  `--IPCompleter.merge_completions=False` I get the right behavior, but it likely makes the behavior a tad worse in some case, like complete worse complete for function keywords arguments. 


Pyflyby patches `global_matches` that is used to find all the locally defined objects, and inject a large number of things that could be autoimported. 

One of the difficult part is that most completer do not know wether they are in a string or not, and only get passed the last token, this could get refactored/improved and maybe moved into Jedi, it will be a non-trivial endeavor though, and a proper fix would be an extensive rework/cleanup of the completion mechanism. If we want to go that route, it might be worth including Jedi's author and see if the can benefit the whole ecosystem instead of just IPython, and it might be worth getting funding from several sources. 


I"ll still see if I can do better than just the above in a reasonable time.
