### ISSUE TITLE
[ipdb] Behavioral change when moving through function multiple-lines arguments

### ISSUE THREAD

**Issue by umairanis03** [ipython/ipython#13426]
Earlier stepping into a function with multi-line arguments through ipdb can be done by moving to the last line and then stepping into it.
Recently, we realized that this is not the case. When stepping into last line it comes back to the first line again, and then stepping into it would do the job.

Sharing a minimal repoducer:
```
In [1]: def foo(a, b, c):
   ...:     return a + b + c

In [2]: def check():
   ...:     ipdb.set_trace()
   ...:     foo(a=1,
   ...:         b=2,
   ...:         c=3)

In [3]: check()
> <ipython-input-2-e57c35c0b1ff>(3)check()
      2     ipdb.set_trace()
----> 3     foo(a=1,
      4         b=2,
ipdb> s
> <ipython-input-2-e57c35c0b1ff>(4)check()
      3     foo(a=1,
----> 4         b=2,
      5         c=3)
ipdb> s
> <ipython-input-2-e57c35c0b1ff>(5)check()
      4         b=2,
----> 5         c=3)
      6 
ipdb> s
> <ipython-input-2-e57c35c0b1ff>(3)check()
      2     ipdb.set_trace()
----> 3     foo(a=1,
      4         b=2,
ipdb> s
--Call--
> <ipython-input-1-8afe21a09ac8>(1)foo()
----> 1 def foo(a, b, c):
      2     return a + b + c
```

**Even simply doing **next** on the above does the same, it goes to the last line, and then comes back again at the first line.**

Also, we **have seen it moving to and fro more than once, which is pretty confusing**. I wasn't able to re-produce in in normal scenario, and can't share the internal reproducer for Proprietary reasons.

Can someone let-us know if there has been any change with regards to this?

**Comment by Carreau** [comment]
There should not be, though ipdb will by default skip some frames now, maybe the skipping frame logic is wrong.

Try
```
ipdb> skip_hidden false
```

**Comment by Carreau** [comment]
Actually that's exactly pdb's default behavior, and I can reproduce it at least until ipython 7.6
```
 $ python foo.py
> /Users/bussonniermatthias/dev/ipython/foo.py(10)check()
-> foo(
(Pdb) s
> /Users/bussonniermatthias/dev/ipython/foo.py(11)check()
-> a=1
(Pdb) s
> /Users/bussonniermatthias/dev/ipython/foo.py(12)check()
-> , b=2
(Pdb) s
> /Users/bussonniermatthias/dev/ipython/foo.py(13)check()
-> , c=3)
(Pdb) s
> /Users/bussonniermatthias/dev/ipython/foo.py(10)check()
-> foo(
(Pdb) s
--Call--
> /Users/bussonniermatthias/dev/ipython/foo.py(4)foo()
-> def foo(a, b, c):
(Pdb) s
> /Users/bussonniermatthias/dev/ipython/foo.py(5)foo()
-> return a + b + c
(Pdb) c
ipython[master ✗]  $ cat foo.py
import pdb


def foo(a, b, c):
    return a + b + c


def check():
    pdb.set_trace()
    foo(
            a=1
            , b=2
            , c=3)

check()
```

So I'm not sure this is due to IPython. I'm trying to get older python version but at least on 3.8 it's the same.

**Comment by Carreau** [comment]
Same on Python 3.7, so 'm really curious to get a configuration where you don't get the problem.

Or i'm misunderstanding what you ask.

**Comment by umairanis03** [comment]
I don't remember exactly till which version it used to step in directly into the function. I want to point out two of these issues:
1. Why for doing `next` it needs to come back to first line again.
2. We have seen it moving to-and-fro more than once, although I can't share a direct reproducer now. I'll try, if I can reproduce it in a minimal scenario.

Based on the above, it feels like a bug which needs to be fixed in the latest version.

**Comment by Carreau** [comment]
Sure, but as I said above this is the same behavior as Python's Pdb. 
If there is a difference then there is likely something to fix, but IPython tends to try not to venture far from Pdb, 
So if there need to be a fix it needs to be in CPython's Pdb not in IPython.

> Why for doing next it needs to come back to first line again.

Cause PDB is not thinking in line but likely using the bytecode, it : 
 - see the "line" `foo(a=1, b-2, c=3)` stop there. you do 'next'
 - step into each part of the subexpression:
    - compute 1, compute 2, compute 3, now compute foo(...).
  
 - the "foo again" with "--return--", is likely because this is that last expression of the function and so it happen to also be the line where `None`  is returned.

So the behavior looks reasonable to me, it just look like your mental model of it differs, which I understand is problematic, and why you think it's doing back and forth.


I think I can get the behavior you "want"
```
$ python foo.py
> /Users/bussonniermatthias/dev/ipython/foo.py(10)check()
-> foo
(Pdb) n
> /Users/bussonniermatthias/dev/ipython/foo.py(11)check()
-> foo(1,
(Pdb) n
> /Users/bussonniermatthias/dev/ipython/foo.py(12)check()
-> 2,
(Pdb) n
> /Users/bussonniermatthias/dev/ipython/foo.py(13)check()
-> 3)
(Pdb) n
--Return--
> /Users/bussonniermatthias/dev/ipython/foo.py(13)check()->None
-> 3)
(Pdb) n
--Return--
> /Users/bussonniermatthias/dev/ipython/foo.py(15)<module>()->None
-> check()

```

But that's by using Python 3.6, which is now EOL, and Python 3.7 has been released 4 years ago. (https://endoflife.date/python), and thus if you want to make a bug report you'll likely have to see that with https://bugs.python.org/.

I'm going to close as I don't think there is anything I can do here. So if bugs.python.org tell you the bugs it's not there and is here I'm happy to revisit.
