### ISSUE TITLE
IPython 8 changes terminal cursor

### ISSUE THREAD

**Issue by tebeka** [ipython/ipython#13472]
After starting IPython 8.0 and then returning to terminal, the cursor changes from block to I-Beam.

Before:
![ipy-cursor-before](https://user-images.githubusercontent.com/87697/149665338-139ee774-5d90-4ddc-88a8-3a7fcfee6f62.jpg)

After:
![ipy-cursor-after](https://user-images.githubusercontent.com/87697/149665346-78bc9858-96b5-4a79-b820-d4a6fb5d7e9f.jpg)

I need to call `reset` to get the cursor back to block.

Setup: XFCE terminal + zsh + starship

**Comment by Jmillan-Dev** [comment]
This behavior also occurs in VI edit mode where in Insert mode the cursor changes to I-Beam but in Normal mode the cursor changes back to Block. exiting in any of the two scenarios will keep the current cursor instead of getting back to the original cursor before opening IPython.

Setups:   
1. XTERM + zsh
2. terminology + zsh

**Comment by Carreau** [comment]
Hum... @jonathanslenders might have an idea ? I don't think we manipulate the cursor in IPython directly.

**Comment by ltrujello** [comment]
It looks like IPython does manipulate the cursor directly, it was done so in [this commit](https://github.com/ipython/ipython/pull/12588) to change the cursor for INSERT, VISUAL, etc. modes (in the case where the user has `vi` as their editing mode). That code is using ANSI escape codes to tell the running terminal what kind of cursor to use.

The original author didn't add code to restore the cursor. I made a pull request [here](https://github.com/ipython/ipython/pull/13501) to fix that.

For now, users can also run 
```bash
echo -en "\x1b[0 q"
``` 
after exiting IPython to get their cursor back.

**Comment by Carreau** [comment]
Ah, good point, I forgot about this.

**Comment by jonathanslenders** [comment]
I think at some point, this functionality should be merged into prompt_toolkit itself, so that all applications can benefit from it.
The issue about cursor shapes is actually open for 7 years now, but unfortunately I never had the time (well, it was never a priority, and didn't want to hurry into merging something without testing it works everywhere as expected). Let's hope I get around it in the coming weeks/month/year. :-)

See: https://github.com/prompt-toolkit/python-prompt-toolkit/issues/192

**Comment by ltrujello** [comment]
@jonathanslenders If you do decide to implement this feature, consider also changing the cursor back when the user does `ctrl+z`. Currently, IPython cannot change the cursor back when the user decides to SIGTSTP their process. That is because when it detects `ctrl+z`, it calls a function in `prompt-toolkit`, which then calls a function to send itself `SIGTSTP`. So `prompt-toolkit` could add code to also change the cursor back and forth in that scenario, which applications using it could benefit from.

**Comment by jonathanslenders** [comment]
@ltrujello : I'll keep that in mind, it should not  be an issue. Thanks!

**Comment by jonathanslenders** [comment]
@ltrujello: Can you check out this PR: https://github.com/prompt-toolkit/python-prompt-toolkit/pull/1558
That should do it. It seems to work fine for suspend too.

With these changes, you can remove the custom cursor shape handling in IPython, pass a ``cursor_shape_config=....`` option to the ``PromptSession`` in ``IPython/terminal/interactiveshell.py``. For the modal cursor, take ``prompt_toolkit.cursor_shapes.ModalCursorShapeConfig()``; otherwise take ``prompt_toolkit.cursor_shapes.CursorShape.BLOCK`` (if you want to always display a block, or ``None`` if cursor shapes should never be touched.)

**Comment by Carreau** [comment]
I'm not sure there is anything we can do for the suspend – I don't know enough about signal. 
In general the cursor thing is unsolvable in the general sens as we don't know the shape/state of the cursor when we start IPython, so we have no way of restoring it.

**Comment by jonathanslenders** [comment]
@Carreau : See my pull request. This should restore the cursorshape on suspend.

Restoring the cursorshape works by rendering ``\x1b[0 q``. This restores to whatever the terminal decides to be the default, not necessarily the cursor shape before IPython started, but almost always this is what we want.

Restoring cursorshapes during suspend works because prompt_toolkit configures the terminal in raw mode, which means that c-z doesn't send a ``SIGTSTP`` to the process group. We handle it as a key binding, restore the cursor shape, and then send ``SIGTSTP`` ourselves to our process group.

**Comment by jonathanslenders** [comment]
@ianbrody : Would you be willing to try my pull request and see whether that fixes your issue?

**Comment by ianbrody** [comment]
Now it changes back to a block cursor after suspend, but both after suspend and after quitting, the cursor is blinking.

**Comment by leycec** [comment]
Personally, I'd strongly prefer that IPython **do nothing whatsoever with the cursor.** Even when IPython changes and then restores the cursor as expected, it's still unexpected. No other terminal application I use forcefully modifies the cursor – not even Vim or `zsh`. I'd prefer that IPython behave like (almost) everything else in the POSIX ecosystem. Is there a trivial way for end users to disable this questionable functionality *without* manually modifying IPython source?

If I grok [this comment](https://github.com/ipython/ipython/issues/13472#issuecomment-1029491555) from @jonathanslenders above correctly, the only means of disabling IPython's cursor modification at the moment is to forcefully pass either `cursor_shape_config=None` *or* `cursor_shape_config=prompt_toolkit.cursor_shapes.CursorShape.BLOCK` to the `PromptSession` in `IPython/terminal/interactiveshell.py`. Is that right?

If so, that's great; at least I have some recourse. Still, changing the cursor without the user's explicit permission only disgruntles users. This should ideally be an opt-in option (i.e., disabled by default).

**Comment by MrMino** [comment]
> Personally, I'd strongly prefer that IPython **do nothing whatsoever with the cursor.** Even when IPython changes and then restores the cursor as expected, it's still unexpected. No other terminal application I use forcefully modifies the cursor – not even Vim or `zsh`. I'd prefer that IPython behave like (almost) everything else in the POSIX ecosystem. Is there a trivial way for end users to disable this questionable functionality *without* manually modifying IPython source?
> 
> If I grok [this comment](https://github.com/ipython/ipython/issues/13472#issuecomment-1029491555) from @jonathanslenders above correctly, the only means of disabling IPython's cursor modification at the moment is to forcefully pass either `cursor_shape_config=None` *or* `cursor_shape_config=prompt_toolkit.cursor_shapes.CursorShape.BLOCK` to the `PromptSession` in `IPython/terminal/interactiveshell.py`. Is that right?
> 
> If so, that's better than nothing; at least I have some recourse. Still, changing the cursor without the user's permission only disgruntles users. This should ideally be an opt-in option disabled by default.

If you'd like to make this configurable, I'd be happy to accept a PR that adds the option. Just make sure to take other PRs that are currently open into account, specifically those open by @jonathanslenders.

**Comment by roachsinai** [comment]
Any updates here?

Ipython 8 change my vim cursor when using [vim-repl](https://github.com/sillybun/vim-repl), even vim in NORMAL mode.

![image](https://github.com/ipython/ipython/assets/9500049/cd5f8d2c-4b66-431c-901d-5187f4a4b46f)

Thanks.

**Comment by Carreau** [comment]
According the discussion you either need to make the mentioned modification to IPython or send a PR to make it configurable. But as we have no way to know what the cursor shape is, we can't really restore it.

**Comment by roachsinai** [comment]
@Carreau thanks for quick reply.
