### ISSUE TITLE
bgcolor highlighting of ast nodes in traceback may be unreadable

### ISSUE THREAD

**Issue by alexandru-dinu** [ipython/ipython#13486]
The commit https://github.com/ipython/ipython/commit/3026c205487897f6874b2ff580fe0be33e36e033 introduced a change with a hard-coded `bg:ansiyellow` color.

Unfortunately, for some terminal color schemes, white-on-yellow may be unreadable, for example:
![image](https://user-images.githubusercontent.com/14110183/150824435-dd65d1ff-7b3c-4b29-acb1-2a774546f820.png)

Changing to `bg:ansired` looks better:
![image](https://user-images.githubusercontent.com/14110183/150831775-1e4e174d-145e-4760-abcd-07ef698ce153.png)

Is it possible to make this option configurable?

Thank you!

**Comment by Carreau** [comment]
Duplicate #13446

**Comment by amerlyq** [comment]
Linked issue is locked, and as I understood it mostly focused on choosing new default color/style instead of exposing Token.ExecutingNode for style_overrides config option.

Mentioning that "bg:ansiyellow" is being only used as fallback in `stack_data.style_with_executing_node(style, "bg:ansiyellow")` is wrong. Because its value is used as override:
```
    class NewStyle(style):
        for_executing_node = True

        styles = {
            **style.styles,
            **{
                k.ExecutingNode: v + " " + modifier
                for k, v in style.styles.items()
            }
        }
```
Therefore we really don't have a way to modify it from user config -- only through modifiying sources itself.

**Comment by kanbara** [comment]
I have spent several hours reading the source and issues trying to override these colours. It's pretty bad for dark backgrounds, and I finally have the normal colours sorted, but I would really really _really_ like the ability for the traceback to be customised-- especially the node colour. It's unusable on dark backgrounds and clashes with everything else.

**Comment by DanielO** [comment]
Being able to customise it would be ideal as currently is illegible on a dark terminal unless you have a muted yellow. Unfortunately I don't know how it's all plumbed together so I am not sure how to make the change.

For iTerm2 at least using anisred  for the BG colour is quite legible for both light and dark (when editing the source).

If I change the line to:
                style = stack_data.style_with_executing_node(style, style.styles[pygments.token.Generic.Error])

(And add 'import pigments.token' up the top) then it uses the existing error style rather than hard coding it - perhaps that is a suitable solution.

**Comment by 0xquad** [comment]
Has there been plans to fix this issue?

First use after many years and experienced the problem immediately. Errors are unreadable, so the tool basically becomes impossible to use normally. I have to run things in a simple python console instead to see anything.

FYI I'm on Windows with Putty (Kitty fork). Tweaking the terminal colors is a huge hack at the very least and not a solution: only IPython outputs unreadable text (white on bright yellow) from all the things I've been using in the past years. (I'm actually surprised that it wasn't fixed before; it really should be a blocking issue in my book. Am I the only one having this issue? Otherwise is there any way I can disable this whole colored output in IPython (*not* the terminal) in order to restore usability?)

Also the original issue was locked ("off-topic" ?) so no one can comment there. Perhaps work is being done elsewhere?

Thanks for all the efforts put in IPython nonetheless, it's excellent!

**Comment by Carreau** [comment]
See #13756 as a workaround. But really most of the open issue that are not fixed is really because someone need to dive into them and do the work.
