### ISSUE TITLE
Sign up for GitHub Sponsors! 💰

### ISSUE THREAD

**Issue by zachriggle** [ipython/ipython#13571]
Please consider signing up for GitHub Sponsors so that others can contribute to the development of IPython!

http://github.com/sponsors

**Comment by Carreau** [comment]
You can sponsor IPython via https://github.com/sponsors/numfocus 
The .github is set-up (https://github.com/ipython/.github/blob/master/FUNDING.yml), so I'm not sure why it does nto show up.

**Comment by MrMino** [comment]
I was wondering why we don't have that button, but never got around to investigating it.

@Carreau is [the feature](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository#displaying-a-sponsor-button-in-your-repository) enabled in the repo settings?

I had a suspicion that it's because of the `'` being used instead of `"` for the links containing `:` (YAML can be touchy when it comes to colons), but PyYAML parses this file without any issue.

**Comment by Carreau** [comment]
I did that and also submitted the IPython or gprofile for review, the button is now present. Closing.
