### ISSUE TITLE
END key no longer reliably working as expected

### ISSUE THREAD

**Issue by digismack** [ipython/ipython#13623]
Having recently updated to iPython 8.2.0 I noticed that my end key is no longer consistently working as expected. Occasionally it will become unresponsive. I'm guessing this is related to the recent addition of [Adding and "End" key binding for applying an auto suggestion](https://github.com/ipython/ipython/pull/13566)

This mainly occurs when I'm in iPython working with SQLAlchemy code. It "feels" like the end key is trying to autocomplete instead of move to the end of the line, even though there is nothing to autocomplete.

If I revert to 8.1.1 I no longer experience this issue.

`Python 3.8.10`

```
ipython                  8.2.0
prompt-toolkit           3.0.29
```

**Comment by MrMino** [comment]
What's the output of `%config TerminalInteractiveShell.editing_mode` in the IPython session where you experience this?

**Comment by digismack** [comment]
```Out[1]: 'emacs'```

**Comment by MrMino** [comment]
This happens when the current input line equals the autosuggestion generated for it. E.g.:


![image](https://user-images.githubusercontent.com/6691643/161606801-895e2703-c69d-4d39-bb2e-52d294669aa0.png)

Hitting <kbd>End</kbd> fills in the autosuggest:

![image](https://user-images.githubusercontent.com/6691643/161606895-5a0ba894-512e-4cd7-a831-98873e2a3a16.png)

Now, if you move cursor back, the <kbd>End</kbd> key doesn't move it to the end of the line anymore:

![image](https://user-images.githubusercontent.com/6691643/161607059-fae7df2b-fe7f-4969-a0bf-3931f8bf39c1.png)

Looks like an issue with wrong `@kb.add` `filter=` in [#13566 L278](https://github.com/ipython/ipython/pull/13566/files#diff-3b2709b0687ef808e68fb6e467415ce313553aa29ba688d523ddb6ba768a7784R278).

**Comment by MrMino** [comment]
Also, this means that <kbd>End</kbd> no longer works properly in vi mode (when emacs bindings are on).

**Comment by MrMino** [comment]
Turned out to be a bug in the code that was checking whether the suggestion is empty or not. See PR.

**Comment by digismack** [comment]
@MrMino Any chance of getting a release soon to include this fix? Our systems are ephemeral and having to reinstall from the git main branch regularly is really annoying. :)

**Comment by MrMino** [comment]
@digismack That is a question for @Carreau mostly. IIRC releases are done ~once a month.
