### ISSUE TITLE
Missing ansi colors on windows

### ISSUE THREAD

**Issue by thisismygitrepo** [ipython/ipython#13805]
ANSI color format is completely missing on Windows machine:

```
print('\x1b[1m\x1b[38;5;0m\x1b[48;5;15mblack on white, bold\x1b[0m\x1b[0m\x1b[0m')
```

It works as expected on Linux but not on my Windows 11 IPython 8.6.0 (python 3.9.7)

**Comment by krassowski** [comment]
Are you using the default Windows console or Powershell? The former does not support the ANSI colours by default and only supports them since Windows 10 if a) explicitly enabled, or b) run from `cmd` (which explicitly enables them).

IPython could possibly enable this using `SetConsoleMode` call.

Some references:
- how to manually enable ANSI colors globally on Windows (beware issues with git): https://superuser.com/a/1300251/
- how to enable it programatically  https://stackoverflow.com/a/36760881/

**Comment by thisismygitrepo** [comment]
I'm using Windows Terminal as host window and Powershell as shell. I tried the programmatic enabling but to no avail.

<img width="653" alt="image" src="https://user-images.githubusercontent.com/46288868/202872461-78631200-6088-42fc-b438-d049961851d3.png">

**Comment by krassowski** [comment]
Thanks for adding more details! Does it work from `cmd.exe`/old Windows Console?

**Comment by krassowski** [comment]
Another thing you could check: does it work with plain Python? The Python issue tracker suggests that it should work with Python 3.7+ (https://bugs.python.org/issue29059).

**Comment by thisismygitrepo** [comment]
* cmd.exe
    * naked `python 3.11`: it works, but only after `SetConsoleMode `
    * `python 3.11` + `ipython 8.6`: it works, even **without**  `SetConsoleMode `

* pwsh.exe
    * naked `python 3.11`: it works, even without `SetConsoleMode `
    * `python 3.11` + `ipython 8.6`: it works, even **without**  `SetConsoleMode `
 
Everything checks as you described, except for my virtual enviroment where it doesn't work (as shown in the image of previous reply) no matter which console or shell, with or without  `SetConsoleMode `. Naked python for that enviroment works though. I created a clean virtual enviroment with just ìpython` and it works. My best guess is that some third-party library is the culprit.
