### ISSUE TITLE
ipython==8.8.0 has weird tab completion bug

### ISSUE THREAD

**Issue by suewonjp** [ipython/ipython#13935]
self.my_attr.my_method(self.f<tab>
Becomes:

    self.my_attr.my_method(self.my_attr.my_method(self.foo
It looks like it would grab and prepend the front part of the line.

## Workaround
Rolling back to 8.7.0 solves it.

## Repro
Unfortunately, I failed to reproduce it with simple setup with a simple class and method and attribute.

But I easily reproduce this bug at my work projects (which are huge... and have so much complicated dependencies). I think this bug wouldn't manifest itself unless the code base is complicated enough.

I've confirmed 8.7.0 doesn't have this issue.

**Comment by krassowski** [comment]
@suewonjp thank you for opening this issue. A reproducer would really help. Based on your example I tried:

```python
class A:
    def my_method(self):
        pass
class B:
    my_attr = A()
    field = 1
    def test(self):
        self.my_attr.my_method(self.f<tab>
```

but it worked correctly, completing `field`.

Also, would you mind checking if changing [`IPCompleter.evaluation`](https://ipython.readthedocs.io/en/stable/api/generated/IPython.core.completer.html#IPython.core.completer.Completer.evaluation) has any influence on the behaviour you see?

**Comment by suewonjp** [comment]
Thank you for your reply.
I think I'll identify the problem commit by git binary search or something when I have time for that at work.

> Also, would you mind checking if changing IPCompleter.evaluation has any influence on the behaviour you see?

I'll try

**Comment by suewonjp** [comment]
The issue was gone by setting True for `IPCompleter.use_jedi` option. I've been using `IPCompleter.use_jedi = False` for a long while due to the issue at #11653

And with debug setting enabled, I've got the following.

![image](https://user-images.githubusercontent.com/5332080/218301932-d848fd88-e9db-4e52-b0d2-c2d9128b42cb.png)

`assert str.st<tab>` becomes `assert assert str.st*` and `assert assert str.st<tab>` becomes `assert assert assert.st*` and so on... just it tries grabbing things before it on the line endlessly.

Honestly, I doubt this may help you fix the issue, but it's what I've got so far. I hope I could share more helpful clues later...

**Comment by suewonjp** [comment]
@krassowski 
I've come up with a very minimum setup which can reproduce the issue (I think)

- CD to ipython repository
- Update it to the latest main branch
- Create a virtualenv
- Install ipython itself with `pip install -e .`
- Create a fresh new profile (just in case)
    - `ipython profile create debug`
- Start a session
    - `ipython --profile=debug`
- Disable use_jedi
    - `%config IPCompleter.use_jedi = False`
- Try a simple tab autocompletion
    - `assert str.st<tab>`

I could reproduce the issue with the procedure on WSL, and Mac. So the issue is not dependent on platforms at all.
I hope this would help.

**Comment by krassowski** [comment]
Ok, so previously `IPCompleter.python_matches` (`attr_matches` to be precise) was returning: `["str.startswith", "str.strip"]` but now it is `["assert str.startswith", "assert str.strip"]`.

Previously `expr = "str"`, now `expr = "assert str"`. Larger expr is good for evaluation, but we need to trim it so that the prefix reconciliation algorithm does not go crazy (or change the reconciliation algorithm, but this may not be possible).

PR on the way.

**Comment by pdemarti** [comment]
(Comment, no action needed): Same issue here with `ipython=8.10.0`. I too had a `c.Completer.use_jedi = False` in my `.ipython/profile_default/ipython_config.py`. Since I didn't have too many other customizations, I simply moved `~/.ipython` out of the way, and let `ipython` create a fresh new vanilla one.

```shell
mv ~/.ipython ~/.ipython-old
```

Now tab-completion works as expected. And it works with tab-completion for e.g. `pandas` dataframes with large number of columns (it doesn't hand as it used to, which had prompted me to `jedi=False`).
