### ISSUE TITLE
Behavior when typing a few characters from an historical command and pressing up has changed.

### ISSUE THREAD

**Issue by moorepants** [ipython/ipython#13979]
I typically have followed this procedure to retype a command in the history:

1. Type first few letters of the historical command.
2. Press the up key until that command is found in the cycle of the historical commands.
3. Press enter.

Now it seems there is an extra step:

1. Type first few letters of the historical command.
2. Press the up key until that command is found in the cycle of the historical commands.
3. Press the right arrow key.
4. Press enter.

This was tested on Python 3.8.16 and IPython 8.11.0.

Is it possible to get the old behavior back? Is this a regression? I've also noticed several other changes to the IPython tab completion and history commands which are open in other issues, but I'm not sure that this one has been opened yet.

**Comment by krassowski** [comment]
The new behaviour is due to a switch to a new navigable auto-suggestions provider whereas previous IPython versions used one without navigation support. You can configure [`TerminalInteractiveShell.autosuggestions_provider`](https://ipython.readthedocs.io/en/stable/config/options/terminal.html#configtrait-TerminalInteractiveShell.autosuggestions_provider) traitlet to modify this behaviour, e.g. to restore the behaviour from IPython <8.9:

```python
TerminalInteractiveShell.autosuggestions_provider = 'AutoSuggestFromHistory'
```

or to disable autosugesstions altogether (<8.0 behaviour):

```python
TerminalInteractiveShell.autosuggestions_provider = None
```

Alternatively, you could disable specific key-bindings using new [shortcut configuration](https://ipython.readthedocs.io/en/stable/whatsnew/version8.html#terminal-shortcuts-customization) capability added in IPython 8.11.

Of note the alternative steps are:

1. Type first few letters of the historical command.
2. Press the escape key to dismiss autosugestions.
3. Press the up key until that command is found in the cycle of the historical commands.
4. Press enter.

I will work on improving the user-facing documentation to address this.

**Comment by krassowski** [comment]
In the meantime, would you be potentially interested in providing a quick feedback (:+1:  or :-1: ) on https://github.com/ipython/ipython/issues/13987?

**Comment by oscarbenjamin** [comment]
I have opened gh-13993 proposing to restore the previous behaviour for navigation with search.

**Comment by oscarbenjamin** [comment]
This is possibly fixed in the latest release. @moorepants I suggest installing ipython 8.14.0 to test it out.

**Comment by krassowski** [comment]
Does it mean we can close this issue?
