### ISSUE TITLE
Proposal: discard autosuggestion with `delete` key

### ISSUE THREAD

**Issue by krassowski** [ipython/ipython#13987]
Auto-suggestions can be discarded using <kbd>Esc</kbd> key (which works slow as there is a time delay allowing to press a combination of <kbd>Esc</kbd> with another key):

![existing-workaround](https://user-images.githubusercontent.com/5832902/227661482-39d72887-2620-44c2-83ab-74ac12e2b54a.gif)

When an auto-suggestion is partially accepted e.g. using <kbd>Ctrl</kbd> + <kbd>Right</kbd> it would appear intuitive to use <kbd>delete</kbd> key to clear the remaining part of the suggestion, but currently this does not work:

![current-behaviour](https://user-images.githubusercontent.com/5832902/227661502-d722a613-1368-42a5-9715-690ae9df8e6c.gif)

the proposed behaviour is depicted on the GIF below:

![proposed-behaviour](https://user-images.githubusercontent.com/5832902/227661534-38083923-57a1-4d7d-965d-598f8f0656c1.gif)

IPython 3.11 users can opt-in for the proposed behaviour by defining a custom shortcut:

```python
custom_shortcuts = [
    {
        "command": "IPython:auto_suggest.discard",
        "new_keys": ["delete"],
        "new_filter": "navigable_suggestions & has_suggestion & default_buffer_focused"
    }
]
%config TerminalInteractiveShell.shortcuts = custom_shortcuts
```

but there may be a value in making this a default behaviour (opt-out rather than opt-in).

Can I ask anyone interested to indicate if they would be happy with an addition of such a shortcut by default (:+1: or :-1: )?

**Comment by aanastasiou** [comment]
@krassowski With all due respect, I have downvoted this proposal for the following reasons:

1. I have never discarded an auto-suggestion explicitly with the press of a button. If I do not like the auto-suggestion then I simply continue typing.
2. Please [do not make me click extra buttons](https://en.wikipedia.org/wiki/Don%27t_Make_Me_Think). Equally, please do not make me configure things :)

But, I would also like to propose the following alternative: If I have written a long(ish) line and I realise that this is not what I should really be doing, then I would appreciate having a convenient shortcut to completely erase the line.

Currently, I can do this either by:
* Hitting Enter knowing that I will get an error (but then littering my history, which is not really productive)
* Pressing Ctrl-C (which is two buttons)
* Pressing Shift-Home, Del to mark and delete the whole line (which is three buttons and also might not work on all kinds of terminals).

Hence why I think that it seems more useful to have this Del shortcut erase the whole line.

It is one keystroke AND, it is also compatible with what you would expect a Del button to do (rather than cancel an intention, as text has not been written when you press Del to cancel an auto-suggestion).

Hope this helps.

**Comment by oscarbenjamin** [comment]
What is the advantage of deleting the completion? Does it change the behaviour of any subsequent operation?

**Comment by cottrell** [comment]
Can you clarify what this ia a proposal for? Is this for some detail of the NEW opt-in-only flavour? Or is this as an alternative to replicating the OLD behaviour?

**Comment by krassowski** [comment]
@aanastasiou based on your comment I think that I  may not have explained the proposal clearly enough:

> 1. I have never discarded an auto-suggestion explicitly with the press of a button. If I do not like the auto-suggestion then I simply continue typing.

The proposed behaviour does not change this.

> 2. Please [do not make me click extra buttons](https://en.wikipedia.org/wiki/Don%27t_Make_Me_Think). Equally, please do not make me configure things :)

The proposed behaviour does not change this. You will not be required to press any buttons to discard the suggestion. This is a proposal for an additive change.

> Hence why I think that it seems more useful to have this Del shortcut erase the whole line.

I would oppose it on the ground that adding a new keybinding with destructive action (deleting a line type by the user as opposing to discarding a suggestion that was not confirmed and can be re-triggered) is very likely to lead to loss of user data.

**Comment by krassowski** [comment]
@oscarbenjamin 

> What is the advantage of deleting the completion? Does it change the behaviour of any subsequent operation?

There are two tiny advantages/changes to subsequent operations:
- the visual aspect (you no longer see the suggestion you are not interested in)
- when using a navigable suggestions provider discarding a suggestion enables user to press <kbd>Up</kbd>/<kbd>Down</kbd>
 to move to previous/next entry in buffer history (rather than suggestions history)

The remaining behaviour (e.g. executing lines, adding a new line) is always the same, regardless of whether a suggestion is shown or not.

**Comment by krassowski** [comment]
@cottrell 

> Can you clarify what this ia a proposal for? Is this for some detail of the NEW opt-in-only flavour? Or is this as an alternative to replicating the OLD behaviour?

It is not clear what you mean by NEW/OLD. This proposal is for the <kbd>Del</kbd> to discard auto-suggestion as [on third GIF](https://user-images.githubusercontent.com/5832902/227661534-38083923-57a1-4d7d-965d-598f8f0656c1.gif) in top-level comment. This proposal does not change any other behaviour as far as I am aware of. If it does then that would be an important point in the discussion. You can emulate the proposed behaviour by copy-pasting `custom_shortcuts` snippet from [top-level comment](https://github.com/ipython/ipython/issues/13987#issue-1640192534) in IPython 3.11+.

**Comment by oscarbenjamin** [comment]
> * when using a navigable suggestions provider discarding a suggestion enables user to press Up/Down
>   to move to previous/next entry in buffer history (rather than suggestions history)

Okay, I see this now. So pressing delete restores previous up/down completion behaviour including up being most recent match and being able to match multiline blocks.

If that is the intended purpose of the suggestion here then I still don't see why it would be preferred to simply having the previous up/down behaviour by default. With this change I would have to type a partial match and then push `delete up` to get the most recent match rather than just `up` in the previous behaviour. Perhaps it is because I don't know anything about the internals of IPython but I am yet to really see a rationale across various GitHub issues for the change to up/down at all.

It seems that "buffer history" and "suggestions history" are two different things and up/down has been changed to use the suggestions history. The differences are that the suggestion mode only handles single lines and does not automatically complete the whole line. If I understand correctly the only potential advantage of using the suggestion mode is that it makes it possible to complete the suggestion incrementally if desired. That does not seem like a common case to me compared to just wanting to rerun the line as it is though. The history buffer mode does allow editing the line(s) if what is wanted is to run a modified version of the previous code but it provides a better interface for modifying the previous command than the one that is provided by suggestion mode.

The proposal here is that `delete` can be used to exit suggestion mode and switch to buffer mode but I think that that is something should just happen implicitly when pushing `up` with no need to press the `delete` key.

**Comment by krassowski** [comment]
> It seems that "buffer history" and "suggestions history" are two different things and up/down has been changed to use the suggestions history. The differences are that the suggestion mode only handles single lines and does not automatically complete the whole line.

Correct.

> If I understand correctly the only potential advantage of using the suggestion mode is that it makes it possible to complete the suggestion incrementally if desired

...and the suggestions are always on rather than on-demand.

> That does not seem like a common case to me compared to just wanting to rerun the line as it is though. The history buffer mode does allow editing the line(s) if what is wanted is to run a modified version of the previous code but it provides a better interface for modifying the previous command than the one that is provided by suggestion mode.

This preference will vary between users, but yes, I believe that a substantial % of users more often re-runs lines as-is. It is not clear where the majority is here (I really appreciate comments of everyone who provided feedback, but let's remember that users who are happy or indifferent to the current behaviour were less likely to engage, and the fraction of users who did come to express opinion is tiny compared to number of IPython users).

> The proposal here is that `delete` can be used to exit suggestion mode and switch to buffer mode but I think that that is something should just happen implicitly when pushing `up` with no need to press the `delete` key.

Let me re-frame the above to: "the default mode of `TerminalInteractiveShell.autosuggestions_provider` should be `AutoSuggestFromHistory` not `NavigableAutoSuggestFromHistory`". As we discussed along https://github.com/ipython/ipython/issues/13878#issuecomment-1484060390 this is a fine suggestion, but then users who do prefer `NavigableAutoSuggestFromHistory` (and would then need to opt-in) would still benefit from the proposed `delete` behaviour, right?

**Comment by krassowski** [comment]
https://github.com/ipython/ipython/issues/13992 is a follow-up for this one.

**Comment by aanastasiou** [comment]
@krassowski Fair enough, good luck with your endeavour.

**Comment by cottrell** [comment]
The "OLD" behaviour (ipython 8.7.0 for example) is:

1. type a bit i.e. "from "
2. hit up arrow
3. immediately get the *complete* last thing in history
4. hitting up down goes through the history
5. hit enter to run command

The "NEW" behaviour (ipython 8.11.0 for example) breaks this as doing the above results in an error. One needs to add

4a. hit right-arrow

To avoid the error.

As long as the old behaviour is preserved, I don't have strong opinions about new optional flavours at the moment but am interested understanding how people find different things useful.

> @cottrell
> 
> > Can you clarify what this ia a proposal for? Is this for some detail of the NEW opt-in-only flavour? Or is this as an alternative to replicating the OLD behaviour?
> 
> It is not clear what you mean by NEW/OLD. This proposal is for the Del to discard auto-suggestion as [on third GIF](https://user-images.githubusercontent.com/5832902/227661534-38083923-57a1-4d7d-965d-598f8f0656c1.gif) in top-level comment. This proposal does not change any other behaviour as far as I am aware of. If it does then that would be an important point in the discussion. You can emulate the proposed behaviour by copy-pasting `custom_shortcuts` snippet from [top-level comment](https://github.com/ipython/ipython/issues/13987#issue-1640192534) in IPython 3.11+.
