### ISSUE TITLE
IPython can't provide completions for second level modules when Jedi completions are disabled

### ISSUE THREAD

**Issue by ccordoba12** [ipython/ipython#14028]
This problem was reported in [Spyder](https://github.com/spyder-ide/spyder/issues/20381#issuecomment-1419243534) and I was able to reproduce it locally. Basically, if you run

```python
In [1]: import numpy as np

In [2]: np.linalg.<Tab>
```

you won't get completions for the `linalg` module.

After a bit of testing, I found that this problem doesn't show up if Jedi completions are enabled. But we have them disabled by default in Spyder because they introduce serious lags when working with large dataframes.

It'd be nice if this could be fixed for the next IPython release and I'm able to put some time to do it. @krassowski, could you let me know where to start looking for a possible solution? Thanks!

**Comment by krassowski** [comment]
Quick answer, since:

```python
%config IPCompleter.use_jedi=False
```

does not work, but:

```python
%config IPCompleter.use_jedi=False
%config IPCompleter.evaluation='unsafe'
```

seems to work ok (please confirm), I would say that we may need to relax the guards in default evaluation mode.

In the default limited evaluation mode we allow:

https://github.com/ipython/ipython/blob/47d043e1dd051294d85f41b18f8e3c1f8434fd5c/IPython/core/guarded_eval.py#L705-L719

and in unsafe:

https://github.com/ipython/ipython/blob/47d043e1dd051294d85f41b18f8e3c1f8434fd5c/IPython/core/guarded_eval.py#L720-L728

This looks related to some `getattr` rule, but needs debugging as I don't immediately see why it does not work on second level.

**Comment by ccordoba12** [comment]
> seems to work ok (please confirm)

Yep, I confirm that's the case.

> This looks related to some getattr rule, but needs debugging as I don't immediately see why it does not work on second level.

Ok, I'll take a look at it. Thanks for the pointer.
