### ISSUE TITLE
my jupyter notebook looks different!

### ISSUE THREAD

**Issue by banafsh89** [ipython/ipython#14127]
My jupyter notebook looks different after installing ISLP data set. It now looks like this:

<img width="1440" alt="Screenshot 2023-07-28 at 3 47 44 PM" src="https://github.com/ipython/ipython/assets/44900049/1f2e4b86-ab09-47cd-9de9-e23037c87cbe">

While previously it looked like this:

<img width="1440" alt="Screenshot 2023-07-28 at 3 48 07 PM" src="https://github.com/ipython/ipython/assets/44900049/9c492241-c950-4255-a4f3-63000872c7d8">

I upgraded my jupyter notebook but still not working. Any idea why that happened?

**Comment by banafsh89** [comment]
I uninstalled all the installation of jupyter notebook and re-installed it again and it did work!

**Comment by krassowski** [comment]
The development of Jupyter Notebook (previously IPython notebook) is not happening in this repository since 2015 ([The Big Split™](https://blog.jupyter.org/the-big-split-9d7b88a031a7)) so it is not an appropriate place to ask for user support about Notebook-specific questions. As for the change in appearance, a new version of Notebook, v7 was released 4 days ago, see [Announcing Jupyter Notebook 7](https://blog.jupyter.org/announcing-jupyter-notebook-7-8d6d66126dcf). If there are any regressions in new version please report bugs in https://github.com/jupyter/notebook; these may include tweaks to user interface (since it was rebuilt from scratch with aim of visually matching the previous version).
