### ISSUE TITLE
Environments/kernels are ignored with running !some_exe

### ISSUE THREAD

**Issue by eusebiu** [ipython/ipython#14151]
### Bug description

Running some_exe using !some_exe syntax is not considering the kernel associated with that session.

#### Expected behaviour

Running some_exe using !some_exe syntax must consider the kernel associated with that session and any tools, env variables that are present in that environment.

### How to reproduce

1. Open hub, login
2. Create a terminal session and create a python environment (with other version of python, e.g. 3.7)
3. Install that environment in hub
4. Create a notebook and change the kernel in for the notebook to use that environment
5. Execute: ```!which python``` in a node which will display the OS python and not the one in the environment

### Your personal set up

Installed JupyterHub using on Docker:
```
RUN python3 -m pip install jupyterhub jupyter notebook
```

 - OS:
ubuntu 22.04
 - Version(s):
 jupyterhub, latest, python 3.10

**Comment by minrk** [comment]
You're right, `!` executes a system shell command, inheriting the parent environment, so `!which python` finds the first `python` in $PATH. It is not a requirement of IPython, Jupyter, or JupyterHub that kernels be launched with the Python first on their $PATH, which appears to be what you're requesting. If we automatically modified a user's $PATH env to insert `sys.executable.parent` to $PATH, it is at least as likely to produce an unexpected path result as respecting the environment that the user provided to us, which is what we do now.

The issue seems to live mostly in your step 3 ("install that environment in hub") for which there are many possible implementations, some of which may do what you want. One such implementation is to install the kernel such that it's launch command explicitly activates the environment prior to invoking the kernel, e.g. with the script:

```bash
#!/bin/bash
source /path/to/env/bin/activate
exec "$@"
```

which ensures the env is fully activated prior to launching the kernel. Or if you're using `conda`, you can change the command to `conda run -n environment python3 -m ipykernel ...`. ([venv-run](https://pypi.org/project/venv-run/) appears to be the same thing for venvs).

Or the simplest, direct solution to only insert the env into the PATH, add the line:

```
  "env": { "PATH": "/path/to/env/bin:$PATH" },
```

to your kernelspec.json, e.g.

```python
{
  "env": { "PATH": "/path/to/env/bin:$PATH" },
  "argv": [
    "/path/to/env/bin/python3",
    "-m",
    "ipykernel_launcher",
    "-f",
    "{connection_file}"
  ],
  "display_name": "Python 3 (ipykernel)",
  "language": "python",
  "metadata": {
    "debugger": true
  }
}
```

I think it's a reasonable feature request to allow the `ipython kernel install command` to _optionally_ include a certain amount of env activation in the generated kernelspec to make this easier, but that's a little tricky to express because there are many flavors of activation (conda, venv, simple path insertion, etc.).

**Comment by eusebiu** [comment]
Hi. Thanks for the comprehensive answer!
Indeed, setting the env in the kernel works fine but only after I restart the entire server, not the kernel itself.
