### ISSUE TITLE
Auto-scrolling of long output should be configurable in the UI

### ISSUE THREAD

**Issue by fperez** [ipython/ipython#2172]
We've had on-list, in person and here (#2154) various requests for different thresholds or behaviors regarding auto-scrolling.  Ultimately there's no one good default that fits all cases, so this should have a UI control for users to enable/disable the feature as well as changing the threshold.

**Comment by uriva** [comment]
+1

**Comment by dwt** [comment]
I'd like to add another use case here, I would often like to use graphs that are slightly larger than the default scroll region size, which makes them very awkward to use (bokeh user here). So please allow setting the threshold some way.

**Comment by JanSchulz** [comment]
Just because I found this earlier than the right solution (and the above didn't work anymore to disable the scolling): 

https://github.com/minrk/ipython_extensions/blob/master/extensions/disable_autoscroll.py

-> just execute the JS in a `%%javascript` does the trick...

**Comment by birdmw** [comment]
wish it was a thing

**Comment by matthewmacleod** [comment]
I just found this issue since I was googling to figure out how to turn off auto scrolling. It would be useful and appreciated if someone had time to fix this. I mean the ability to turn auto-scrolling on and off. Thanks.

**Comment by matthewmacleod** [comment]
I had trouble getting the above javascript to work on my computer, but I was able to get the ipython notebook extensions here to work:

https://github.com/ipython-contrib/IPython-notebook-extensions

**Comment by mdengler** [comment]
The original request was for:

> a UI control for users to enable/disable the feature as well as changing the threshold.

Plumbing code is in place to enable such a UI (for [#1 enable/disable](https://github.com/ipython/ipython/issues/2172#issuecomment-14685420) and [#2 changing the threshold](https://github.com/ipython/ipython/issues/2172#issuecomment-53708976)).  Are you still open to contributions for such a UI?  The commit that closed this issue was about persisting the per-cell scroll state metadata, which is different from the original request (the commit is/was needed to implement a solution to this issue, which is great).
