### ISSUE TITLE
ascii progressbar in notebook broken

### ISSUE THREAD

**Issue by mqk** [ipython/ipython#2285]
I recently updated to the tip of the IPython development and discovered that the ascii progressbar that I like to use (http://code.google.com/p/python-progressbar/) no longer works in the notebook. [I understand that using a javascript progressbar would be more appropriate for the notebook, but for sake of compatibility with running the same code in a terminal I'd like to use the ascii-based one also in the notebook.]

I've tracked the problem down to commit d980adfb445d5aac3c01ae6d5d1497d6140845db (yay git bisect!) where this line

txt = txt.replace('\r', '');

was removed from the function fixConsole() in IPython/frontend/html/notebook/static/js/utils.js. If I reinstate that line, the progressbar once again works for me.

Here's an example:

```
import time
import progressbar as pb

def example1():
    widgets = ['Test: ', pb.Percentage(), ' ', pb.Bar(marker=pb.RotatingMarker()),
               ' ', pb.ETA(), ' ', pb.FileTransferSpeed()]

    Neval = 1000
    pbar = pb.ProgressBar(widgets=widgets, maxval=Neval).start()
    for i in range(Neval):
        time.sleep(0.01)
        pbar.update(i)
    pbar.finish()

example1()
```

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository if this is an actual bug or code proposal. For general help use [discourse](https://discourse.jupyter.org).  This will allow to keep the number of opened issue on the IPython repo under control and allow you to get faster response.
