### ISSUE TITLE
Better document how organizing remote running code in different functions and modules

### ISSUE THREAD

**Issue by jankatins** [ipython/ipython#2489]
Currently organizing code in different modules or different functions results in errors when such code is run remotely (see https://github.com/ipython/ipython/issues/2473#issuecomment-9200719 for an example).

It would be nice if the documentation would show how to work around such issues and maybe implement a simple way to decorate such functions so that running them remotely is easy.

**Comment by RafalSkolasinski** [comment]
Hi, I am trying to use ``send_module`` function from https://github.com/ipython/ipython/issues/2489 to make my module available on remote engines. 

First of all I am suspicious about lines 
```python
        if os.path.exists(filename):
            return False
```
because after sending module once, changing it locally and trying to send again would not work, am I right?

Another annoying problem I got is that anytime I try to send my module the only thing that is being written to a file on remote machine is ``<memory at 0x2aac02ac43e0>`` or similar stuff. 

I would be grateful for a help.
