### ISSUE TITLE
Notebook inline CSS style blocks borked by text processor.

### ISSUE THREAD

**Issue by Panoplos** [ipython/ipython#2510]
Environment: Mac OS X Lion; Chrome 24.0.1297.0 dev; 0.13 w/ MathJax patch.

Problem code

``` html
<style type="text/css">
    table.prob {
        border: none;
    }

    table.prob tr {
        border: none;
    }

    table.prob th {
        border-style: solid;
        border-width: 0px 0px 2px 0px;
    }

    table.prob tr td {
        border: none;
    }
</style>
```

Is processed as 

``` html
<p><style type="text/css">
    table.prob {
        border: none;
    }</p>

<pre><code>table.prob tr {
    border: none;
}

table.prob th {
    border-style: solid;
    border-width: 0px 0px 2px 0px;
}

table.prob tr td {
    border: none;
}
</code></pre>

<p></style></p>
```

Without spaces between definitions, it is fine...

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository if this is an actual bug or code proposal. For general help use [discourse](https://discourse.jupyter.org).  This will allow to keep the number of opened issue on the IPython repo under control and allow you to get faster response.
