### ISSUE TITLE
Readline won't load on pypy-2.0-beta1 win8-64bit

### ISSUE THREAD

**Issue by jansegre** [ipython/ipython#2670]
I'm using Windows 8 64-bit with PyPy 2.0 beta1.

I installed pip then 'pip install ipython'.

Installation went smooth but when I run ipython I get:

```
C:\Users\Jan>ipython
C:\Dev\pypy\site-packages\IPython\utils\rlineimpl.py:80: UserWarning: Failed GetOutputFile warnings.warn("Failed GetOutputFile")
WARNING: Readline services not available or not loaded.WARNING: Proper color support under MS Windows requires the pyreadline library.
You can find it at:
http://ipython.org/pyreadline.html
Gary's readline needs the ctypes module, from:
http://starship.python.net/crew/theller/ctypes
(Note that ctypes is already part of Python versions 2.5 and newer).

Defaulting color scheme to 'NoColor'Python 2.7.3 (7e4f0faa3d51, Nov 22 2012, 10:06:18)
Type "copyright", "credits" or "license" for more information.

IPython 0.13.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
...
```

My PyPy is installed at C:\Dev\pypy, though that's probably not a problem.

I have C:\Dev\pypy and C:\Dev\pypy\bin on my path. I use it from cmd.

I tried reinstalling pyreadline and installing cffi, but that didn't sovle it.
I tried installing ctypes but that failed since I have VS2012 and probably need VS2008 instead.

**Comment by romantu** [comment]
+1 Win 7 64bit, pypy 2.6.0 32bit, pyreadline==2.1
import pyreadline
ok
but does not work and no colors
any suggestion ?? any progress since 9 Dec 2012 ??
Unbelievable...

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one. It's too bad we weren't able to resolve this sooner, sorry to everyone who bumped into this issue with PyPy. None of the core IPython developers use windows, so anything windows related takes a while to get our attention. Additionally, since this affected only PyPy, there were even fewer people impacted and and even smaller sliver of a chance that we'd prioritize to get this fixed.

The good news is that we no longer use `pyreadline` and have switched to [prompt_toolkit](http://python-prompt-toolkit.readthedocs.io/en/stable/) since [IPython 5.0](https://blog.jupyter.org/2016/07/08/ipython-5-0-released/). From what I can tell based on [this Travis-CI page](https://travis-ci.org/jonathanslenders/python-prompt-toolkit) - prompt_toolkit supports PyPy, so hopefully this will work out for you all.

Happy hacking! :bowtie:
