### ISSUE TITLE
Cannot interrupt infinite loops in the notebook

### ISSUE THREAD

**Issue by wasade** [ipython/ipython#2781]
I recently gave an introduction to Python programming at the Workshop on Genomics. For the tutorial, we used the notebook interface and it was very well received (thank you!). During the discussion on loops, I asked the students to convert an example for loop into a while loop. In the process many of the students created infinite loops. For some of those students, it crashed Firefox. The fix was to kill the notebook server and kill the browser. All of the students were using Ubuntu-based virtual machines and Firefox as the browser. If it would help, I can get further details about the systems as well as investigate if I can recreate this behavior on my copy of the virtual machine.

**Comment by fabioedoardoluigialberto** [comment]
I also have this **critical** issue. It seems to be related to loops indeed. This prevents me from running long simulations or data analysis, which means: I'm screwed...

I don't know if it's related but I noticed that once it hangs, the hyperthreading seems to collapse into one CPU still working. You can see that by using [htop](http://hisham.hm/htop/), for example. At first, it seemed to me that hyperthreading (which the numpy -> BLAS libraries are exploiting on my machine) was the one crashing and then the whole thing would run crazy slow, but then I tried to interrupt and had no luck and so I realized it was the IPython kernel just getting stuck.

This problem never occured me when:
- I was using an older machine (but still very similar, just fewer RAM and CPUs)
- I was using old ipython<3.0
- I was not working on a remote IPython notebook

My educated guesses are:
- issue with the some socket somewhere...
- matplotlib threading backends are messing up <-- but that's just because they almost always do so better put there the bet ;)

When the problem occurs, I just restart the kernel from within the web interface and re-do what I was doing...

**Comment by mizzao** [comment]
I also see this problem quite frequently and it's hard to resolve - if there is a lot of data that is time-consuming to process in the kernel, it can be quite a pain to kill everything and force a restart. Definitely not an imaginary bug :)

**Comment by sc932** [comment]
I also have this problem on OSX + chrome.

**Comment by wasade** [comment]
@minrk, I think this may be worth reopening. I don't have sufficient privs to just reopen short of creating a new issue.

**Comment by sc932** [comment]
From the CLI it looks like pressing the stop button is doing something, but the notebook remains completely unresponsive.
```
[I 15:26:22.224 NotebookApp] Kernel interrupted: edee0497-b340-43fd-be77-1ad67e5170ee
[I 15:26:32.197 NotebookApp] Kernel interrupted: edee0497-b340-43fd-be77-1ad67e5170ee
[I 15:26:42.688 NotebookApp] Saving file at /Untitled.ipynb
[I 15:27:30.993 NotebookApp] Kernel interrupted: edee0497-b340-43fd-be77-1ad67e5170ee
[I 15:27:35.605 NotebookApp] Kernel interrupted: edee0497-b340-43fd-be77-1ad67e5170ee
[I 15:28:43.999 NotebookApp] Saving file at /Untitled.ipynb
[I 15:29:28.038 NotebookApp] Kernel interrupted: edee0497-b340-43fd-be77-1ad67e5170ee
```

**Comment by mizzao** [comment]
I think one of us needs to find a simple notebook that replicates this issue, at least on some system. Otherwise it will probably not be fixable.

**Comment by DGMichael** [comment]
I'm also seeing this problem.

**Comment by miraculixx** [comment]
> I think one of us needs to find a simple notebook that replicates this issue, at least on some system. 

```
while True:
    print "foo"
```

This makes Firefox use 100% CPU and unresponsive in any way or form. Killing Firefox and the IPython process is the only way to get the system back.

Ipython 3.0.0
Firefox 42.0
Linux 3.13.0-24-generic

**Comment by sc932** [comment]
I can reproduce with
ipython 3.2.0
python 2.7.10
Chrome Version 46.0.2490.86 (64-bit)
OSX 10.10.5

**Comment by red-bin** [comment]
Pretty huge annoyance for me, too. I often have to kill the entire notebook server along with chrome because of this problem. I can get to the point where I click the interrupt kernel button and it highlights as if it was clicked, but something, somewhere doesn't receive the message to stop. 

My initial impression is that it's a problem with chrome's text rendering engine, but I know little on how that works.

Another example of slowness is when a relatively large matplotlib comes to the foreground after scrolling to it. The entire notebook becomes extremely jittery for a good 4-5 seconds.

For what it's worth, I'm using a fairly beefy machine, so it's especially weird that jupyter can bring my entire machine to its knees.

9/10, it happens on accident, so it's not as easy as calling it a user error bug.

**Comment by bradknox** [comment]
I just had this problem occur for me (or at least it fits the profile described above). I couldn't get window to be regularly responsive, but _I could_ do a very slow clipboard copy of the whole page, which allowed me to retain my recent code changes.

Not a solution to the problem, but a potential way to mitigate its consequences.

**Comment by domdog** [comment]
I've had the same problem today and in the past, running Linux Mint(18.0) and firefox. I was a very simple count() generator, but I was messing with __getitem__ and, in a silly way, set a print on the key.

**Comment by takluyver** [comment]
The latest versions of our packages implement output throttling, which should mitigate the issues with large amounts of output slowing the browser down.

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository.  This will allow to keep the number of opened issue on the IPython repo under control. 

Feel free to keep commenting or reopen if necessary.

Thanks.

**Comment by wasade** [comment]
@Carreau, do you have a suggested repository (or did this just not get carried over to where the notebook issues are tracked...)?

**Comment by Carreau** [comment]
That will need to be migrated either to jupyter/notebook or jupyterlab/jupyterlab. LIkely second one if it affects jupyterlab as well.
