### ISSUE TITLE
Switching rendering backends

### ISSUE THREAD

**Issue by ribonoous** [ipython/ipython#2851]
Say I have a python script that I can call from IPython. I would like this script to 

* Build some plots for the sole propose of saving them to disk with `fig.savefig(path_to_file)`, without showing them on screen.

* Build some other plots that are displayed on the screen. 

Is this currently possible within the same script?

I have tried with:

``` python 
matplotlib.use('Agg')
# The following figures will not render on the screen
# but can be saved directly to disk

matplotlib.pyplot.switch_backend('QT4Agg')
# The following figures will render on the screen

matplotlib.pyplot.switch_backend('Agg')
# The following figures will not render on the screen
# but can be saved directly to disk
```
with no luck. Is there anything that I am doing wrong?

----------------------

Also, if I have a Python script that starts with:
``` python
import matplotlib
matplotlib.use('Agg')
from pylab import *
```
and then I call the script from my IPython session, and then I change the rendering backend in the script:

``` python
import matplotlib
matplotlib.use('QT4Agg')
from pylab import *
```
and then I run it again from the same IPython session, the changes do not seem to take effect. However, if I restart IPython the backend specification is taken into consideration.

This is all with the latest stable versions of Python, matplotlib and IPython.

**Comment by drevicko** [comment]
I know you're trying to clean out the cobwebs, but seeing as I can get unresponsive popups and crash the kernel by killing them if I do `%pylab inline` followed by `switch_backend` and trying to plot again, I think this counts as a bug worth noting. 

I imagine it's a pain to fix. We should at the least do something like hijacking `switch_backend` when `%pylab inline` is executed so that it tells the user that you can't.
