### ISSUE TITLE
Add support for drag and drop image into notebook cell

### ISSUE THREAD

**Issue by Tooblippe** [ipython/ipython#4111]
It would also be great if you can drag an image link or image (or paste one) from your local machine into a cell in the ipython notebook. This could upload it to some directory and also create the markdown do display the image in the cell.

I wish I could code better, would have tried myself.

**Comment by stevengj** [comment]
I'd be happier with something that just created a new cell, analogous to an output cell with a `display_data` message for image data, that embeds the image in the notebook and displays it just like `display_data` except that it is not tied to an input cell.   (I don't want it to be editable as Markdown b64.) This would be much nicer for e.g. sharing notebooks, since I wouldn't have to remember to copy the image file along with the notebook.

**Comment by dsblank** [comment]
@juhasch Is the drag and drop extension broken in IPython 3?

**Comment by juhasch** [comment]
The extension works for me for IPython 3.

**Comment by stevengj** [comment]
Closed by jupyter/notebook#621?

**Comment by minrk** [comment]
Yes, indeed.
