### ISSUE TITLE
kernel dies with " : cannot connect to X server " attempting to plot when running under byobu

### ISSUE THREAD

**Issue by drevicko** [ipython/ipython#4116]
I often run `ipython notebook` from a `byobu` (aka `screen`) on Ubuntu. In my `byobu` terminals, the `DISPLAY` environment variable is not set, and as a result attempting to create a matplotlib plot results the kernel crashing with:

   : cannot connect to X server 

I can fix it by executing `export DISPLAY=:0` before I run `ipython notebook`.

I guess this is more a problem with `byobu`/`screen`, bit it'd might be useful to try `:0` (or it's equivalent on other OS's) if `DISPLAY` is empty.

At the very least, a more informative error message to the log is in order - it took some digging in the source code to track it down..

ps: [This pull request](https://github.com/ipython/ipython/pull/3883) may have some relevance??

**Comment by cswarth** [comment]
Is this issue ever going anywhere?  This bug still occurs late 2015 when running jupyter notebook on a headless server.   Why does the server need an X11 server to display output on a web page?

```

**Comment by takluyver** [comment]
I think we have agreed before that inline should be the default backend when you use matplotlib inside an IPython kernel, but not got around to implementing it, because people are already used to running `%matplotlib inline`, and because it could be confusing if they've explicitly configured another default backend in matplotlibrc.

**Comment by cswarth** [comment]
I saw the [long thread on this topic](https://mail.scipy.org/pipermail/ipython-dev/2015-July/016631.html) with many proposed solutions, and issue ipython#6424 meant to track progress.   Some people in that thread describe this as soft-failure, where no plot is produced when expected.   On headless systems without X11 this is a fatal error - the kernel just dies.  Users without access to the server logs will be completely mystified by this fatal error.

To make the situation even more frustrating, the `--matplotlib` option is not available on the `jupyter notebook` command line, and as far as I can tell there isn't an option for overriding this behavior in  `~/.jupyter/jupiter_notebook_config.py`  So instead of getting better, it feels like the situation has actually gotten worse.

This has been discussed to death.    Overriding module loading to detect when matplotlib module was loaded the first time seems like a robust solution.  It would be nice see one of the proposed solutions adopted, even if it isn't perfect.  

[BTW this issue should probably be merged with  ipython#6424 ]

**Comment by takluyver** [comment]
You should still be able to configure it in `~/.ipython/profile_default/ipython_kernel_config.py`, by setting:

```python
c.InteractiveShellApp.matplotlib = 'inline'
```

It's an IPython kernel issue (because it's about executing Python code), so the config is there rather than under Jupyter.

Thanks for pointing out #6424 - I'll close this issue in favour of that one (and I'll actually get round to doing something about it).
