### ISSUE TITLE
Feature request: Be able to receive cell output from a remote kernel after reconnecting

### ISSUE THREAD

**Issue by ptwobrussell** [ipython/ipython#4140]
Once your browser disconnects from the kernel running on a remote notebook server, there's no way to recover the output once the notebook reconnects to the kernel. My understanding is that even though the output is actually shipped back to the browser, it's just unable to be sent to the right cell for display. If you are using IPython Notebook for long-running computation in a cell, the ability to re-connect and get cell output from the point of reconnection forward would be nice to have.

**Comment by jacobhinkle** [comment]
@Carreau, I am willing to help get this working, as this would be a big help to my coworkers and I who are used to working with screen for remote jobs.  You say this is being worked on. Is there a fork or branch I could take a look at? Thanks.

**Comment by Carreau** [comment]
Thanks a lot for the proposal. 

Hum, right now that will be though, but let me make a quick recap of future plan. 

1. get 3.0 out of the door. 
2. get https://github.com/jupyter/jupyter-drive out of the door (need 1)
3. Refactor IPython to support RT colaboration (technically help with what you ask, 2 will help a lot) 
4. Make an Operational Ttransform server (google RT like) backend for RT communication (independant of 1-3 mostly, but knowing google RT API would help to make things compatible)
5. Make kernel speek with (4) instead of browser. 

Depending on what you want to work on there are plenty to do. 
Even just playing with IPython master, testing Pull request, or reviewing code
is of huge help as it free us time to work on more complex stuff.

Even if you are just better at communicating that we are, and know a bit about our future plan, 
even proposing a news to be posted on main ipython.org website would be awesome !

I should probably make a blog post that details more what we are doing :-P

**Comment by malmaud** [comment]
What if the web UI could just show some kind of raw console with the output being sent from the kernel, even if it doesn't know what cell that output should go into? Obviously that's not the full long-term solution, but at least it would alleviate a critical usability issue for those of us using the notebook to monitor long-running jobs.

**Comment by Carreau** [comment]
https://github.com/ipython/ipython/pull/7087 should at least lay down the basics for that where there are hooks to receive this output. We still don't know exactly what to do with the output, core team is divised half half on "the right thing'" to do.

**Comment by jeanpijon** [comment]
This is dirty, DIRTY hack! But if you want to be able at least see the progress output (not cached though), put this code in your custom.js
```javascript
$([IPython.events]).on('app_initialized.NotebookApp', function(){
      IPython.notebook.events.on('received_unsolicited_message.Kernel', function(evt, data) {
		cells = IPython.notebook.get_cells();
		  ncells = cells.length
		  idx = ncells-1
		  for (var i = ncells-1; i >= 0; i--) {
				if (cells[i].get_text() != ""){
					idx = i;
					break;
				}
		}
		cells[idx].output_area.handle_output(data)
		}); 
});
```
It will append the output from the kernel to the last non-empty code cell. Not nice, but works for me...

**Comment by udibr** [comment]
+1

**Comment by chasewright** [comment]
+1

**Comment by pasky** [comment]
+1

**Comment by deepakrox** [comment]
+1

**Comment by mohamed-ezz** [comment]
+1

**Comment by sebastian-schlecht** [comment]
+1

**Comment by zhengbx** [comment]
+1

**Comment by andychisholm** [comment]
+1

**Comment by wangz10** [comment]
+1

**Comment by tachim** [comment]
+1

**Comment by TashaArvanitis** [comment]
+1

**Comment by themummy** [comment]
+1

**Comment by paolodoors** [comment]
+1

**Comment by BenBBear** [comment]
+1

**Comment by BenBBear** [comment]
I think if the notebook could have **another V layer** to capture all the progress data. The browser will interact with this layer instead of raw python kernel. The problem could be solved. (Like a long running proxy browser on your server)  This doesn't seem to be a small surgery.


But another idea I have is more like frontend point of view. If the jupyter notebook supports server rendering someday using react/angular2.js/etc...  then this problem will be automatically solved.

**Comment by Carreau** [comment]
Yes @BenBBear, you seem to have came up with roughly one of the long-time planned architecture. 

The extra question we still haven't solved is how to build real-time collaboration on top of that.

Currently if you used Python you can use `Futures` to hold intermediate results.

**Comment by BenBBear** [comment]
@Carreau   

Great to see RT collaboration is on the road map.  Maybe the collaboration could be easier if the proxy layer is websocket-enabled instead of just http? Just my rough idea.  


Use Asynchronous computing to hold intermediate result, this is genius...  👍

**Comment by abrahamneben** [comment]
+1

**Comment by guillaumerosinosky** [comment]
+1

**Comment by mharradon** [comment]
+1

**Comment by francomarianardini** [comment]
+1

**Comment by Carreau** [comment]
If you can restrain from just posting +1 that woudl be great. You can or use emojis on the issue, github added them for that, as you can sort issues by number of +1 Emojis. Also if you just like to subscribe to the issue there is the "subscribe" button on the right. 

We are aware of the issue and are doing our best. +1 ing won't make things faster. though reviewing open PRs and trying to write simple patches for issue tagged as "Need contributor" can free us some time to actually work on this :-) We'll also be happy to teach you jupyter internals to get new contributors !

Also at some point  the issue probably need to be migrated to jupyter/notebook as this track only core IPython issue now. 

Thanks !

**Comment by joernhees** [comment]
+1 (SCNR)

A connection drop today also made me fall into that trap :-/

I guess even at the moment something on server side must be able to notice that no client is connected anymore. Can't it in such cases modify the ipynb file directly? (Like an auto-saver server side fail-over loop in case no client is reachable.)

Obviously a proper, cool async solution that also allows multi-player edit would be awesome, but after nearly 4 years, maybe a simpler solution first?

**Comment by simon19891101** [comment]
+1

**Comment by wanglovesyang** [comment]
+100000000000

**Comment by lucasb-eyer** [comment]
This actually seems to happen now, though. When I leave the notebook open, put my laptop to sleep while there's output coming (even matplotlib images), then later resume my laptop, re-initiate the connection and reconnect to the kernel, I receive the output that happened while the connection was gone. There's actually two flags controlling this that I had to increase:

```
## (bytes/sec) Maximum rate at which stream output can be sent on iopub before
#  they are limited.
c.NotebookApp.iopub_data_rate_limit = 100000000

## (msgs/sec) Maximum rate at which messages can be sent on iopub before they are
#  limited.
c.NotebookApp.iopub_msg_rate_limit = 100000

## (sec) Time window used to  check the message and data rate limits.
c.NotebookApp.rate_limit_window = 3
```

**Comment by phizaz** [comment]
@lucasb-eyer You mean jupyter notebook or jupyterlab? It seems to be somewhat working in jupyterlab, but not perfectly. 

Regrading your settings, could you justify that your settings relevant?

**Comment by lucasb-eyer** [comment]
Jupyter notebook, I didn't even know about jupyterlab :smile:

Yes, the settings are relevant because when the notebook reconnects, all missed messages come streaming in, which kicks-in these rate-limits. Before adjusting the values as above, I only got the first bunch of missed messages upon reconnect exactly because of these rate-limits. Now they are large enough so that I usually get everything I've missed. That's in my typical workflows and tasks, at least. The notebook actually pointed me to those settings when starting to drop messages.

**Comment by AbhinavMehrotra** [comment]
Which version of notebook are you using? I couldn't get this working on 4.0.6 version.

**Comment by lucasb-eyer** [comment]
Uhm, seriously? `4.0.6` is 3 years old! I'm using `5.4.1` in all that I described above.

**Comment by francomarianardini** [comment]
Hello Lucas, thanks for your suggestion.

I am using Jupyter Notebook 5.4.0. I put the three options you were
mentioning in the config file.

Unfortunately, I also couldn't get this working. I will update to 5.4.1 to
test the same version you have.

Best regards,

Franco

**Comment by CYHSM** [comment]
@lucasb-eyer I guess this only works when you reopen the browser, see https://github.com/jupyter/notebook/issues/1647: 

> What #2871 did was buffer any outputs (and other messages) until the user reconnects -- it will only help you for cases where you're reconnecting the same tab.

So this fix does not really apply for a remote use case where you want to close the browser tab.

**Comment by lucasb-eyer** [comment]
@CYHSM Your statement is self-contradicting, I guess you wanted to write

> this only works when you *don't* reopen the browser"

right? Because in that case, I think you are right: I always put my laptop on standby and thus the notebook stays in the same tab.

**Comment by mjkvaak** [comment]
+1, this feature would be extremely useful

**Comment by ThoSap** [comment]
+1

**Comment by Yiannis128** [comment]
Hi, has this been looked at yet?

**Comment by krassowski** [comment]
Yes (https://github.com/jupyterlab/jupyterlab/pull/15448). The notebook codebase is no longer in IPython repository, instead it resides in https://github.com/jupyterlab/jupyterlab and https://github.com/jupyter/notebook.

Closing in favour of issues in the repositories where the relevant code is actually in:
- https://github.com/jupyter/notebook/issues/641 and
- https://github.com/jupyterlab/jupyterlab/issues/2833
