### ISSUE TITLE
IPython should have functionality to store user data in backend db

### ISSUE THREAD

**Issue by kaazoo** [ipython/ipython#487]
It would be nice if IPython would have a generic way to store user data in it's backend database. Let's say you want to save some extra information which you don't want to add to each attributes of a bigger number of tasks.
One example would be 'jobs' which are formed by a set of tasks in the field of 3D rendering management. It would be helpful to store the following information for a number of tasks: name of job, id of job, start frame, end frame, blocksize, renderer, scene file, owner, ... .
Having functions for setting and getting database values would be enough. The attribute names of a job could be flexible. So it wouldn't be made not just for this form of application. 

Of course one could just modify the backend database without the help of IPython. But it would be great to do this transparently through IPython, so the developer doesn't need to know which backend database type is in use.

**Comment by Carreau** [comment]
Hi all, this is 4 years old, and should likely be migrated to ipyparallel. 

I suspect the parallel computing landscape has change quite a bit since then. 

I'm thus going to close, and suggest for you, if this is still relevant, to reopen on a better suited repository where it won't be hidden in 1k issues. 

Thanks !
