### ISSUE TITLE
%debug's raw_input wedges notebook if cell deleted

### ISSUE THREAD

**Issue by ivanov** [ipython/ipython#5026]
@minrk and @takluyver and I were just having a discussion about this.

our `raw_input()` that makes its way to the notebook respects KeyboardInterrupt, but in debug mode, we're in a loop that just issues another `raw_input()` prompt on interrupt.

If you delete a cell that had a debug prompt, you currently _have_ to restart the kernel in order to be able to do work again.

One approach might be to have our pdb exit on keyboard interrupt when running from the notebook. This would also help in cases where, even if the cell isn't deleted, you still have to locate it and exit pdb in order to continue doing work.

**Comment by soerenwolfers** [comment]
Bump

**Comment by impact27** [comment]
I would see two ways of solving this:
 - detecting if raw_input is from Pdb and sending “quit” instead of keyboard interrupt
 - opening a new cell if the notebook receives an input request that doesn’t go anywhere.

To detect Pdb you can either match the prompt to a list of known Pdb prompts (”(Pdb) “, “I Pdb> “, ...) or subclass Pdb to modify the message it sends to the frontend (with something like “shutdown_input”: “quit”

**Comment by soerenwolfers** [comment]
@impact27 When you say "you", do you mean ipython developers or do you mean there is an easy quickfix out of this for a generic user like me? 

Also, because I'm really confused about how glaring and drastic this problem is for me, just to be sure there is nothing else wrong with my setup:
 
(1) I run code in some cell
(2) It crashes
(3) I open a cell below it running `%debug`
(4) I figure out what went wrong a
(5) I think "problem solved, I don't need this debug cell anymore" and close the debug cell with `dd`. 
(6) If I forget to (q)uit pdb first I ruin my notebook and loose half an hour of data loading and transformation 

How is it possible no one else ran into this in the last 5 years? I run into this every week. Sure, you could say "just learn to (q)uit first" but given that there is not even a keyboard shortcut to jump to the pdb prompt, I can't see how anyone does not occasionally forget this. The worst is that even recovering the deleted cell doesn't help, because it's not connected to the pdb anymore.

**Comment by impact27** [comment]
I was thinking of a notebook developper or a user willing to work on the code and create a PR. I don't see an easy workaround for the generic user. I worked on something similar for `Spyder` and the main challenge I see to differenciate between pdb calls and `input` calls.

**Comment by impact27** [comment]
But it the issue is only related to jupyter notebook, then the conversation should probably be moved to https://github.com/jupyter/notebook .
