### ISSUE TITLE
request: Usability by alternative Python implementations

### ISSUE THREAD

**Issue by dsblank** [ipython/ipython#5032]
Most (if not all) of IPython could be utilized by alternative implementations of Python (such as PyPy, Jython, and IronPython) with a few fairly minor tweaks. As a single example, this code from IPython appears in a few places:

devnull = open(os.devnull, "a")

but gives an error ("The stream does not support seeking") in IronPython. I see no reason why devnull would be opened in append mode, so this would be very easy to fix by leaving out the "a". (However, perhaps there is some reason for this. In that case a try/except could wrap the open). 

Other examples might need more cases than sys.platform in ["win32", "linux2"] or another test to separate behavior.

I'd be glad to submit pull requests to help make IPython usable beyond CPython. Just wanted to make sure that the IPython team was open to such tweaking.

**Comment by ivanov** [comment]
Hey party people! I'm going through old issues and it seems to me that it makes sense to close this one. I think the main point of this issue was @dsblank inquiring if particular changes to IPython would be welcome, and since he went ahead and made a PR with those changes (#5055) which was merged, we don't need to keep this open.


Happy hacking! :bowtie:

**Comment by dsblank** [comment]
Feb of 2014... wow. My first uses of github, IPython, markdown... so many firsts. How times have changed. We don't even use IronPython any more. So yes, glad to close this.
