### ISSUE TITLE
ipython should get bashrc aliases for shell commands

### ISSUE THREAD

**Issue by ignatenkobrain** [ipython/ipython#5072]
```
$ alias ll
alias ll='ls -l --color=auto'
$ ipython 
Python 2.7.6 (default, Feb  4 2014, 15:36:52) 
Type "copyright", "credits" or "license" for more information.

IPython 0.13.2 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: !ll
sh: ll: command not found
```

**Comment by ivanov** [comment]
Thanks for your report. I'm going through cleaning up old issues, and I think it makes sense to close this one. This issue is quite old now and it is unlikely that we will ever support this in stock IPython, among other reasons one contributing factor is that IPython runs on platforms that do not come with bash at all (Windows, for example), as well as there being a bunch of different shells to choose from and shell preferences among the unix-like operating systems.


It's worth mentioning here that IPython does support its own `alias` mechanisms (read `%alias?` for more), as well as the execution of bash commands (via `%%bash` cell magic).

Happy hacking! :bowtie:

**Comment by westurner** [comment]
Why couldn't this be an optional function that's not on by default, that just doesn't work if there aren't any shells with alias features on the system?

Does this support:

- [ ] ash
  ```
  $ alias a=b
  $ alias
  a='b'
  ```
- [x] bash
  ```
  $ alias a=b; alias; alias a
  alias a='b'
  alias a='b'
  ```
- [x] zsh
  ```
  $ alias a=b; alias b='c d'; alias a; alias b
  a=b
  a='b c'
  ```

- [ ] fish
  ```
  $ alias a=b; alias b='c d'; alias
  alias a b
  alias b 'c d'

  $ alias a
  # Error: "alias: body cannot be empty"
  ```

- IPython:
  - `%rehashx?`
    - src: https://github.com/ipython/ipython/blob/main/IPython/core/magics/osm.py#L201 
    - > Update the alias table with all executable files in $PATH.
  - `ipython -p sh`
    - http://ipython.org/ipython-doc/stable/interactive/shell.html
    - https://github.com/ipython/ipython/issues/1297/
      - https://github.com/ipython/ipython/commit/280759b7d8d3edd8e28152f3a3e902e1ce4c3f8d#diff-80b160e05233354f02cb247f9955ca3d5130458ad5ecc9656dfd7f986531ce16R11-R17
  - IPython line magics and cell magics: 
    https://ipython.readthedocs.io/en/stable/interactive/magics.html
  - ```python
    # IPython magic commands for shell and python dev use
    ?

    %rehashx?

    !set -x; echo helloworld
    !!echo -e 'a\nb\bc'
    print(_)

    lines = !!echo -e 'b\nc\d'
    print(lines)
    %sx echo -e 'b\nc\nd'

    %%prun   # cell magic
    %prun    # line magic
    %prun?
    %prun -d ./example.py  # pdb
    %prun -p ./example.py  # cprofile

    %debug?
    %pdb?
    %pdb on
    %pdb off
    ```
