### ISSUE TITLE
Unable to autocomplete script namespace unless I start an embedded shell

### ISSUE THREAD

**Issue by ribonoous** [ipython/ipython#5562]
Say I run a script with:

`run my_script`

that exits with no problem.

If I then try to tab auto-complete any variables defined in the script in my IPython terminal I can't. However, I can still inspect them if I fully type any of the script variable names.

Strangely, if I drop myself into an embedded IPython shell, I can auto-complete the script variables within the embedded shell, and once I exit this embedded shell, I can also auto-complete them in the original shell, although retrieving any of the variables **always** results in an error that ends with:

`KeyError: '_oh'`

Is this a bug or expected behavior?
 
This is with `IPython 2.0`.

**Comment by ellisonbg** [comment]
Not sure where to go with this one...

**Comment by minrk** [comment]
I'm not sure what could be causing this. I can't reproduce it, so it must be some amount of configuration, IPython or otherwise. @ribonoous can you reproduce it when running IPython without any configuration (`IPYTHONDIR=/tmp/ipython ipython`)? What exact script are you using? Does it happen with a script that only has an assignment or two?

**Comment by ribonoous** [comment]
Thanks @minrk I don't think I have had this problem in some time. We should close and I can open it if I see it again. Thanks for looking into this again.

**Comment by minrk** [comment]
@ribonoous thanks!
