### ISSUE TITLE
Using an iframe as an HTML tag in Markdown no longer works in 2.0 Notebook

### ISSUE THREAD

**Issue by mebersole** [ipython/ipython#5711]
With IPython Notebook 1.x, I was able to embed YouTube videos and other features in the Notebook without having to execute an IPython code cell (using an iframe).  This was very useful for educational purposes in my Notebooks.  I believe with the HTML sanitation in Markdown cells in 2.0, this is no longer possible.

Is there way to re-enable this behavior?  Maybe if it's a Trusted Notebook?

**Comment by akimd** [comment]
I would like that too.  Currently I use %%HTML as a workaround, but that does not look nice.

**Comment by jason-s** [comment]
>Currently, in IPython 2.0 is not possible to embed iframes in markdown cell because of some sanitization to avoid malignant code to be executed... 

I get that on public servers, but on my own private server, how can I allow `<iframe>` and `<object>` tags?

**Comment by Carreau** [comment]
You can't. Or you need to patch the source. The reasoning is that almost
nobody understands the implication in allowing iframes in markdown. One of
them being "why does it work here and not there" questions from users. So
we push toward uniformity of feature support across frontend instead of
configurability of "dangerous" feature.

On Jun 28, 2017 6:13 PM, "Jason Sachs" <notifications@github.com> wrote:

Currently, in IPython 2.0 is not possible to embed iframes in markdown cell
because of some sanitization to avoid malignant code to be executed...

I get that on public servers, but on my own private server, how can I allow
<iframe> and <object> tags?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ipython/ipython/issues/5711#issuecomment-311709941>,
or mute
the thread

**Comment by kenokabe** [comment]
I think this is overkill security implementation.
At least, a config file can provide dangerously allow option.

**Comment by byubean** [comment]
I use notebooks for presentations, and the ability to embed video and other web resources would be really nice.

Many of the workarounds don't work in my case because I use non-python kernels.

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository if this is an actual bug or code proposal. For general help use [discourse](https://discourse.jupyter.org).  This will allow to keep the number of opened issue on the IPython repo under control and allow you to get faster response.
