### ISSUE TITLE
Difference from Github Markdown rendering

### ISSUE THREAD

**Issue by takluyver** [ipython/ipython#6118]
I'm opening this as an issue for discussion, but I'm not convinced that we should actually change anything. I'd especially like to get @fperez's input on it.

If you have GFM fenced code blocks, with something that's not a language name on the first line:

    ```\begin{align}

- Our current implementation treats this as part of the text, and renders it (monospace, unhighlighted) along with the rest of the block.
- Github's implementation treats it as an unrecognised language name, and doesn't render it.

@ellisonbg considers this difference a bug, and thinks we should match Github. On the other hand, changing it would break existing notebooks (including our own example "Typesetting Math Using MathJax").

I discovered this in PR #6028.

**Comment by ellisonbg** [comment]
@takluyver your original issue got sidetracked down a rabbit hole. do you think we need to do anything on this for 3.0?

**Comment by takluyver** [comment]
I don't. I think preserving the behaviour of existing notebooks is preferable to precise compliance with undocumented details of Github Markdown.

**Comment by dsblank** [comment]
There some things that could be documented related to this point, however. For example, what language names are supported after a triple back quote?

http://jupyter.cs.brynmawr.edu/hub/dblank/public/Jupyter%20Notebook%20Users%20Manual.ipynb#4.7-Including-Code-Examples

(This is no doubt an outdated list, as CodeMirror has been updated a few times since then).
