### ISSUE TITLE
Update example in custom.js

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#6403]
cf #6258 discussion, but decided to do later. 

Assigning to me.

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one. I chatted with @Carreau in person about it, and this was always just a minor chance of a race condition where jQuery is not loaded that it's not worth bothering to fix the example since many things have changed since then, and the notebook is only in maintenance mode now.

Thanks @Carreau and happy hacking! :bowtie:
