### ISSUE TITLE
Add priority attribute to tasks and execute high priority tasks first

### ISSUE THREAD

**Issue by kaazoo** [ipython/ipython#644]
It would be nice to give different tasks different priorities if they are all executed in a loadbalanced view. For DrQueueIPython, I group tasks together as jobs. Jobs can have different priorities, because it can be important to have the results of a small render job (for example a preview) before the results of a bigger long running job.
I haven't found any hint on this in the documentation, so I think this is a missing feature.

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one, since this is a feature request for parallel, and I just checked and it turns out someone else made the same request over at that repo: https://github.com/ipython/ipyparallel/issues/237

Thanks everyone and happy hacking! :bowtie:
