### ISSUE TITLE
notebook: plotting hangs in %debug mode

### ISSUE THREAD

**Issue by efiring** [ipython/ipython#6872]
It is useful to be able to plot variables inside a function after an exception is raised, using %debug, and this works with ipython from the command line.  I haven't been able to make it work inside the notebook (version 2.3), however, or using `qtconsole --existing`.  I tried on OS X with qt backend, and on linux with tk backend. The window is displayed but it hangs without ever drawing the plot. Example .ipynb file:

```
{
 "metadata": {
  "name": "",
  "signature": "sha256:e0a5c049bf1b161fcf2997fe6ff55c23b3a29badd44bea024af5f7b84b465152"
 },
 "nbformat": 3,
 "nbformat_minor": 0,
 "worksheets": [
  {
   "cells": [
    {
     "cell_type": "code",
     "collapsed": false,
     "input": [
      "#%qtconsole --existing\n",
      "%matplotlib qt"
     ],
     "language": "python",
     "metadata": {},
     "outputs": []
    },
    {
     "cell_type": "code",
     "collapsed": false,
     "input": [
      "import numpy as np\n",
      "import matplotlib.pyplot as plt\n",
      "\n",
      "def test():\n",
      "    xx = np.random.randn(10, 10)\n",
      "    raise Exception()\n",
      "    return xx\n",
      "    \n",
      "yy = test()"
     ],
     "language": "python",
     "metadata": {},
     "outputs": []
    },
    {
     "cell_type": "code",
     "collapsed": false,
     "input": [
      "# Try running \"plt.pcolormesh(xx)\" in debug mode:\n",
      "%debug"
     ],
     "language": "python",
     "metadata": {},
     "outputs": []
    },
    {
     "cell_type": "code",
     "collapsed": false,
     "input": [],
     "language": "python",
     "metadata": {},
     "outputs": []
    }
   ],
   "metadata": {}
  }
 ]
}
```

**Comment by ellisonbg** [comment]
We do have plans to build a full debugger that doesn't rely on `raw_input`, but that is going to be a longer term project.

**Comment by ccordoba12** [comment]
@ellisonbg Any draft of how that would work? And your estimated time frame? This is very important to us in Spyder and I'm planning to work on improving our debugger during the last part of the year.

**Comment by ellisonbg** [comment]
It would be a relatively significant effort that would require significant funding (probably $100-200k/year for a few years = a full time person) for us to move forward on. We really want to do this, but it will require talking to a lot of different stake holders and working with folks who are experts with debugger design. It is non-trivial because it has to work across all of the kernels we support and will involve a lot of time consuming UI/UX work. It also can't move forward until a lot of other frontend work is done (which will itself hold a global lock on our frontend for most of the next year).

High impact stuff, but but we simply don't have the resources to move this forward right now.

We will likely start to work on funding this type of thing later this year. Please let us know if you have any funding leads...

We will get there...just have to be patient...

**Comment by ellisonbg** [comment]
Oh forgot to answer the first part of your question. We will basically need to build the debugger into our message specification and then allow kernels to implement that part of the message spec to enable debugging. Thus, the main parts of this are:

1. Message spec design
2. Implementation of the debugging message spec by kernels.
3. Implementation of UI/UX for the debugger.

Again, all of this has to work across all 22 languages we support :)
