### ISSUE TITLE
Create Jupyter PyPI classifiers

### ISSUE THREAD

**Issue by blink1073** [ipython/ipython#6947]
At the very least we should have:

Framework :: Jupyter
Framework :: Jupyter :: Kernel

**Comment by ellisonbg** [comment]
@dsblank can we close our version of this issue?

**Comment by dsblank** [comment]
Sure, we will follow up on the progress and report back. 

It would be handy if someone from the Jupyter Project could give their endorsement to add the classifier over there at pypi so that we can start to tag kernels etc appropriately. We would like to build some tools that automatically list available kernels, etc, but it won't work until they are classified.

**Comment by ellisonbg** [comment]
OK I commented on the bitbucket issue, closing here.

**Comment by dsblank** [comment]
Thanks!
