### ISSUE TITLE
completer go below pager.

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#7134]
Should be fixable  by poppin the completer 'up' if too close from pager.

**Comment by douglas-larocca** [comment]
A related issue I'm having is that the completer goes "up" outside the viewport window. Here's a screenshot showing the full viewport, invoking the completer on `IPython.`.

![completer_dialog](https://cloud.githubusercontent.com/assets/5607827/7552116/f8b8b118-f670-11e4-8938-c3ff228ae58b.png)

I have some custom css going on but I don't think this the problem. IIRC the issue started after an upgrade but I didn't do anything about it at the time...

It's a minor annoyance but happens often because leaving edit mode moves the page so the top of the selected cell is flush with the top of the viewport. Sometimes I even guess ('probably third in the list...') to avoid reaching for the mouse!
