### ISSUE TITLE
Exceptions block engines with retries flag set

### ISSUE THREAD

**Issue by Zaharid** [ipython/ipython#7368]
Consider:
````python
from IPython.parallel import Client
c = Client()

def bad():
    raise Exception("?")
    
v = c.load_balanced_view()
v.set_flags(retries = 5)    
r = v.apply_async(bad)
````
When having a cluster with 4 engines, this will block the engines and never execute.

`c.queue_status()` will return forever:

````python
{'unassigned': 0,
 1: {'completed': 0, 'queue': 0, 'tasks': 1},
 2: {'completed': 0, 'queue': 0, 'tasks': 1},
 3: {'completed': 0, 'queue': 0, 'tasks': 1},
 0: {'completed': 0, 'queue': 0, 'tasks': 1}}
````

**Comment by minrk** [comment]
It will continue to resubmit the task until any one of:

- it succeeds
- retries are exhausted
- timeout is reached

is satisfied. The default timeout is forever, so it will stay in the queue forever. If you specify a timeout, the task will fail with the timeout reached.

It is not correct to say that it is blocking the engines, since the engines are not affected. Other work can be assigned while the failing task is waiting in the queue to be assigned to a new engine. It will not be re-assigned to an engine that has already failed to run it.

**Comment by Zaharid** [comment]
May I suggest documenting the fact that it will not retry in the same engine in here:

http://ipython.org/ipython-doc/2/parallel/parallel_task.html#retries

Also I can think of situations where it would be best to allow to retry on the same engine (such as when failure is non deterministic and dependant only on the task and the available engine number is small) or for debugging as in the example above.

**Comment by minrk** [comment]
Making the blacklist behavior optional is a reasonable request, we should consider it. I'll definitely document the blacklist behavior, thanks.
