### ISSUE TITLE
Output widget broken

### ISSUE THREAD

**Issue by jdfreder** [ipython/ipython#7509]
Caused by the grand asynchronous movement of 2014.  Specifically, the asynchronous code in the comm that calls back the user registered message handling function.

The output assumes (now incorrectly) that the widget custom messages are received by the front-end in the same order as the stdout/display messages. 

@takluyver @jasongrout :horse:

**Comment by jdfreder** [comment]
I marked this as a blocker since it doesn't make sense to ship a broken feature with IPython 3.0, especially since it's a new feature.

**Comment by takluyver** [comment]
From the dev meeting: @jdfreder will try reimplementing this so that the state change is on the kernel side, and the context manager causes output to be sent to the widget as comm messages. If that's not ready for 3.0 then we may pull output widgets out rather than trying to hack around the async issues.

**Comment by jasongrout** [comment]
+1 to redirecting stdout on the python side with totally self-contained code, at least until we understand much better how things should work in the core notebook with output and redirection and things.
