### ISSUE TITLE
Dashboard UI: it is not clear which button corresponds to which notebook

### ISSUE THREAD

**Issue by kmike** [ipython/ipython#7613]
Hi,

This is how a dashboard looks like now on a reasonably small window (less than 1200px wide):

![dashboard](https://cloud.githubusercontent.com/assets/107893/5933866/6cf75f08-a6e8-11e4-8a80-28474f542075.png)

I think that it is hard to tell which notebook will be deleted/stopped when you hover Delete or Shutdown buttons because notebook names are in far left.

Some ideas about how to fix it:

1. move buttons closer to text;
2. make the table less wide by default;
3. highlight the current table line.

(1) and (2) fix this particular issue better, but they have their own problems; (3) is less invasive.

**Comment by mathieu1** [comment]
This has been addressed since merging of #7505 (new UI). 

![New UI](https://cloud.githubusercontent.com/assets/3292874/5843785/ce28d610-a163-11e4-92bf-395469ac5fcf.png)

The only difficulty that remains is to see exactly which notebooks are running. There were some nice ideas (which I believe were somehow postponed in favor of more important discussions) like:
> One idea, which I hesitate to try, is to color the notebooks if they are running - maybe green.
> Another, use a different icon, like an open notebook or the logo of the kernel.
> Another, display a second icon, either or the left or right side of the row, which indicates the notebook is running. This icon could be the kernel logo, to additionally indicate what type of kernel is running.

To me having the kernel logo (or an open notebook icon in absence of a logo) would be a great indicator of a notebook "running".

**Comment by kmike** [comment]
Wow, thanks! It turns out my IPython master was outdated by ~16 hours, I didn't expect the issue to be fixed during this time :)

**Comment by Carreau** [comment]
> Wow, thanks! It turns out my IPython master was outdated by ~16 hours, I didn't expect the issue to be fixed during this time :)

Wow, 16h ago master is soooooo Yesterday :-)

Thanks for feedback though !
