### ISSUE TITLE
Multiline string looses the first 3 characters if that are dots

### ISSUE THREAD

**Issue by diarized** [ipython/ipython#7617]
iPython 2.3.1
```
In [97]: ss = """"aaa
   ....: ....
   ....: ...."""

In [98]: print ss
"aaa
.
.

In [99]:
```

**Comment by takluyver** [comment]
The reason is that IPython tries to handle code copied and pasted from an interactive prompt, like this:

```
>>> a = """
... 123"""
```

People often start selecting after the `>>>` prompt, so if the second line starts with `...`, it assumes that it's copied from an interactive session.

In IPython 2.x, it matches anything starting with `...`; #6027 made it a bit more specific, so that it matches `...` followed by either a space or the end of the line. That will make the example you gave work correctly in IPython 3.0.
