### ISSUE TITLE
content.js model.running in js ?

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#7634]
It seem right now that `contents.js` return wether notebook is running or not, and get the information from the server side. 

This is (a bit) problematic for drive, as we swap contents.js for our own, and `contents.js` is not supposed to get a handle on the `session` object.

Either contents should be giver  a handle on session, or drawing the notebook list should set `running`on model by itself.

**Comment by Carreau** [comment]
Wait, I'm mixing stuff with kernel list also. there seem to be 2 different logics...

**Comment by Carreau** [comment]
Ok, I'm starting to see how things works. 
though I have a question, when I rename a file in drive, how do I indicate to the corresponding session, that the file has been renamed ? Otherwise, the rennaming does not appear in the "running" tab, and I guess I need a handle on session to do that ...

**Comment by minrk** [comment]
@Carreau contents don't know anything about whether a notebook is running or not. Sessions are the only things that relate kernels to notebooks. Renaming a running notebook is two actions - update session and update the contents. If you rename with the UI in the notebook, it should take both actions. If you rename via other UI (e.g. on Google Drive), then the Session will lose track of the file because it hasn't been notified of the change.

**Comment by Carreau** [comment]
I rename through UI, and it does not take care of both. 
Maybe an exception get swallowed.
I'll continue to investigate.

**Comment by minrk** [comment]
@Carreau tree view or notebook page?

**Comment by Carreau** [comment]
rename through notebook page... haven't tried via dashboard.

**Comment by Carreau** [comment]
Ok, figured it out. Rename was actually renaming only `model.name` and not `model.path`everywhere. Which lead to inconsistent behavior. I'll close for now.

**Comment by minrk** [comment]
Yup, model.name should not have any effect anywhere, it's just a convenience alias for the last part of model.path.
