### ISSUE TITLE
Windows 7 64bit Chrome, can't enter Command mode on remote server

### ISSUE THREAD

**Issue by dpcuneowcg** [ipython/ipython#7636]
I'm new to IPNB on  and stumped by the fact, that I appear to always to be in the edit mode.
My cells are always Grey and hitting 'escape' or clicking off the cells has to notice-able effect.

If I click off the cells, to the extreme left, I can click and select cell lines of text while staying in the margins. It is my understanding that I should enter into command mode and that shouldn't normal behavior.

It's entirely possible that I'm missing something simple but this seems pretty straight forward.
local : Chrome Version 40.0.2214.91 m

server: Ubuntu Trusty 64-bit, IPython 3.0.0-dev

**Comment by minrk** [comment]
@dpcuneowcg does it work in an Incognito window, or other browser?

**Comment by dpcuneowcg** [comment]
Hi minrk, incognito mode was different but not entering command mode.

I realized another strange behavior present in the original enironment:
    The mark up cells appear as regular code cells.

In the "incognito" test, the markup cells did in fact, change appearance and become mark up.
After clicking on the mark up cell, the cell went into edit mode. I was able to make changes, but could enter command mode again. The markup cell remained, a grey-lighted box for editing.

I'm still wondering if I'm doing some wrong, I haven't had an example of a "working" instance. I've seen how IPNB should look when reading them on the web.

**Comment by takluyver** [comment]
To render a Markdown cell, you need to 'run' it - click inside it, and then press shift-enter, or click the play button in the toolbar. That was changed before IPython 2, so that you could have several markdown cells unrendered at the same time.

Rendered/unrendered is distinct from command/edit mode. In edit mode, you see a green border around the cell, and a pencil icon in the top right. In command mode, the border is grey and the pencil icon disappears. Is this what you see?

**Comment by dpcuneowcg** [comment]
markdown cell:
   When I shift-return, running the cell, it renders.

Double Clicking back inside the cell, I enter edit mode and can make changes.

If I'm in edit mode, pressing escape or clicking out of the cell, do not put me in command mode.

The reason I write that I'm not in command mode, is that none of the short cut keys work.

**Comment by takluyver** [comment]
OK, so it sounds like Markdown cells are behaving as expected.

The pencil icon isn't expected to change colour: the cell border changes colour, and the pencil appears and disappears. So it sounds like the problem is just that keyboard shortcuts aren't working. What specific keyboard shortcuts have you tried? E.g. `j` and `k` should move between cells, `a` and `b` should add cells above and below.

**Comment by dpcuneowcg** [comment]
Command line mode is working.

The line  number enable short I was using to test, does not work, possible colliding with the Chrome short cut   <ctr> L, to edit the URL bar.

The space bar short cut to scroll down works.

So the only issue I'm really having, is enabling the line numbers.

**Comment by takluyver** [comment]
Editing the URL bar should be `Ctrl+L`. Enabling/disabling line numbers is just the `L` key by itself. Shortcuts without Ctrl/Alt can be confusing, but they're nice when you're used to them.

**Comment by dpcuneowcg** [comment]
Everything works now. I didn't have any reference to tell what mode I was in and misunderstood the short cut help doc. Reminds me of the first time I tried VI. I'm not a a VI user if that's not obvious already.

Cheers

**Comment by takluyver** [comment]
Thanks. You're not the only one who's misunderstood the shortcuts, see the comments on #5531. We've not yet had a great idea for making it clearer that most of them don't need modifier keys.
