### ISSUE TITLE
NameError for defined variable

### ISSUE THREAD

**Issue by snapy666** [ipython/ipython#7672]
When I paste the following code in iPython..
```python
_memo = {}

def test(n, _memo=_memo):
    if n in _memo:
        return _memo[n]
        
    start = 0
    for i in range(start, n + 1):
        pass
    return b
```

I get..

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-4-465a7c5fb86a> in <module>()
----> 1 for i in range(start, n + 1):
      2         pass
      3 return b
      4 

NameError: name 'n' is not defined
```
Maybe I've overlooked something, but I can't see how that makes sense, as `n` is clearly defined here.

I'm on `Ubuntu 14.04 / 64bit`.

**Output of** `python3 -c "import IPython; print(IPython.sys_info())"`:
```python
{'commit_hash': '681fd77',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/usr/local/lib/python3.4/dist-packages/IPython',
 'ipython_version': '2.1.0',
 'os_name': 'posix',
 'platform': 'Linux-3.13.0-44-generic-x86_64-with-Ubuntu-14.04-trusty',
 'sys_executable': '/usr/bin/python3',
 'sys_platform': 'linux',
 'sys_version': '3.4.0 (default, Apr 11 2014, 13:05:11) \n[GCC 4.8.2]'}
```

**Comment by dsblank** [comment]
I think you have two problems:

1) When you "paste" into IPython (or Python for that matter) you have to make sure this is all in one "cell"... all at one In prompt. Try pasting this:

```python
_memo = {}
def test(n, _memo=_memo):
    if n in _memo:
        return _memo[n]
    start = 0
    for i in range(start, n + 1):
        pass
    return b
```

2) The second problem is that b is undefined.

**Comment by snapy666** [comment]
@dsblank Ahh.. thanks! So, no newlines allowed? Is this a limitation that can be removed from iPython? The current error message is also pretty weird, as it doesn't complain that `b` is undefined.

**Comment by takluyver** [comment]
In terminal IPython, a blank line means you're finished entering one bit of code, and it should go and run that. You can get round this by using `%paste` or `%cpaste` to paste a block of code.

It doesn't complain that b is undefined because it processes these lines as one chunk:

    start = 0
    for i in range(start, n + 1):
        pass
    return b

So it sees the undefined `n`, and stops before it gets the chance to notice that there's a problem with `b` too.

**Comment by ssanderson** [comment]
@snapy666 the reason you're not seeing the error about `b` being undefined is that you're not getting to that line. What's happening is that, when you paste your code into the REPL, it's as though you pasted each line one-by-one and hit enter after each line.  The problem that occurs is, because you've got a blank line in the middle of your function, the python interpreter assumes that that function is done, so you end up executing the equivalent of:

```
_memo = {}

def test(n, _memo=_memo):
    if n in _memo:
        return _memo[n]

# Note that we're no longer in the function, which means the name `n` isn't bound to anything.
start = 0
for i in range(start, n + 1):
    pass
return b
```

As @dsblank notes, you can fix this particular issue by pasting the text with no blank lines.  However, a cleaner solution is to use `%paste`, which copies the content of the clipboard in a way that's aware of the above quirks.

**Comment by ssanderson** [comment]
Gah, @takluyver you beat me by 20 seconds.

**Comment by snapy666** [comment]
@takluyver @ssanderson I mean the compacted version of @dsblank where it doesn't throw an error message regarding `b`.

**Comment by takluyver** [comment]
Then it's inside a function, so there won't be an error until you call the function. And if you define `b` globally in the meantime, the function call will succeed too.
