### ISSUE TITLE
Output widget issues. 

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#7698]
Widget outputs not stored in notebook format anymore. 

Example of beating frequency does not work the same for 2 reasons : 

1 - `<audio controls=\"controls\" >` not in ipynb anymore. 
2 - `f1, f2 = v.children`raise as `v` has 3 childrens: `f1`, `f2` and `out`.

**Comment by minrk** [comment]
@jdfreder did output widget outputs used to persist in the document, or am I crazy? If this is the expected behavior of an output widget, we should revert the change that puts interact in an output widget.

**Comment by jdfreder** [comment]
I'm pretty sure at some point in time they did get saved.  I feel like I've implemented the output widget a couple of times now.  At first I thought #7523 introduced the regression, but it looks like the implementation prior to that was also bugged.

**Comment by minrk** [comment]
@jdfreder what do you want to do with respect to 3.0? I don't think we should let interact output get lost. Would you rather revert the change that put interact in an OutputWidget, or make sure OutputWidget outputs aren't ethereal? I would be okay if OutputWidget outputs were treated like the rest of the widgets, but I don't think that should apply to `@interact` outputs.

**Comment by jdfreder** [comment]
Ah I remember what happened.  Widget persistence complicates things.  If you refresh the page, the output widgets will be recreated.  If you are also collapsing all the output widgets into the cells output, you'll see a duplication of outputs.  Also collapsing all the output widgets is non-trivial since children can be stored in any List traitlet (not just `children`).

I think when we decide on a way to persist the widget state to the disk, we can revisit the idea of using output widgets with interact.  Until then, https://github.com/ipython/ipython/pull/7703
