### ISSUE TITLE
%load_ext julia.magic doesn't seem to work on Windows 

### ISSUE THREAD

**Issue by stonebig** [ipython/ipython#7750]
It would be nice to have it back, as it would allow a complete WinJuPy experience.

**Comment by Carreau** [comment]
This is probably not the place to fill that as the extension is not part of IPython.
It should probably be reported to https://github.com/julialang/pyjulia

**Comment by stonebig** [comment]
probably ?

2015-02-11 21:47 GMT+01:00 Matthias Bussonnier <notifications@github.com>:

**Comment by Carreau** [comment]
> probably

Probably in the sens that last time I checked the julia magic was part of PyJulia and I wasn't sure it still was, but apparently [it is](https://github.com/JuliaLang/pyjulia/blob/master/julia/magic.py#L80-L82), so I would report the issue there.

The magic is also only a think wrapper around PyJulia, so if the magic don't work on windows it is probably not due to IPython or the magic, but PyJulia not working on windows. So the issues is between Julia and Python regardless of wether you use IPython or not.

**Comment by stonebig** [comment]
Le mainteneur côté Julia ne touchera jamais à Windows: tu étais mon dernier
espoir.


2015-02-11 22:06 GMT+01:00 Matthias Bussonnier <notifications@github.com>:

**Comment by Carreau** [comment]
The problem is my knowledge of Julia, windows and Python C api are really limitted, and the intersection of the 3 probably null. Don't loose hope.

**Comment by stonebig** [comment]
never
https://github.com/JuliaLang/pyjulia/pull/33
