### ISSUE TITLE
_repr_png_ vs _repr_html_

### ISSUE THREAD

**Issue by senyai** [ipython/ipython#7899]
```python
class A(object):
    def _repr_html_(self):
        return "<h1>_repr_html_</h1>"
    def _repr_png_(self):
        raise Exception("No")

A()  # raises exception
```
I don't understand why `_repr_png_` is called when nevertheless HTML representation is always used.
('commit_hash': u'f75fda4')

**Comment by takluyver** [comment]
All the reprs are generated, because there might be multiple frontends receiving the data which prefer different reprs, and in a notebook, alternative reprs might be useful when converting the notebook to another format.

If you need a `_repr_*_` method which may not be able to return something, you can have it return None, IIRC.

**Comment by senyai** [comment]
I see now. Thanks for your clear answer. Even though I don't like this solution as image object I have can have at least `jpeg`, `png` and `html` representation, and each representation takes time to generate. I'll stick to `_repr_html_`.

**Comment by minrk** [comment]
@senyai some projects choose to have a config value to specify which representations to produce, so that `_repr_png_` might check something like `if not self.png_enabled: return None`. Then you can define all the representations you may want, but only compute the ones you actually want to see at a given time.
