### ISSUE TITLE
Switch 32bit and 64 bit python in Ipython notebook

### ISSUE THREAD

**Issue by thoo** [ipython/ipython#7980]
Hi , 
I can successfully run `arch -32 /System/Library/Frameworks/Python.framework/Versions/2.7/bin/python -m IPython` to get 32bit python on my Mac os x. I also tried to install  `arch -32 /System/Library/Frameworks/Python.framework/Versions/2.7/bin/python setup.py install` under ipython folder. But I don't know how to execute `ipython notebook` so that it will launch 32bit python. I am using 64bit anaconda python on Mac. Thanks,

**Comment by minrk** [comment]
Setting the arch is a per-process thing. It has no real effect at install time. Probably the easiest way to set the bit-ness of Python is with the environment variable:

    export VERSIONER_PYTHON_PREFER_32_BIT=yes

with that set, any Python process in the same environment will run in 32 bit mode.  

However, you cannot use 64b Anaconda in 32b mode, because it's 64b-only.

Why do you need 32b Python?

**Comment by thoo** [comment]
@minrk  I tried to use pyvisa and it only works with 32bit python on my Mac. Eventually I decided to go with canopy 32bit. I might try to switch back and forth with canopy and anaconda. Thanks,
