### ISSUE TITLE
nbconvert to rst won't embed images.

### ISSUE THREAD

**Issue by rainwoodman** [ipython/ipython#8063]
--to html seem to embed images, but also generate files in _files directory.
--to rst won't embed the images.
running pandoc on the html will produce an rst that embeds the images.

Affected Version: 2.3.0.

**Comment by takluyver** [comment]
The rst, markdown and latex converters all extract the images to separate files and put references to them in the file, as this is the normal way of including images in these documents. Only for HTML do we generate a single file with the images included inline, because it's much more common to view HTML in a web browser than to look at the raw code.

If you want rst/markdown with images embedded in base64 image tags, it should be possible to write your own exporter to do that. I don't think we're going to support it.

**Comment by rainwoodman** [comment]
I see. I thought it might be great to have something like
```
ipython nbconvert --embed
```
for a consistent interface. but this surely isn't anything of high priority.

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository.  This will allow to keep the number of opened issue on the IPython repo under control. 

Feel free to keep commenting or reopen if necessary.

Thanks.
