### ISSUE TITLE
notebook: make it possible to print the keyboard shortcuts

### ISSUE THREAD

**Issue by jankatins** [ipython/ipython#8141]
Currently it is not possible to open the keyboard shortcuts in a new window and trying to print it in the current window will print the text on top of the underlying cells, making it unreadable. :-(

**Comment by jcb91** [comment]
@Carreau I've made something which provides this as part of an extension in ipython-contrib/IPython-notebook-extensions#347. It's a little convoluted, since the `quickhelp` module doesn't export much, but seems to work ok. If it'd be helpful, I'd be happy to port this into the main `quickhelp` module (say a button to expand to fullscreen, or something).

**Comment by jcb91** [comment]
although I guess it should go to jupyter/notebook really...

**Comment by Carreau** [comment]
@jcb91 if you want to expose more/refactor feel free to send PR. 
You can close issues cross repo by saying `close ipython/ipython#8141`. I guess with the current work on phosphor, help can be just another panel.

**Comment by jcb91** [comment]
Righto, I'll knock something together. Ooh, ok, I haven't heard about phosphor before. I wasn't really sure what to google, I just get information about actual chemical phosphors (doh!). @Carreau, could you recommend somewhere I can find out about it?

**Comment by Carreau** [comment]
http://phosphorjs.github.io/ I have to dig into it too.

**Comment by jcb91** [comment]
great, thanks!
