### ISSUE TITLE
%matplotlib notebook: issue with mpl.rc_context

### ISSUE THREAD

**Issue by cel4** [ipython/ipython#8222]
I noticed a weird behavior of `%matplotlib notebook` compared to `%matplotlib inline`:

This is my example notebook with 3 cells:

```
%matplotlib notebook
import matplotlib.pylab as plt
import matplotlib as mpl
```

```
with mpl.rc_context():
    plt.hist([1,1,2,3,4], bins=4)
```

```
plt.hist([4,3,2,2,1], bins=4)
```

The plotting code in the third cell plots into the interactive figure of the second cell and the log shows the error message below:

```
[IPKernelApp] ERROR | No such comm: 22a56780552d410d9f4c61e62f6d8813
[IPKernelApp] ERROR | No such comm: 22a56780552d410d9f4c61e62f6d8813
```

**Comment by minrk** [comment]
Plot commands continuing to go to the current figure is the intended behavior of the nbagg backend (which is part of matplotlib, not IPython). I'm not sure about the comm logs, though.

**Comment by jenshnielsen** [comment]
The comms error is triggered when a figure is closed an believe that it is a bug on the matplotlib side. It seems to happen because we don't close the connection on both the python and javascript side. We should fix that but at this stage the error is relatively harmless. 

@minrk is right. You should expect the nbagg backend to mimic a GUI backend and not the inline backend. New plot lines are added to an old figure unless you explicitly create a new figure using plt.figure() etc.

**Comment by cel4** [comment]
Oh okay, thanks for clarification. Does not seem to be a real issue then.
