### ISSUE TITLE
iPython Notebook won't run b/c it requires tornado >= 4.0 but I have 4.1

### ISSUE THREAD

**Issue by pmdaly** [ipython/ipython#8249]
ImportError: The IPython Notebook requires tornado >= 4.0, but you have 3.1.1

Anyone know how to fix this?

**Comment by takluyver** [comment]
Is 4.1 installed in a different version of python, perhaps?

**Comment by matthiaskoenig** [comment]
Had the same problem:
I had tornado installed via apt-get and pip:

sudo apt-get remove python-tornado
sudo pip install tornado

**Comment by duccoder** [comment]
You can solve with upgrade tornado:
```
sudo pip install tornado --upgrade
```

**Comment by SrinivasRG** [comment]
I had this problem too.  matthiaskoenig's suggestion worked for me.

**Comment by remram44** [comment]
Oh god, please don't "sudo pip install" things, like, ever. These are very bad recommendation. You probably broke everything when you did it the previous time, you can try and fix it with your package manager (`apt-get reinstall ...`), using pip again will just f*ck it up even more.

You can [learn about virtualenv here](https://virtualenv.pypa.io/en/latest/).

As for the IPython issue I think there's nothing to be fixed here so it can be closed.

**Comment by takluyver** [comment]
`sudo pip install tornado` isn't a great idea, but in all likelihood it won't cause serious breakage. The reasons to avoid using `sudo pip` are:

- If you install newer versions of modules that system stuff depends on, that system stuff might be broken. e.g. at one point, installing a newer version of `requests` broke pip on Debian systems. This probably isn't an issue for tornado, as not many system components depend on a web framework (yet).
- Python packages aren't as trusted as Debian packages, so you shouldn't install them as root. This is true, but on a single user machine, making a special effort to protect root is [kind of ridiculous](https://xkcd.com/1200/).

If you've done `sudo pip install ...`, later doing `sudo apt-get reinstall ...` won't change anything: apt installs into `/usr`, pip into `/usr/local`. Apt will reinstall its files, and the files pip installed will still be there, and still take precedence. If you want to undo `sudo pip install ...`, you should `sudo pip uninstall ...`.

Virtualenv is handy when you want to test out different versions of things, e.g. to test the development version without overwriting your install of the stable version. But for day to day work, I don't bother with them. Instead I use `pip install --user ...` which installs packages in my home directory.

**Comment by matthiaskoenig** [comment]
I assume you know what your are doing by installing things via pip, i.e. executing
`sudo pip install tornado` 
If you want a clean environment only for certain projects use a virtual environment or something like docker. 
I am on a multiple user system and wanted to provide a working version of ipython for all users. The pip install did the trick for me.

**Comment by laf72** [comment]
I am also having this issue when I try to run jupyter notebook.  somehow jupyter notebook spontaneously uninstalled, and I cannot run my new notebooks as they're in the new format.

**Comment by minrk** [comment]
@laf72 this Issue is about having the wrong version of the tornado library. Is that what you are seeing? Do you know what version of IPython you were using before you upgraded? What do you see from `pip list` or `conda list` (depending on which you use)? Can you share a notebook that you are unable to open?

**Comment by laf72** [comment]
I had tornado version 4.2.1.  I reinstalled jupyter with anaconda and the issue was resolved.

**Comment by takluyver** [comment]
Closing as I think this was confusion with multiple versions installed, rather than a bug.

**Comment by DSLituiev** [comment]
I got in this problem most probably after installing a bunch of dependencies for matplotlib. Ubuntu14.
Running suggested 

```
sudo apt-get remove python-tornado
sudo pip3 install -U tornado 
```

does not help. The version is `tornado-4.3` which is obviously >=4.0.

**Comment by DSLituiev** [comment]
upd: though `sudo apt-get remove python-tornado` had no effect, manual cleansing helped:
`sudo rm /usr/lib/python3/dist-packages/tornado`

**Comment by remram44** [comment]
```
sudo rm /usr/lib/python3/dist-packages/tornado
```
Oh my god.

**Comment by minrk** [comment]
This is a known and relatively common bug in setuptools seen on Linux. Setuptools can create a file called `easy-install.pth`, typically in `/usr/local/lib/pythonX.Y/dist-packages/easy-install.pth`. Bugs in setuptools can cause it to add `/usr/lib/pythonX.Y/dist-packages` to this file, corrupting the sys.path priority. The result being that apt-installed packages end up being imported, no matter what else has been installed in a higher priority location. If you see `/usr/lib/.../dist-packages` in easy-install.pth, this is the bug and the line should be removed from the .pth file.

The bug has since been fixed in setuptools, I believe, so it should only be an issue if you are using (or have ever used) outdated pip/setuptools. One thing to be sure of: make sure you always have up-to-date setuptools and pip. Even if you have installed them with apt, the *very first thing* you should do is `pip install --upgrade setuptools pip`.

**Comment by takluyver** [comment]
Also, @DSLituiev : your apt command was working on the Python 2 version of the package, which is why it had no effect on Python 3. To remove Tornado, try this instead of manually removing the folder:

```
sudo apt-get remove python3-tornado
```

**Comment by sukhjitsehra** [comment]
solved by removing python-tornado  and then re-installation using  
```pip install tornado```

**Comment by haoyuanliu** [comment]
sudo pip install tornado --upgrade
Use --upgrade to update your tornado version!

**Comment by raheelqader** [comment]
sudo apt-get remove python3-tornado
then 
sudo pip3 install -U tornado

worked for me
