### ISSUE TITLE
Autosave "messing" with File Permissions

### ISSUE THREAD

**Issue by LightServant** [ipython/ipython#8322]
Hello,

after upgrading to iPython Notebook 3.1 I realized that the autosave functionality of the notebooks broke my owner rights on my notebooks stored in my companies network storage (netapp).
I'm running the notebook server from my MacBook (OSX 10.9.5). Our IT-department sais that OSX can show the file permissions on the network, but if it tries to change it, it destroys these rights.

I can reproduce the behavior. If i create a clean notebook and save it, all is fine. But as soon as the autosaved tries to create a new checkpoint, all permissions are gone and I can't even read the notebook anymore.

I realize this is not a ipython notebook bug in the first place, but it can lead to severe dataloss and I don't see why ipython should try to change owner rights when creating checkpoints at all. At least it seems it does

kind regards
Markus

**Comment by takluyver** [comment]
It's the atomic save mechanism - in order to avoid corrupting a file if e.g. the disk gets full mid-write, we actually save to a new file, try to copy the permissions from the old file, and rename the new over the old.

Myeh. I guess we need a mechanism to switch back to regular save, but that's horrible because it leaves it up to the user to understand the issue and change the setting. I wish we had a better way to do this.

**Comment by Carreau** [comment]
I suppose we want  a "disable atomic save" feature backported to 3.x

**Comment by rlabbe** [comment]
I will note that I have a lot of notebooks in Dropbox, and dropbox and autosave are 'fighting'. Sometimes I end up with warnings from the notebook that the notebook 'changed', other times I end up with extraneous folders named as 'name.ipynbrandomcharactershere'. Not sure if that is dropbox making the folder or IPython. More than once I've accidentally added those folders into my git repository.

**Comment by takluyver** [comment]
IPython makes those as temporary files, but in normal situations they will be immediately renamed to replace the notebook file you're saving. Something Dropbox is doing is keeping copies of them around.

I hate this situation because it's a feature we added to fix a horrible, albeit rare, user experience - losing a notebook because of a failed save. It turns out that the fix makes things worse in other important use cases, but we have no reliable way of telling when these use cases are happening.

We could use `/tmp` (or platform equivalent) for atomic save, and fall back to regular non-atomic save if that's not on the same filesystem as the directory we're saving too. That would improve things for Dropbox and similar sync tools, but it would still clobber the permissions in @LightServant's case. And it would be extra complexity, so it might cause extra problems.

**Comment by Carreau** [comment]
does dropbox save dotfiles ? can we make the atomic name start with a `.` or a `_` to have dropbox not sync them ?

**Comment by rlabbe** [comment]
yes, it syncs all of my .gitignore, etc files. Not really a big deal for me; my pain point is git add, and a regular expression in .gitignore will solve this problem for me.

**Comment by Carreau** [comment]
https://www.dropbox.com/en/help/145

``` 
Temporary files

When some applications (such as Microsoft Word, Excel, or PowerPoint) open a file,
they will often save a temporary file in the same directory and name it in one of the
following ways:

Name begins with ~$ (a tilde and dollar sign) or .~ (a period and tilde)
Name begins with a tilde and ends in .tmp, such as ~myfile.tmp
Dropbox does not sync these temporary files on any operating system.
```

**Comment by takluyver** [comment]
OK, so we can resolve it for Dropbox. Perhaps that's good enough?

A quick search doesn't turn up any similar info for Google Drive, and a few people from a couple of years ago were complaining that it *does* sync MS Office temporary files.

**Comment by Carreau** [comment]
[Here](https://github.com/shazow/unstdlib.py/blob/master/unstdlib/standard/contextlib_.py#L14) is something that we might want to consider that also implement atomic operation on files.

**Comment by takluyver** [comment]
That looks broadly similar to what we're doing, but it users predictable
names for the temporary files, which probably makes it a bit nicer with
syncing systems.

**Comment by LightServant** [comment]
Maybe there is a way to check the file-system of the storage folder? Knowing the OS one could include a list of "compatible" filesystems which support changing of file-permissions and just omit the "chmod" oder system equivalent in the unsupported cases?

**Comment by takluyver** [comment]
I don't know of a good or cross-platform way to check what filesystem a folder is on (parsing the output of `mounts` is a way that's neither good nor cross platform), I don't want to get into blacklisting/whitelisting filesystems, and it still might not be sufficient information (e.g. for an NFS mount, it might depend on the remote system). And it doesn't tell us about sync tools that might be running on that directory.

I'll bring it up at our next weekly meeting to see if anyone has any more inspiration.

**Comment by takluyver** [comment]
I just went to add one of those prefixes to the name to hide it from Dropbox, and found that we're using temporary directories now instead of temporary files, since #7469. And those patterns only appear to work to make it ignore files, not directories.

**Comment by takluyver** [comment]
jupyter/jupyter_notebook#67 does atomic saving a different way, which I think might be more robust.

**Comment by tritemio** [comment]
For reference here there is a related issue:
#8270

**Comment by Carreau** [comment]
Atomic saving is now done differently and should handle that.
