### ISSUE TITLE
Class attributes are shown regardless of __dir__ override 

### ISSUE THREAD

**Issue by patter001** [ipython/ipython#8330]
For some user interactions I'm trying to limit what the tab completion options are. I have implemented a `__dir__`, and dir(object) has the expected results. However, the tab completion still shows functions from the class -- inherited from a parent class.

I tried adding a `@classmethod` `__dir__` and I tried adding `__dir__` to the parent class, but neither one seems to help -- though..the `@classmethod` feels like it should have...and that might either be a python bug or "not a supported feature" :)

**Comment by minrk** [comment]
This is the result of `dir2`, which explicitly looks for class attributes in addition to the output of `__dir__`, so it's not a bug per se, but behaving as intended. Whether it *should* behave that way is a different question.

@takluyver thoughts on what we should do about giving objects control over their own completions?

**Comment by takluyver** [comment]
The default `__dir__()` method does return class attributes (including attributes of parent classes) as well as instance attributes, which makes me think that it should be up to code implementing `__dir__()` to show those if they want to - i.e. most implementations should do something like `return super().__dir__() + [...]`.

On the other hand, we presumably add the class attributes explicitly because at some point something didn't provide those from `__dir__()`. I don't know if that was an obsolete version of Python or some library, or if it would still be an issue if we changed it now.

**Comment by mortada** [comment]
Interesting to see this thread because I was about to ask the same question. We are trying to limit the tab complete options dynamically for `pandas` `Series` (details in this PR https://github.com/pydata/pandas/pull/9910) 

Basically some of the attributes are only valid if the `Series` contains the appropriate data type (`Series.str` only works if it has strings, `Series.dt` only works if it has datetimes), so we'd like to get the tab completion to reflect that. However to our surprise removing the items from `__dir__` does not remove them from the tab completion.

**Comment by Carreau** [comment]
OTOH, it should not be to the library to mess with completion, the
completer should be smart enough to know things like that. (I guess that
what types are for) and I doubt __dir__ is only use for completions.

**Comment by takluyver** [comment]
I'd lean slightly towards saying that `__dir__` is informative, not definitive, so it's OK to use it to hide methods that you're sure are not relevant, like `s.str` for a non-string series. Off the top of my head, I can't think of anything other than completions that uses `dir(obj)`.

If we don't want to recommend that, though, then I think we should support a separate hook that objects can override to provide an informative list of attributes e.g. `_completions_dir_`. But my preference is to use `__dir__` for that rather than making a new mechanism.

**Comment by patter001** [comment]
Should I move this to some feature request bucket? or would it be ok to submit a pull request with this change?

**Comment by takluyver** [comment]
I'll bring this up at the dev meeting today.

**Comment by takluyver** [comment]
The conclusion was that the code fetching extra attributes can go away, and we should trust what we get from `__dir__()`. Do you want to make a pull request? I can do it if you don't want to.

**Comment by mortada** [comment]
@takluyver that's great news, thanks! 

@patter001 if you don't do the PR, I'd be happy to do it.

**Comment by patter001** [comment]
Ok, PR created...Build #11929....

I have to admit though...it was a small edit that I made in my fork directly. I had some odd unrelated install issue with "traitlets.config.application" when trying to install the head in my virtual environment.

**Comment by patter001** [comment]
Sorry, the more relevant link would be: PR8355 - https://github.com/ipython/ipython/pull/8355

**Comment by takluyver** [comment]
That's OK - we've just split the repository up into multiple pieces, so installation is a bit tricky for the time being. It will get easier as we make releases of the separate pieces.

**Comment by patter001** [comment]
Sounds good. Thanks for the quick merge!
