### ISSUE TITLE
Cancelling a paste operation in ipython console

### ISSUE THREAD

**Issue by tarlabs** [ipython/ipython#8334]
Recently while working with iPython, I wanted to paste some code and by mistake copied a file with 40K lines of code. When I pasted, it kept on processing each line as syntax error, but CTRL + C didn't work and there was no way to cancel that paste operation.

Is it possible for iPython to somehow handle such thing and allow a user to cancel a bad paste operation?

**Comment by Carreau** [comment]
This is most likely handled by readline/your terminal , which we don't have control over, so I doubt there is anything we can do about that. 

Basically from IPython point of view there is no difference between getting 40k line of code in 1ms, or having you type it at the prompt.

**Comment by takluyver** [comment]
I assume you mean you pasted it directly into the terminal with `Ctrl-Shift-V` or something similar, not using `%paste`. In that case, I'm pretty sure we can't do anything about it, because there's one of two possibilities:

1. Ctrl-C is queued behind the input going through the pty, so it won't even send the SIGINT until the input has finished.
2. It sends SIGINT immediately, bypassing the input buffer, but that only gets you a new prompt, and then the input carries on.

I'm not sure which it is, but in either case I don't think we can do anything about it.

**Comment by tarlabs** [comment]
So nothing like a series of say 10-15+ continuous syntax errors within few ms and we take no more input and ask user if we need to gulp all upcoming input till the buffer ends?

**Comment by takluyver** [comment]
I don't think there's a practical way to ask the user to confirm anything when stdin is still being flooded with incoming input. And even if there was, we can't stop that input coming through, though not trying to run it might make it go through a bit faster.

In general, I'm very wary of trying to guess what the user is doing and behave differently based on that guess, even when it's technically possible to do so. It makes the software more complex, less predictable and harder to test.

I remember using a website that prevented me from copy-pasting values into an HTML form (because computers can't be trusted, I guess) by timing how quickly successive characters were entered. My normal typing speed, which is nothing remarkable, was enough to make it think I was using the clipboard, so I had to force myself to type slowly to stop it resetting the field. This type of interface is very hard to do well, and utterly infuriating when done badly.

**Comment by tarlabs** [comment]
I agree @takluyver 

Is it the same case with %paste? Do we read all the clipboard text in one go? or we process it line by line

**Comment by takluyver** [comment]
With `%paste` we can get the clipboard text much more efficiently and process it in one go. I don't know at what size it will start being awkward, but it will certainly be much better than pasting through the terminal.
