### ISSUE TITLE
Jupyter terminal does not support input method

### ISSUE THREAD

**Issue by yuyichao** [ipython/ipython#8360]
The terminal does not seems to be a input context and therefore does not support input method.

**Comment by Carreau** [comment]
I think you will have to be a bit more descriptive of what terminal you are talking about and what you are trying to achieve.

**Comment by yuyichao** [comment]
Well, the terminal is what's available in the drop down menu from the new button on the main page.

Input method is, well, input method. It's the way to input non-ascii characters in many languages.

**Comment by yuyichao** [comment]
Or probably a better way to describe it here is that the terminal I'm talking about is the page availabe at url `*/terminals/2`

I'm not sure how exactly browsers handles input methods but I guess the distinction is like the difference between typing words and using hotkeys.

I'm not sure how / how hard it is to implement this but it seems that [`pypy.js`](http://pypyjs.org/) privides a similar interface and support input methods.

**Comment by Carreau** [comment]
Ah, but it was not obvious to me that you were speaking about the terminal in the terminal, 
it could have been the pure `ipython` terminal, or `ipython console`, which using 2 process zmq, or even the qt console.

And yes, we know it has limitation for this , which are (in part) due to browser limitation and keyboard handeling, (like example on french keyboard I cannot type pipe (`|`)) we will do our best, but this will mostly get better if issues are fixed upstream in [`term.js`](https://github.com/chjj/term.js)

**Comment by yuyichao** [comment]
Ahh, right. I guess I could have meant that....

I see. It seems that `pypy.js`  is using jq-consoles. Not sure which one is better (since I've never used any of them....)

**Comment by takluyver** [comment]
Looking at jq-console, I don't think it implements the right level of abstraction for us, unfortunately.

I think this is an issue with term.js - there's not much we can do in IPython about something like this.

**Comment by yuyichao** [comment]
Ok, will report ti term.J's later if ut haven't been done already.

Is this also the case for #8361 as well?
