### ISSUE TITLE
force remove read-only flag from ipynb or save the changes in new ipynb

### ISSUE THREAD

**Issue by denfromufa** [ipython/ipython#8368]

**Comment by koenvb** [comment]
Could you clarify a bit more the problem you are facing?
Any example code so I can try to reproduce the problem?

Thanks!

**Comment by denfromufa** [comment]
This is how you can reproduce this big problem:

1. Create ipynb, some content, save and close.
2. Change the file access to read-only flag.
3. Open the notebook and add some extra content.

At this point the extra content :
* cannot be saved in existing file (even if read-only flag is removed while
notebook is open).
* cannot be transferred to a new notebook (make a copy option in File menu).
* cannot be downloaded from File menu option.

So the extra content is LOST.

**Comment by koenvb** [comment]
Was playing around with it on Mac Os X and understand the problem here.

* It kind of mentions that you are opening in read only mode in a subtle way
* BUT if you close the notebook you wont see any message saying nothing has been saved.

Bad thing is that I managed to get my notebook in a state where:

* File is write enabled 
* Notebook does not mention anything 
* I can NOT save the notebook as it mentions "Checkpoint failed"

I created an issue for that https://github.com/ipython/ipython/issues/8380

This seems to be related to the new saving mechanism mentioned in

* https://github.com/ipython/ipython/issues/8323
* https://github.com/ipython/ipython/issues/8322

**Comment by denfromufa** [comment]
my workaround https://github.com/ipython/ipython/issues/8323#issuecomment-349198496

closing this one in favor of: https://github.com/jupyter/notebook/issues/1324
