### ISSUE TITLE
Strange behavior with >>>  in notebook

### ISSUE THREAD

**Issue by amitsaha** [ipython/ipython#8377]
Hi all,

This code runs fine in my notebook:
```
#P18: Fahrenheit to Celsius conversion
>>> F = 98.6
>>> (F - 32) * (5 / 9)
```
However, the following errors out:

```
#P18: Fahrenheit to Celsius conversion

>>> F = 98.6
>>> (F - 32) * (5 / 9)
```

Error:

```
File "<ipython-input-27-f226e36e82b1>", line 3
    >>> F = 98.6
     ^
SyntaxError: invalid syntax
```

I am using ipython-2.3 on Fedora 21.

**Comment by rsmith31415** [comment]
The error is caused by the line after your comment. Remove that line and your code will run fine. Remember to use `from __future__ import division` to obtain the intended division of 5/9.

This is also happening in master.

**Comment by amitsaha** [comment]
@rsmith31415 i forgot to mention this is Python 3. Did you mean the "blank line" ?

**Comment by rsmith31415** [comment]
@amitsaha Correct. Python 2.7+ and Python 3 behave the same here.

**Comment by takluyver** [comment]
I know this seems odd, but this is the expected behaviour. Allow me to explain.

The reason IPython ignores `>>> ` is so that you can easily copy and paste examples that have the interactive prompts in. But ignoring part of the code the user gives is a tricky game - what if you wanted to write code like this:

```python
a = """
>>> YOU WIN <<<
"""
```

Try it - the `>>> ` that was supposed to be in the string goes missing. There's no 100% accurate way to tell whether those characters at the start of the line are what the user intended, or just the way an example was presented. So whatever we do is a guess. And the compromise we have is that if either of the first two lines in a cell appears to have a prompt, we guess that you've copied and pasted a code example, and we strip the prompts. If not, we assume that you really meant to type those characters.

Why the first two lines? Because with a code example like:

```python
>>> for a in range(5):
...     print(a)
...     print(a**2)
```

Some people will copy from the initial `>>> `, and some will leave that out and copy from the `for`. Either way, they both get the `... ` on the second line.

I know this probably seemed bizarrely inconsistent when you ran into it, but that's the pitfall of trying to make interfaces that are clever about this kind of thing. If you've read this far, thanks for making it worth my time to write this far. ;-)

**Comment by rsmith31415** [comment]
Nice explanation, but I was wondering, what are the pitfalls of using the rule "If there is a block comment or inline comment, ignore it" and start processing after that part. You are already throwing an error if there are nested comments, so that rules out the issue of parsing nested patterns with regex. 

The interesting thing is that the console is doing the right thing:

```
In [1]: #P18: Fahrenheit to Celsius conversion

In [2]: 

In [2]: >>> F = 98.6

In [3]: >>> (F - 32) * (5 / 9)
```

**Comment by takluyver** [comment]
Each `In [x]:` prompt at the console is equivalent to a new cell in the notebook. If you run that code as a single block using `%paste`, you'll see the same thing.

**Comment by rsmith31415** [comment]
You're right, I see the same error. 

If the whole block is being processed, then it is probably not a good idea to spend much time writing some positive lookbehind assertion to deal with this.

**Comment by amitsaha** [comment]
Thanks @takluyver  for the explanation. It does make sense why I am seeing this behavior. 

Thank you @rsmith31415 too.
