### ISSUE TITLE
Python 2.7 Tutorial Conflicting behavior with WeakValueDictionary.

### ISSUE THREAD

**Issue by crispybacon** [ipython/ipython#8403]
https://docs.python.org/2/tutorial/stdlib2.html
**Section 11.6. Weak References**

The example code below from the python tutorial suggests that the value of 'a' is not persistent when cast into a WeakValueDictionary as entry 'primary'

The value persisted in the dictionary after 'a' was deleted and garbage collection had been called.  I did not see a bug report for this already, forgive me if there was one already put in.  

**The weakRef Dictionary functions as expected within the standard Python shell.**

    import weakref, gc  
    class A:  
        def __init__(self, value):  
            self.value = value  
        def __repr__(self):  
            return str(self.value)  

    a = A(10)                   # create a reference  
    d = weakref.WeakValueDictionary()  
    d['primary'] = a            # does not create a reference  
    d['primary']                # fetch the object if it is still alive  

    del a                       # remove the one reference  
    gc.collect()                # run garbage collection right away  

    d['primary']                # entry was automatically removed

**Comment by Carreau** [comment]
IPython does (among other Things) keep an history of input and output in `_,__,___,In[..], Out[]` so it si likely that one of this is keeping a reference to `a`, hence it's not gc'ed as you expect. 

If you pass the above block of code as once the REPL, it behave as expected, which hint for history.

I would expect a `del _,__,___, Out` to work, but apparently it does not, so there might be one more object keeping a ref.

**Comment by takluyver** [comment]
It's also stored as e.g. `_3`, matching the `Out [3]` prompt number. If you use the [`%xdel`](http://ipython.org/ipython-doc/3/interactive/magics.html#magic-xdel) magic, like `%xdel a` instead of `del a`, it should delete all the references IPython is keeping.

This does make some bits of code behave a bit differently from a standard Python shell, but it's useful enough that I don't see it changing. As far as I know it's unusual to use weak references in interactive use.

Closing accordingly - we can reopen if people disagree.

**Comment by graphicore** [comment]
I'm collaborating in writing an application that uses the `weakref` module in it's implementation of the observer pattern. I'd also like to add Ipython as a direct python scripting interface to that application at some point in the future. Without having any proof yet, I think this behavior of Ipython may become problematic.

Here is just a thought: Why not use `weakref.ref` to store objects in `In` and `Out`? You could unwrap the objects again when returning them from e.g. `Out[4]` etc. So the expected behavior would not change.

If `weakref.ref` can't do it's thing it throws a `TypeError`, also for weakref objects. So you must remember if you made the weakref that you put on the stack or not. Like this:

```python

# in the setter
try:
    Out.append((true, weakref.ref(value)))
except TypeError:
    Out.append((false, value))

# in the getter
wrapped, value = Out[index]
return value if not wrapped else value()
```
