### ISSUE TITLE
ipython notebook dead kernel bug

### ISSUE THREAD

**Issue by potatochip** [ipython/ipython#8447]
iPython notebook kernel dies if there is a file called 'tokenize.py' in the same directory as whatever notebook file you are trying to load.

**Comment by takluyver** [comment]
`tokenize` is a standard library module we use. If, when we try to import that, Python finds a different module instead, it dies. That's true of any module we import.

There are some ways we could get round this for things in the current working directory, but:

1. They're hackish, and would either require special-casing Python or forcing other kernels to jump through extra hoops for no good reason.
2. You still wouldn't be able to use your `tokenize` (or whatever) as a module, because Python expects each module name to be used only once.
3. Naming Python files like standard library modules is a bad idea anyway.

So sorry, you just need to rename your file.

**Comment by potatochip** [comment]
Ugh Python always takes the good names
