### ISSUE TITLE
Support readline in the IPython Notebook editor

### ISSUE THREAD

**Issue by brianmingus** [ipython/ipython#8466]
When writing code in the Notebook it would be really nice to have readline.

I have implemented a small proof-of-concept here: https://jsfiddle.net/uLz4cjbL/2/

This small implementation of Ctrl+a/e in a textarea should generalize to IPython Notebook, which uses divs and pres, since the underlying mousetrap library takes an arbitrary function.

If this enhancement is implemented I would be able to do serious work in IPython Notebook, so comments appreciated. 

Other aspects of this issue include:
- readline / emacs shortcuts
- readline / vi shortcuts
- history (kill ring / yanking / undo / redo)

**Comment by Carreau** [comment]
I'm not quitesure what you mean by "having readline". The library we use for text edition is codemirror and support a lot of [keymaps](https://codemirror.net/doc/manual.html#keymaps) including vi, emacs shortcut, undo, redo, and extension for killring, and is even more feature rich; highlighting, multicursor, etc... 

What more do you want ?

(note that I don't see any difference in your demo than in any other texarea)

**Comment by brianmingus** [comment]
My textarea demo supports Ctrl+a/e (tested in Chrome only).

It could be the case that my Notebook editor was not using CodeMirror, as I installed IPython Notebook from source on Ubuntu.

**Comment by takluyver** [comment]
I don't think we should override Ctrl-A, which already means something that people are generally used to. In general, we don't override any Ctrl shortcuts, because it almost always conflicts with something in the browser. The only exception we make is Ctrl-S, because browser save is not very useful on a notebook.

If you want to customise the shortcuts for your own use, that should be possible. @Carreau probably recalls the details of how to do that better than I do.

For an advanced example of customising keyboard shortcuts, see [ipython-vimception](https://github.com/ivanov/ipython-vimception).

**Comment by brianmingus** [comment]
CodeMirror supports emacs-like editing (with a couple of notable exceptions): https://codemirror.net/demo/emacs.html

One user added the following to ~/.ipython/profile_default/static/custom/custom.js

`require(["components/codemirror/keymap/emacs"],
     function (emacs) {
         to('emacs');
         console.log('emacs.js loaded');
     });`

But this doesn't work for me.

Whether a code editor should support standard emacs / vi shortcuts as the vast majority of users will expect is a no-brainer. I will submit a patch allowing you to choose emacs / vi from the menu once I figure out how to get it working.

**Comment by brianmingus** [comment]
I found a similar issue https://github.com/ipython/ipython/issues/2319

The suggestions in that issue do not work for me.

**Comment by brianmingus** [comment]
Since I found https://github.com/millejoh/emacs-ipython-notebook I have no need of using the web editor anymore, so I am switching to that.

**Comment by Carreau** [comment]
> Ctrl+a/e

Oh, that's because Ctrl+a/e are bount to beginning/EOL already for all text-area on Os X

I've started to write [http://carreau.gitbooks.io/jupyter-book/content/keyboardshortcut.html](http://carreau.gitbooks.io/jupyter-book/content/keyboardshortcut.html) some exampleon how to add keyboard shortcut, this might not target codemirror yet. What you do is ok, but after you need to tell codemirror to use emacs.
