### ISSUE TITLE
Using an undefined Python variable in a shell magic converts all variables to environment variables

### ISSUE THREAD

**Issue by audy** [ipython/ipython#8526]
(Sorry if this is a duplicate. I did my best to find a pre-existing issue).

I recently ran into this issue which caused my some confusion. When I use an undefined Python variable within a shell magic using `$`, IPython will silently convert all variables to environment variables (which may be undefined).

```python
a = 1
!echo $a
# $a is a Python variable, 1 is printed

!echo $a $b
# $a and $b are now environment variables, nothing is printed

%env b=2

!echo $a $b
# both are environment variables, 2 is printed (a is empty)
```

The current behavior is (a) replace shell variables with Python variables if and only if all of the variables are defined in Python (b) otherwise, use shell variables. This makes things very difficult to debug even though I am now aware of it.

I have some proposals for alternative behaviors:

1. Warn the user if some, but not all, of the `$` variable names match Python variable names.
2. Be strict about using Python variables and raise a `NameError` and/or use different syntaxes for Python and environment variables

**Comment by Carreau** [comment]
See https://github.com/ipython/ipython/issues/8492 among other, agree difficult to find for background. 

The observed behavior is due to a more complex mechanisme. 1) is not possible, or relatively difficult to do as we already use the fact that a NameError will be raised to decide wether or not to expand to shell variable. 2) is not possible because people rely on current behavior.

**Comment by audy** [comment]
> 1) is not possible, or relatively difficult to do as we already use the fact that a NameError

Why not raise some other error then?

> 2) is not possible because people rely on current behavior.

Why not keep this open and fix it in a major release? Also, adding a warning shouldn't break anyone else's code.

I feel like you were a bit quick to close this issue. Would it help if I came back with a PR to raise a warning?

--austin

**Comment by takluyver** [comment]
I'm not convinced that warnings are appropriate - I use `$VAR` to mean environment variables more often than Python variables, so I don't want to see warnings whenever it can't find a Python variable.

We recently looked into making the variables independent, so that if it failed to interpolate one, it could still interpolate others in the same command. But it turns out that that's hard because of the API that formatters expose, so I don't think it's worth the extra complexity.

**Comment by Carreau** [comment]
1) well because raising an error is not what people expect. `%cd $HOME` should'nt raise anything even if HOME is undefined. 

Following the above link would have brought you to https://github.com/ipython/ipython/pull/8494, which is in progress, but is much more hairy than expected. You can try to get things right, but I would expect the code to be a significant refactor of IPython. And there si another issue opened somewhere where the proposal is to make the Python variable expansion optional on a per magic basis (which is a even larger refactor).

The changing the behavior of such a fundamental syntax on IPython, even just changing it in a major release will piss of a lot of people. 

Though if you can comme up with a sensible fix we can consider it.
