### ISSUE TITLE
Do >3.0.0 source archives include git submodules?

### ISSUE THREAD

**Issue by durack1** [ipython/ipython#8591]
As noted on the [3.0.0 release page](https://github.com/ipython/ipython/releases/tag/rel-3.0.0) the standard github "Source code" *.zip/*.tar.gz archives didn't include git submodules.. Is this issue still apparent with the [3.1.0](https://github.com/ipython/ipython/releases/tag/rel-3.1.0) and [3.2.0](https://github.com/ipython/ipython/releases/tag/rel-3.2.0) tagged releases?

If yes, is it possible to provide hosted archives which do include these?

**Comment by minrk** [comment]
GitHub source links use `git archive`, which does not support submodules. We have asked GitHub for the ability to remove these links, since they are confusing to people, and we have no control over them. You can get a 'full' source version of IPython, either [on PyPI](https://pypi.python.org/simple/ipython/) or [archive.ipython.org](http://archive.ipython.org/release).

**Comment by takluyver** [comment]
And we've stopped using submodules for 4.0, so this won't be a problem for much longer.

**Comment by durack1** [comment]
@takluyver can you confirm that for [4.4.0b1](https://github.com/ipython/ipython/releases/tag/rel-4.0.0b1) these should build directly from the github tarballs? So git submodules are no longer an issue..?

**Comment by Carreau** [comment]
Regardless of wether the github tarball works or not, we cannot assure you that will be the same as sdists. Please use official release channels to get the code. 
-- 
M
