### ISSUE TITLE
Look at switching to Jedi for completion machinery

### ISSUE THREAD

**Issue by takluyver** [ipython/ipython#8606]
Our current completion machinery is relatively old and brittle. I've been meaning to refactor it, but I've realised that the Python completion library *Jedi* has [support for completing in REPLs](https://jedi.readthedocs.org/en/latest/docs/plugin-api.html#jedi.api.Interpreter). We can probably use that and get rid of our own completion machinery entirely.

One minor concern is performance: I tried using jedi-vim at one stage, and found it slowed the editor down quite a bit. Hopefully it's better now.

I'm interested in looking into this post 4.0.

**Comment by minrk** [comment]
Yeah, I've heard a number of issues about jedi being slow, and requiring anything that interacts with it to do some async handling, which isn't a good fit for readline. It might be something we can handle better with prompt toolkit, though, so something to keep in mind as we try that.

I think if we can make any completions that IPython provides plugins to jedi, that would probably be an improvement for everyone.

**Comment by takluyver** [comment]
@davidhalter: We're looking at using Jedi for completions in IPython. A couple of questions:

1. IPython has some extensions to Python syntax (e.g. `%magics`, `foo?` help). Is there a way to extend Jedi to accommodate these?  

2. We have some concerns about the speed of completions. Our current completion machinery is pretty basic, but it's usually close enough to instant that the user doesn't notice any delay. How quick is Jedi? How much leeway do the configuration options give us to adjust performance?

Thanks!

**Comment by davidhalter** [comment]
@takluyver 
Sorry to delay this for a week. I was on holidays.

1. I guess controlling the exensions won't be a big issue, since you can just put a function in front of the Jedi calls to handle the extensions accordingly. 

2. Giving you a precise specification of how fast Jedi is, tends to be hard. Jedi is definitely optimized for speed and queries that take longer than 200 ms are worth a bug report. However, while most queries are really fast (< 50ms) you will have slower queries, especially after warm-up (generating the caches) and within extremely large codebases. 

Jedi has a ton of optimizations to make completing Python fast, among them:

- A lot of caches (imports, modules, call signatures and a lot them to improve the speed of just one completion)
- A parser that only parses parts of files when they are modified (probably doesn't improve the speed for REPL completions). 
- In REPL completion Jedi falls back to the default Python logic for REPL completion when possible.

However, I expect Jedi to be slow especially when loading new modules. Doing completion async would solve that. Jedi will just be slow on certain occasions. I don't expect Jedi to be fast always. I'd rather have something that either stops Jedi when taking to long or even better is async. However that would require IPython to have an async REPL completion implementation as well.

Let me know if you need to know anything else.

**Comment by takluyver** [comment]
Thanks for this info! We're also looking at moving to prompt_toolkit, so async may be possible even in the terminal. We'll probably play around with jedi in a couple of months and ask you more specific questions as they come up.

**Comment by Carreau** [comment]
This is now partially addressed, as jedi is now use for (part of) our completion. Though we do not make full use of Jedi API (and we need some bugs to be fixed in Jedi). I'm going to bump that to 6.0 as we should start to stabilize 5.0

**Comment by takluyver** [comment]
I'm closing this. We looked at it and did it. I don't like vague 'do something more with this' issues lingering for future releases. We can open new issues for specific things we want to do.

**Comment by davidhalter** [comment]
@carreau let me know if you need certain specific bugs fixed.

**Comment by Carreau** [comment]
@davidhalter Nothing urgent, just for new feature, we would like to have the type of each completion, but it tend to [alway return `module` (jedi/#713)](https://github.com/davidhalter/jedi/issues/713) when using the `Interpreter` completer. 

I also need to push forward my knowledge of the Jedi API before knowing exactly what we want, so for now I'll push IPython 5.0 forward, and will consider improvement to completion for 6.0
