### ISSUE TITLE
Non explicit local import

### ISSUE THREAD

**Issue by Mrngilles** [ipython/ipython#8655]
I think I found a place in `utils.text.py` where there is a non explicit local import https://github.com/ipython/ipython/blob/master/IPython/utils/text.py#/L66 
Can you confirm this so that I can place a PR to fix it?
Thanks

**Comment by takluyver** [comment]
That is actually a global import, of [path.py](https://pypi.python.org/pypi/path.py). However, it is broken under Python 2, because it tries to do an implicit local import from `IPython.utils.path` instead, which fails.

We should use `from __future__ import absolute_imports` at the top of that file to fix it. Do you want to make a PR doing that? If you could also add a test that would have caught the problem (in `IPython.utils.tests.test_text`), that would be great.

**Comment by Mrngilles** [comment]
Of course, I will make a PR. As for the tests, I am no sure exactly what to test. Should I test that we import the good package? Or that we are not importing the local package? I am not sure exactly.

**Comment by Mrngilles** [comment]
Pull request done #8656

**Comment by ssanderson** [comment]
@takluyver @Mrngilles looks like this can be closed?

(Happened to notice while scanning issues).

**Comment by Carreau** [comment]
Thanks for noticing. Closing.
