### ISSUE TITLE
Kernel dies unexpectedly

### ISSUE THREAD

**Issue by clearf** [ipython/ipython#8678]
Hi, 
I'm having a problem where my kernel consistently dies and restarts at a certain point in my notebook. 

There is no debugging information that I can see anywhere, only:

    [I 10:15:47.625 NotebookApp] KernelRestarter: restarting kernel (1/5)
    WARNING:root:kernel 1186a28c-f408-401d-9f3e-ebdef9273ba3 restarted

The crash usually happens while trying to read a particularly large dataset from disk. This is sometime successful, though, in which case the crash happens during subsequent attempts to manipulate that dataset. I'm not sure if I'm running out of memory? 

I also have an iPython parallel instance running at the same time (otherwise my ``%px --local`` commands don't work), but there is only one node and it's not doing any calculation.

I don't believe it is due to a timeout, as I've upped the time_to_dead to no effect

    import IPython as ip
    ip.config.get_config()['MappingKernelManager']['time_to_dead']
> 600

Version:

﻿﻿* pyzmq (14.7.0) (installed via pip but built from source)
* zeromq-4.1.2 (built from source)
* ipython: both 3.1.0 and 3.2.1

Would love some pointers on debugging this.

**Comment by minrk** [comment]
What happens when you run the same code in a plain terminal IPython or a regular Python script?

**Comment by clearf** [comment]
In [163]: model_analytics.add_metadata()

>  Killed: 9

So  I guess this implies it's not iPython notebook. Any suggestions on how to further debug?

**Comment by minrk** [comment]
Out of memory's definitely  possible. Such things should be caught and turned into MemoryErrors in Python, where possible. This may be a bug in pandas. I'd bring it up with them. You can get some debugging by running a regular Python script that reproduces the error with gdb.

**Comment by clearf** [comment]
Great, thanks.
–C

**Comment by kylepolich** [comment]
Hi Jupyter team, just a quick suggestion for you.  This page is the top Google result for the query "juypter notebook kernel died unexpectedly".  Since many people probably find their way here on searches like that, it would be great if this page had a comment directing people to the canonical page to help users debug down to the myriad of likely causes of this error.

**Comment by Haythamamin** [comment]
**IN:** `pd.read_table(filename, sep='|', encoding='utf_8', quoting=3, error_bad_lines=False) `
**OUT:** ```
C:\Users\user\AppData\Local\Continuum\Anaconda2\lib\site-packages\IPython\core\interactiveshell.py:2717: DtypeWarning: Columns (1,51) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
```

**IN:** `pd.read_table(filename, sep='|', encoding='utf_8', low_memory=False, quoting=3, error_bad_lines=False) `
**OUT:**```
[I 10:15:47.625 NotebookApp] KernelRestarter: restarting kernel (1/5)
WARNING:root:kernel 1186a28c-f408-401d-9f3e-ebdef9273ba3 restarted
```

Pandas 0.20.1 

The issue is triggered by size of data file to be imported.
