### ISSUE TITLE
delivering ready-to-use ipython notebooks in packages

### ISSUE THREAD

**Issue by nealmcb** [ipython/ipython#8683]
I'd like to package an application which uses an IPython notebook as the UI.  For convenience I'd like the whole application to be in the package, rather than having to provide an ipynb file alongside the package to be installed in a different location.  But I'd like the user to be able to fire it up and get a notebook interface, in a manner analogous to the the "-m" option to ipython for running a module out of a package.

E.g., if the package is named "mypackage", they could run something like

    ipython notebook --ipynb mypackage.myinterface.ipynb

and get the myinterface.ipynb notebook somehow extracted from the package and pre-populated in the server, or perhaps written into the local directory before the notebook is started up.

The details of command-line options and the syntax for naming the files are just suggestions.   I imagine this could be implemented using the pkg_resources features of setuptools and the egg format, but I don't know the details.

Or perhaps there is already some way to do this or get close to it?

**Comment by minrk** [comment]
The most logical place for this kind of thing is distutils `data_files`, which typically end up in `sys.prefix/share`. Unfortunately, it's not strictly reliable as a destination because distutils doesn't record where it puts files. It is probably fine in all cases one actually cares to support, though.

An extra wrinkle for things like that, though, is that docs shouldn't be mutable, and often aren't (e.g. `sudo pip install`). We do plan to address this with a sort of copy-on-open way for packages to specify "my docs are here" and the notebook can open them in a special way that doesn't attempt to edit the files in their original home, but that doesn't exist yet.

**Comment by takluyver** [comment]
It should be possible to have your own script that locates a notebook in package data, and launches the notebook server for it. To find the location, use:

```python
import mypackage
mypackage.__file__
```

Closing as I don't think we're likely to do anything on this; and if we do the relevant repo is now jupyter/notebook.
