### ISSUE TITLE
restart notebook server

### ISSUE THREAD

**Issue by denfromufa** [ipython/ipython#8685]
Is there any way to restart notebook server from notebook interface, i.e. without access to remote terminal?

Also I installed terminado, but still terminals are unavailable.

'Windows-2012Server-6.2.9200'
'3.4.3 |Anaconda 2.2.0 (64-bit)| (default, Mar  6 2015, 12:06:10) [MSC v.1600 64 bit (AMD64)]'
IPython.__version__ = '3.0.0'

**Comment by takluyver** [comment]
From a notebook, you could run `!ipython notebook` to start a new server, and come up with some command to stop your existing server. There's nothing in the interface to restart the server.

Terminals aren't available on Windows.

**Comment by denfromufa** [comment]
is this limitation of terminado or underlying ipython infrastructure?

**Comment by takluyver** [comment]
Limitation of terminado, but it's really hard to do that on Windows. There's a fairly minimal, simple interface on Unix called a pseudoterminal or pty, which communicates between the terminal emulator and the program running in the terminal (like bash). That makes it fairly easy to have a different terminal emulator, which is what we're doing here. On Windows, terminal programs have to call [console API functions](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682073.aspx), which makes it much harder to provide a separate console interface.

Oh, and I should have been clearer: terminals aren't available if the notebook server is running on Windows. If the server is running on a Unix machine, you can use its terminals in the browser on a Windows machine.

**Comment by denfromufa** [comment]
How about mintty? It can be used without cygwin under MSYS + MinGW.

https://github.com/mintty/mintty

**Comment by takluyver** [comment]
That is trying to do the same thing, and it has [major issues](https://github.com/mintty/mintty/issues/56) when used with native Windows (non cygwin) programs. Notice how that issue is tagged 'Difficulty: Insane' and 'Priority: None'. I have little interest in opening that can of worms.

That issue discussion also describes the creation of [winpty](https://github.com/rprichard/winpty), which is, I think, the kind of thing we'd need to get it working. But... "Winpty requires two g++ toolchains." That's not the kind of thing I want to end up debugging.

We've asked some people at Microsoft about the possibility of having a pty-like interface as part of Windows. But I'm not holding my breath.
