### ISSUE TITLE
IPython Truck Factor

### ISSUE THREAD

**Issue by gavelino** [ipython/ipython#8710]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **IPython** and obtained a value of **4**.

The developers responsible for this TF are:

MinRK - author of 41% of the files
Thomas Kluyver - author of 23% of the files
Brian Granger - author of 19% of the files
Jonathan Frederic - author of 16% of the files

To validate our results, we would like to ask **IPython** developers the following three brief questions:

(a) Do you agree that the listed developers are the main developers of **IPython**?

(b) Do you agree that **IPython** will be in trouble if the listed developers leave the project (e.g., if they win in the lottery, to be less morbid)?

(c) Does **IPython** have some characteristics that would attenuate the loss of the listed developers (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by takluyver** [comment]
Hi Guilherme - thanks for looking into this, it's really interesting. I imagine @emilienschultz will also be interested in the results.

I'm curious how exactly you calculated the TF - from the percentages you give, it looks like we have a TF of 2: Min and any one other of those people add up to >50% of the files.

a) We're certainly some of the main developers. The project is expanding rapidly at the moment, so there's a different (larger) pool of people who are major contributors today than the statistics you've gathered, which show more of a historical picture.

b) I don't think winning the lottery would stop us doing what we do ;-). Losing those four people would certainly have an impact on the project, but I don't think it would be fatal - again, this is due to the growing set of major contributors. Some parts of the project would suffer more than others - for instance, IPython.parallel is something Min knows much better than any of the rest of us.

c) Compared to other open source projects, we have funding - from academic grants and gifts from companies. All four of the people you listed are paid to work on the project, along with a number of others. So if the four of us took off, the project would hire some more people. Of course, that doesn't make it a non-issue: it would take some time to find the right people, hire them and get them up to speed with the project, especially with a big chunk of the core team gone. But I think it would happen.

I guess we should make sure the four of us never cross the road together!

**Comment by rgbkrk** [comment]
> I guess we should make sure the four of us never cross the road together!

We've done it before. :fearful:

**Comment by Carreau** [comment]
I'm curious of what files where included, especially if you take into account the js-component directory that was checked-in at some point in time in the repository, then you will get a huge bias in the number of files, as you basically count a high number of files that are just vendorized libraries.

Typically : https://github.com/ipython/ipython/pull/3232

with 830 files changed 24000 addition, 10000 deletion, is probably not really relevant. (@ellisonbg author here), though I doubt this particular example would change Brian position in the project. Yes you speak about removing vendorized libs, I'm just curious in feb 2015, what language would have IPython be detected as. 

Also I for example had some PR that would change 1 line across all files (update copyright). But does should not make me part of the contributor to a file. (I guess taken into account in the DOA calculation). 

It feel strange to see @fperez with lower that 16% of authorship on files. 

Is the script that determine authorship availlable somewhere ? I would like to run-it on subpart of the tree. 

Otherwise seem relatively coherent.

**Comment by minrk** [comment]
There's one major shortcoming that comes to mind for git-based metrics for something like Truck-Factor, and it's that the developers who implement refactors are over-credited with authorship. I think this is a particular challenge in IPython, which has undergone an awful lot of refactoring, the majority of which has been by the four individuals you list above. That said, the developers who do the refactors tend to be those most familiar with the given piece of code. If not in the beginning, they can be by the end. Some of these refactors are just moving files around (e.g. the recent Big Split), which doesn't require looking at the files, but can inappropriately reassign credit to the renamer.

How are you accounting for 'authorship of files'? There are relatively few files that are actually 'written' by a single developer, and most would probably claim at least two 'main authors'.

You might also consider weighting files differently, based on some metric of importance. I have no idea how to do that in practice, but I probably get undue credit 'for IPython' from my work on IPython.parallel, which is a lot of lines and files, but is really not core functionality for many users of IPython (and part of why it is in its own repo now), whereas contributions to IPython/core/interactiveshell.py are super important to every IPython user.

Other metrics could include non-code participation, such as mailing-list and GitHub comments.

On to your actual questions:

> (a) Do you agree that the listed developers are the main developers of IPython?

On the ipython/ipython repo, yes, though I would add Matthias Bussonier who is the expert on many pieces of the code. There are several other developers working on IPython- or Jupyter-related projects, such as nbgrader, nbviewer, etc. who are critical to those pieces, so it depends a bit on what you mean by 'IPython'.

> (b) Do you agree that IPython will be in trouble if the listed developers leave the project (e.g., if they win in the lottery, to be less morbid)?

If *any* leave or *all*? I think it would definitely be in trouble for a while if we all left at once. However, there are a lot of enthusiastic and capable developers coming into the project right now, who I think would be able to fill voids left by any, if not all of us. I think this goes to the fact that many of us work on different pieces of the project, and none of us work on everything. For instance, of the four listed, Jon definitely has the most expertise on the interactive widgets. That said, Jason Grout and Sylvain Corlay and others have been doing a lot of work with Jon on widgets, and I would trust them to fill that void in time. I think most aspects of IPython are well enough understood by at least a couple of developers, including those outside the listed group, that it would survive. Some more obscure aspects would likely stagnate, such as IPython.parallel.

> (c) Does IPython have some characteristics that would attenuate the loss of the listed developers (e.g., detailed documentation)?

The funding is definitely key. If we left while there is still funding, people can be hired to learn the code, rather than in their free time. I would say that our documentation is nowhere near where it needs to be to enable someone to become a new core developer upon the sudden departure of existing core devs. However, it is our hope to be able to get closer to that with the funding we currently have.

I would also say that the popularity of the project, and the fact that it is a tool for developers, attenuates the Truck Factor a bit. Many of the users of IPython have the necessary skills to pick up development of IPython, and could step in if the need arose. This has happened once before, when Fernando was the only core developer and stopped being able to work on it, Ville Vainio stepped in as maintainer for quite some time. There are also quite a few core and non-core developers who have contributed to, if not been 'primary authors' on, IPython, who can be called upon.

**Comment by Carreau** [comment]
Side note. We often joke that @minrk  is in fact 5 peoples, according to above statistics he is "Only" 1.8 time @takluyver or 2.56 times @jdfreder. :-)

**Comment by minrk** [comment]
I should also mention that Brian and Fernando do a *huge* amount of non-code work, without which none of us would have the jobs we currently do working on IPython. We have mentioned the funding above, but without them spending their time pursuing that funding and collaborations with various organizations instead of coding, the rest of us wouldn't have the freedom to spend all of our time writing code.

**Comment by michaelaye** [comment]
As git offers the functionality, one could also try this by counting the 'ownership' of git-blame lines, no?

**Comment by minrk** [comment]
@michaelaye that's exactly what the refactors tend to misrepresent. I'm considered 'author' of a lot of code that I actually just moved from one place to another. But it's definitely a better metric than giving authorship of a whole file to a single user, which is not at all representative of how development occurs.

**Comment by ellisonbg** [comment]
I think that git commit logs are meaningful, they just don't have the
meaning they appear to on the surface. It is meaningful that someone has
done huge refactorings of the code base - but not in a lines of code sense.

On Thu, Aug 13, 2015 at 1:43 PM, Min RK <notifications@github.com> wrote:

> @michaelaye <https://github.com/michaelaye> that's exactly what the
> refactors tend to misrepresent. I'm considered 'author' of a lot of code
> that I actually just moved from one place to another. But it's definitely a
> better metric than giving authorship of a whole file to a single user,
> which is not at all representative of how development occurs.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipython/issues/8710#issuecomment-130834747>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by Carreau** [comment]
Closing as this is not really an issue, feel free to continue commenting.
