### ISSUE TITLE
Automatically export notebook to .py upon saving: simpler solution

### ISSUE THREAD

**Issue by Teodormz** [ipython/ipython#8715]
There was the issue https://github.com/ipython/ipython/issues/8009 discussed on this topic.

For us this is actually less convenient than having --script command. I have a team of people, every one runs their own installation of Anaconda on their machines (similarly to as if you have your own installation of Eclipse, VS, compilers, etc.: very reasonable).
Asking them to add the lines to ipython_notebook_config.py is more burdensome than asking them to run notebooks with --script option by default. Also, not all the notebooks need to be converted to .py, the ones which aren't shared are good the way they are.

Do you have a simpler solution? Can you not deprecate the --script option please?

**Comment by Carreau** [comment]
The `--script` has been deprecated in 2.x , that is to say since February stable release. It has been removed since long before. It is still present, but will be removed. We cannot not-deprecate as it is already deprecated in a stable version. 

The post-save-hook is strictly more-powerful that `--script`, and if you have your own package that do whatever you can use `ipython notebook --FileContentsManager.post_save_hook='your.own.module.with.post.save.hook'`

It take less than 5 minutes to create a local package that get the functionality, and shouldn't take more than 5 to make a module that does that on PyPI. 

Then you just ask your users to pip-install it. And you can even programatically set up the post-save in the json config file. 

So we will most likely not un-deprecate. 

If you want to have your own package with a post save-hook, we can help you to set it up though.
