### ISSUE TITLE
Documentation links to latest versions

### ISSUE THREAD

**Issue by techtonik** [ipython/ipython#8772]
IPython docs don't have links to latest version of documentation:
https://ipython.org/ipython-doc/rel-0.10.2/html/api/generated/IPython.OInspect.html

Read the docs has an awesome feature of linking all versions - take a look at the enu at the bottom right:
https://django.readthedocs.org/en/1.7.x/topics/db/queries.html

**Comment by Carreau** [comment]
Latest version is on [read the doc](http://ipython.readthedocs.org/en/stable/), where did you find the link to 0.10.2 ? (so that we can update it) 

I have no objection on re-publishing the previous version on read the docs, but someone need to take the time to do it. 

I think there is a problem with RTD which refuses to detect our tags and publish both a **latest** and and **stable** tags for the docs, but again someone would need to investigate. 

Thanks !

**Comment by techtonik** [comment]
Third link in search results - https://www.google.com/search?q=oinspect

![image](https://cloud.githubusercontent.com/assets/515889/9513568/2ead1a0a-4c9a-11e5-8023-f6fdb1c153b7.png)

**Comment by Carreau** [comment]
Gahhhhh why the hell 0.10.2 and not latest....

Thanks.

**Comment by techtonik** [comment]
Because it is better linked on the web. One of the solutions is to upload all versions to readthedocs and place a redirect there from https://ipython.org/ipython-doc/rel-0.10.2/*

**Comment by takluyver** [comment]
Closing to centralise discussion on #8785.
