### ISSUE TITLE
ggplot plots do not appear in ipython console when executing .py source

### ISSUE THREAD

**Issue by ActionPace** [ipython/ipython#8784]
I am running Anaconda ipython version 3.2.0

When I create ggplots interactively in the console the plots appear inside the ipython console
When I execute a .py source file, they do not appear

I don't have this problem with matplotlib and since this is not the ipython notebook so %matplotlib inline does not apply here

Please advise,
Thanks

Later note: I can't figure out how to change width of bars in barplots and the distance between the bars (It seems some options are missing in geom_bar (like width).. I am moving on to plotting in matplotlib via pandas and seaborn.. but if there are some solutions (or things that I am missing here, I'd like to continue to use ggplot if possible)

**Comment by tacaswell** [comment]
This should probably be reported against https://github.com/yhat/ggplot.

In all cases, you are plotting with `matplotlib`, it is just a matter of which API you are using.

**Comment by ActionPace** [comment]
Thanks

I did report it there first and they transferred it here.

Is there any other test I can do such as seeing if it works in a standard python shell? I suspect it would create a separate window but it might prove or disprove something (perhaps?)

**Comment by takluyver** [comment]
I'm not exactly clear what you're doing. You may have to use some kind of explicit `show()` call when running a script to show the plots. I don't know whether ggplot exposes that itself, or you should just call matplotlib's show directly.

Closing for now as there hasn't been activity for months, and I don't think it's a bug in IPython. We can always reopen if it turns out that it is.
