### ISSUE TITLE
%%writefile ignores '>>>' at the beginning of lines

### ISSUE THREAD

**Issue by petrposik** [ipython/ipython#8791]
If I write the following in the code cell:
```
%%writefile test.txt
>>> fact(5)
120
```
I expect that the text after the %%writefile magic will be present in the text file literally. Instead, only the following is found in the textfile:
```
fact(5)
120
```
IPython probably first filters out the '>>>' string and then passes the result to the cell magic function.It behaves like this in both the notebook, and in the IPython console.  I do not think this is the expected behavior.

**Comment by Carreau** [comment]
o_O thanks for the report. 

Not sure what can be causing this.

**Comment by Carreau** [comment]
@takluyver, this seem to be the input transformers that strips `>>>` before converting %-ish syntax to a `get_ipython().<function call>`.

I'm not sure how to fix as `classic_prompt()` is ment to strip the prompt if `>>>`  appear in one of the first 2 lines (which obviously appear to be the case here). 

And obviously a pasted magics where we start selecting from after the first prompt make sens.

Could `classic_prompt()` yield transformed line, only if all the lines after the `initial_re` match `prompt_re` ?

**Comment by takluyver** [comment]
> Could classic_prompt() yield transformed line, only if all the lines after the initial_re match prompt_re ?

Not really. We have this complex system of transformers handling things line by line so that in a console environment, it can decide after each line whether input is complete, and it should execute, or incomplete, and it should prompt for another line.

We could alleviate this particular case by saying that if the first line begins with `%` or `!`, it must be IPython syntax, so `classic_prompt()` should ignore the rest of the cell. But you'd still have the same problem using writefile if the next line started with `In [1]: `.

Trying to guess what the user means is hard!

**Comment by Carreau** [comment]
I keep seeing this pattern: When we remove users from the equation  90% of all our bugs are solved :-P (10 remaining % being JS, unicode and windows)

**Comment by takluyver** [comment]
See #9144, which should make this a bit smarter. I've actually done it for IPython prompts when inside a cell magic as well.
