### ISSUE TITLE
autoreload and package causing TypeError

### ISSUE THREAD

**Issue by nidleo** [ipython/ipython#8807]
Please see my question here:
http://stackoverflow.com/questions/32481508/autoreload-and-package-causing-typeerror-supertype-obj-obj-must-be-an-insta

There appears to be a bug in autoreload.

**Comment by Carreau** [comment]
I think this is covered in the doc of autoreload:

> Reloading Python modules in a reliable way is in general
difficult, and unexpected things may occur.

The problem is that python imports are cached, so while we do our best to replace things
where we can, you end up with 2 instances of your `base` module, that are the same (content)
but not the same (object id). Which to some weird case like an object not being an instance of it's class.
You can poke around and have [3+1 = 255](https://jakevdp.github.io/blog/2014/05/09/why-python-is-slow/) also if you like. 

These are some corner case you hit when you do things (like autoreaload) you are not supposed to do with the language. 

If you find a fix, PR welcome, but this is not something we will actively work on, so I'm going to close. 

Thanks
