### ISSUE TITLE
Strange Output printed

### ISSUE THREAD

**Issue by hsiaoyi0504** [ipython/ipython#8824]
[Link](https://github.com/hsiaoyi0504/ML2015/blob/master/hw1/hw1_17_PLA.ipynb)
My code is above
I find that in the end of this script
The output printed is strange
' PLA training verification\nprint("PLA updates count:",updates);\ny2=[];\nfor i in range(len(x[0])):\n    innerProduct=0;\n    for j in range(dimensions):\n        innerProduct=innerProduct+w[j]*x[j][i];\n    if innerProduct>0:\n        y2.append(1);\n    elif innerProduct<=0:\n        y2.append(-1);\nif y==y2:\n    print("PLA training verification: successed");\nelse:\n    print("PLA training verification: failed");\n'

**Comment by minrk** [comment]
The last statement in your code is a big string:

```python
""" PLA training verification
print("PLA updates count:",updates);
...
"""
```

This is considered a 'result'. If you want this to be a comment, you can start lines with `#`

**Comment by hsiaoyi0504** [comment]
Sorry for the stupid question
I am a beginner of python
And I found the """ for comment purpose from
http://www.pythonforbeginners.com/comments/comments-in-python

Does it not work due to python3 ? or just this is totally wrong?

Thanks

**Comment by minrk** [comment]
@hsiaoyi0504 that site is totally wrong. Multi-line strings are not comments, and never have been.

**Comment by hsiaoyi0504** [comment]
I'am confused
I find the document on python website also have this
https://www.python.org/dev/peps/pep-0008/#documentation-strings
Still this mean no error?bug?
Or iPython takes this as feature?

**Comment by minrk** [comment]
Docstrings are not comments; they are part of the code. There are no bugs here. IPython displays the last result of a cell with `Out[n]:`. In your case, you have entered code whose result is a long string. It would be the same if you had a short string:

```python
In [1]: "a string"
Out[1]: 'a string'

In [2]: """also a string"""
Out[2]: 'also a string'
```

There is no difference in Python between triple-quoted strings (`"""`) and single-quoted strings (`"` or `'`). The triple-quote only makes it easier to make multi-line strings, because they are allowed to span multiple lines without escape characters.

**Comment by hsiaoyi0504** [comment]
Still confused
I see the stackoverflow
http://stackoverflow.com/questions/7696924/multiline-comments-in-python
and famous tweeter
https://twitter.com/gvanrossum/status/112670605505077248
I produce same result even using ''' rather than """

**Comment by minrk** [comment]
As seen in the code above, a multi-line string represents a value. When Python runs interactively (this includes regular Python and IPython), it displays the value of the last expression. In your case, the last is a string literal, so that value is displayed.

In the midst of a Python module, the interpreter may optimize-out a string literal that it knows is never used, but that is not how it works in general.

**Comment by hsiaoyi0504** [comment]
ok,thanks
