### ISSUE TITLE
multiprocessing output is displayed only when all subprocesses are done

### ISSUE THREAD

**Issue by andrea-cuttone** [ipython/ipython#8863]
Running multiprocessing does not display the output until all computations are done.
For example using multiprocessing module:

```python
import multiprocessing

def bar(x):
    for i in xrange(x*10000000):
        pass
    print x, 'done'
    return 0

pool = multiprocessing.Pool(2)
pool.map(bar, range(16))
```

If the code is run with standard python the output is printed immediately after one subprocess is done.
But if this code is run in ipython, the output is displayed only when all subprocesses are done. 

Similarly when using [joblib](https://pythonhosted.org/joblib/):

```python
from joblib import Parallel, delayed

def foo(x):
    for i in xrange(x*10000000):
        pass
    return 0

Parallel(n_jobs=2, verbose=100)(delayed(foo)(i) for i in range(16))
```

in ipython the progress is printed only when all subprocesses are done.

EDIT: forgot to add my system info. OSX 10.10, python 2.7.10, ipython 3.2.0

**Comment by minrk** [comment]
Since we forward output over zmq, getting output from subprocesses is a bit complicated. The subprocess publishes messages over zmq to the parent, but the parent process only forwards those on to the public socket when `sys.stdout.flush` is called. You can see this if you call sys.stdout.flush periodically while waiting for the async job:

```python
import sys
import multiprocessing

def bar(x):
    for i in range(x*10000000):
        pass
    print('%i done\n' % x, end='')
    return 0

pool = multiprocessing.Pool(2)
mr = pool.map_async(bar, range(16))
while not mr.ready():
    sys.stdout.flush()
    mr.wait(0.1)
```

I think we may be able to address this by putting output publishing in its own thread, which would allow subprocess output to be published as it arrives, even if the main thread is blocking (as long as it releases the GIL once in a while). I think that would improve the situation quite a bit.

**Comment by takluyver** [comment]
@minrk can this be closed with your recent work on IO?

**Comment by minrk** [comment]
Yes
