### ISSUE TITLE
Reinstalling iPython Notebook

### ISSUE THREAD

**Issue by AlbinB** [ipython/ipython#8939]
Is there a way to remove Jupyter from the system? I tried uninstalling/reinstalling conda, even system restore...nothing seems to get rid of the damn thing. Any help will be appreciated.

**Comment by minrk** [comment]
If you installed the packages with conda, you can remove them with `conda remove`. If you installed them with `pip`, you can remove them with `pip uninstall`. You can see what packages are installed with `conda list` or `pip list`, respectively.

Since Jupyter is actually a collection of packages, not one, there may be several packages to uninstall, depending on how many jupyter projects you have, e.g.:

    conda remove jupyter_core jupyter_qtconsole nbformat nbconvert notebook

**Comment by AlbinB** [comment]
so, that was my first step. However, when I tried to run iPython notebook, I was still getting Jupyter. That's why I uninstalled/reinstalled conda, tried to clean out all jupyter references from appdata and programdata, registry(which came up empty).....even attempted system restore. However, I still get jupyter when i try to run iPython notebook

**Comment by Carreau** [comment]
IPython 3.x already had the jupyter "branding".

From a notebook go to the "help" menu and click "About". and it will either tell you you are using IPython 3.x  or Jupyter 4.x.

**Comment by minrk** [comment]
IPython notebook *is* Jupyter. The naming/logo transition started with IPython 3.x, and it is its own standalone package in 4.x. The two are not distinct, separate projects. The IPython notebook was given a new name, and eventually moved to a standalone package, but it is the same thing.

**Comment by Carreau** [comment]
Closing as nothing to do.
