### ISSUE TITLE
encoding of input in ipython (Windows python 2)

### ISSUE THREAD

**Issue by luopuya** [ipython/ipython#8949]
Quite confused about the encoding in ipython
in python
``` Python
>>> '一'
'\xd2\xbb'
>>> import sys
>>> sys.stdin.encoding
'cp936'
>>>
```

while in ipython
``` Python
In [1]: '一'
Out[1]: '\xe4\xb8\x80'

In [2]: import sys

In [3]: sys.stdin.encoding
Out[3]: 'cp936'
```

stdin.encoding is 'cp936', but ipython get 'utf-8' instead

**Comment by takluyver** [comment]
The short answer: if you're using non-ascii characters, you should use Unicode strings. `u'一'` should give you the correct Unicode code point. In Python 3, non-ascii sequences in byte strings have to escaped (i.e. `b'一'` would give a SyntaxError).

Longer: I can waffle about this all day if required. When we get code from the user, we can hand it to Python either as a series of bytes or a series of unicode code points. In the former case, unicode literals in the code are ambiguous - what code points do those bytes represent? In the latter case, non-ascii bytes literals are ambiguous - what bytes do those code points represent? We do the latter, because:

- If you're using non-ascii characters, you should probably put them in unicode literals anyway.
- On Python 3, non-ascii characters aren't allowed in bytes literals, so it's unambiguous.
- It so happens that the default guess Python makes when you give it unicode is what you expect for bytes literals on ~all modern Linux and Mac systems. The default guess when you give it bytes is mostly what you expect for unicode literals on Windows in a Western European locale.
