### ISSUE TITLE
Convert leading TABs to spaces when pasting code from external editor

### ISSUE THREAD

**Issue by p-i-** [ipython/ipython#8975]
When I paste a block of code (indented by TABs) from Sublime Text into a notebook cell, I then have to go about replacing the TABs with spaces. If the code contains different indent levels, it's rather fiddly.

It would make sense to perform this conversion automatically!

The only situation I can think of where this wouldn't be desirable is a multi-line string containing TABs.  But that would be easy to code around.

**Comment by Carreau** [comment]
Unfortunately, the browser is handling copy-pasting, and in particular on Mac OS X, it is trying to do "Smart" things (like smart quotes, space after/before punctuation...), and despite bug report and feature requests to have the ability disable that, a lot have been denied, or ignored. 

The next version will have search and replace (wit reg-ex support) so that should help. 

Also in general issues about the notebook should be opened on the [notebook](https://github.com/jupyter/notebook) repository. But I understand that what is which component on on which repo to open what can be confusing.

**Comment by jaamarks** [comment]
@p-i- , I found a website that converts tabs to spaces. It adds another step between copy/paste, but it does the job.

http://tabstospaces.com/

**Comment by sdive** [comment]
You can do a Replace (search for '\t', replace with the desired number of whitespaces (explicitly type the whitespace characters in the "Replace" field). Do not forget to enable the '.*' option.

Example:
![image](https://user-images.githubusercontent.com/390361/155323200-863a57d7-f43a-4ddf-8dc0-2ddc5a0092db.png)
