### ISSUE TITLE
traceback text color 

### ISSUE THREAD

**Issue by tblazina** [ipython/ipython#8986]
For some unknown reason, when I've opened ipython in sublimeREPL I've found that when I get any sort of traceback, for example when I enter an unknown variable name into the ipython interpreter it gives me garbled mess with a bunch of 

ESC[1;32 scattered in between the text. The same thing happens when I use the ? or ?? commands in ipython to bring up an function/object description. I've found I can fix this part of it by altering the  following commands in the ipython_config.pyL 

c.InteractiveShell.color_info = False set equal to True, 

or by making c.InteractiveShell.colors = 'Linux'  set equal to 'NoColor' 

I'm wondering if this perhaps a problem with Ipython or rather something with sublimeREPL (I've raised a similar issue on the sublimeREPL git). Anyone seen this before?

**Comment by Carreau** [comment]
I would say that this is likely an issue with sublimeREPL. 

The thing you see are [ansi escape sequences](https://en.wikipedia.org/wiki/ANSI_escape_code), they are the way to indicate to a terminal that you want a style for the underlying text. usually copy-pasting in software is implemented so that you do not get these escapes sequences out in your clipboard. 

I'm marking as "no action" as there is not much we can do if we want to display colors. and this will likely be close later. Feel free to post here a link to your sublime repl issue.

**Comment by Carreau** [comment]
Hi, 

This issue has been quiet for almost two years, and I don't think there is anything we can do. It has been marked as no-action, and I'm going to close it to attempt to reduce the number of opened issue. Feel free to reopen if needed. 

Thanks.
