### ISSUE TITLE
ipykernel\__main__.py:3: DeprecationWarning: object() takes no parameters 

### ISSUE THREAD

**Issue by indranilsinharoy** [ipython/ipython#9162]
If I create  a class that has a ``__new__`` magic method, I get the above deprecation warning when I try to instantiate. This problem appears in both the IPython Qt Console and Jupyter notebook (running IPython Kernel). The following code snippet illustrates the issue. (Please note that the I don't see the same warning message if I run the code in a standard Python shell.)

**Minimal reproducible test case**

```python
class MyClass(object):
    def __new__(cls, *args, **kwargs):
        return object.__new__(cls, *args, **kwargs)
    def __init__(self, a):
        self.a = a
```
When I invoke

```python
myclass = MyClass(10)
```

I get the following warning 

```python
C:\Anaconda\lib\site-packages\ipykernel\__main__.py:3: DeprecationWarning: object() takes no parameters
  app.launch_new_instance()
```

**Other reports of this issue?**
When I googled the above warning message, I found one report about it [here @ stackoverflow](http://stackoverflow.com/questions/33985173/deprecationwarning-object-init-takes-no-parameters). The question posted there was in the context of SymPy, and so the solution also seemed to be in the context of SymPy. However, it seems to me (as the above code snippet shows) that it doesn't have anything to do with SymPy.

**System information**
λ python -c "import IPython; print(IPython.sys_info())"
{'commit_hash': u'8ff8693',
 'commit_source': 'installation',
 'default_encoding': 'cp437',
 'ipython_path': 'C:\\Anaconda\\lib\\site-packages\\IPython',
 'ipython_version': '4.0.3',
 'os_name': 'nt',
 'platform': 'Windows-10-10.0.10240',
 'sys_executable': 'C:\\Anaconda\\python.exe',
 'sys_platform': 'win32',
 'sys_version': '2.7.11 |Anaconda 2.3.0 (64-bit)| (default, Jan 19 2016, 12:08:31) [MSC v.1500 64 bit (AMD64)]'}

**Comment by Carreau** [comment]
This is a perfectly normal behavior. 

DeprecationWarnings are what they name suggests, warnings about deprecation. Thay are Supposed to be enabled by developers to warn them of deprecated features, what we do by default in IPython. 

You can do it simply with : 

```
$ python2
Python 2.7.10 (default, Jul 13 2015, 12:05:58)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import warnings
>>> warnings.simplefilter('default')
```

then if you continue typing your example:
```
>>> class MyClass(object):
...     def __new__(cls, *args, **kwargs):
...         return object.__new__(cls, *args, **kwargs)
...     def __init__(self, a):
...         self.a = a
...
>>> MyClass(1)
__main__:3: DeprecationWarning: object() takes no parameters
<__main__.MyClass object at 0x10df0e9d0>
```

As stated, `object()` does not takes parameters. Python let you pass parameters without crashing (it emits a warning). Which mean you are strongly advise to not do what stated above as it will fail soon. 

And indeed in Python 3, object do not take parameter, if you try you will get a `TypeError`. 
The fix is simple, you just have to not pass parameters to `object` (and switch to Python 3).

I'm going to close the issue, but feel free to continue asking questions.

**Comment by indranilsinharoy** [comment]
@Carreau Thank you very much for explaining the issue :+1: . I should have known better :-). 
Best regards,
Indranil.

**Comment by Carreau** [comment]
> @Carreau Thank you very much for explaining the issue .

> I should have known better :-)

No problem, we are here for that.
