### ISSUE TITLE
Custom PPrinter

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#9227]
It was pointed to me on Twitter by @wolever, that it's not obvious how to get custom pprint formatter in IPython. 

There are many things:
- document in a better way how to register a formatter for a specific type 
  - probably got lost in TheBigSplit.
- add a config option / document how to completely replace our pprint library.
- add entrypoint for pprinter libs ?
  - directly use https://github.com/wolever/pprintpp if installed ?

**Comment by wolever** [comment]
I don't know if the current pretty printer is doing a bunch of compatibility stuff… but if considering a switch to pprintpp isn't totally unreasonable, I'd be happy to make any reasonable changes to pprintpp to make that happen :)

My question is specifically motivated by the fact that the default pretty-printer does weird and hard to read things with nested collections, like putting the first item on the same line as the open paren:

```python
In [42]: {"foo": [{"bar": 42}, {"bar": 16}] * 3, "bar": [1,2,3,4,5]}
Out[42]: 
{'bar': [1, 2, 3, 4, 5],
 'foo': [{'bar': 42},
  {'bar': 16},
  {'bar': 42},
  {'bar': 16},
  {'bar': 42},
  {'bar': 16}]}

In [43]: pprintpp.pprint({"foo": [{"bar": 42}, {"bar": 16}] * 5, "bar": [1,2,3,4,5]})
{
    'bar': [1, 2, 3, 4, 5],
    'foo': [
        {'bar': 42},
        {'bar': 16},
        {'bar': 42},
        {'bar': 16},
        {'bar': 42},
        {'bar': 16},
        {'bar': 42},
        {'bar': 16},
        {'bar': 42},
        {'bar': 16},
    ],
}
```

**Comment by takluyver** [comment]
I don't think we're especially tied to the current pretty-printer machinery, though some of our tests probably assume it. I'd be happy to move to a pretty printer module someone else maintains, so long as we could be reasonably sure it wasn't making any case significantly worse. Our own pprint module is fairly old and doesn't get much love.

@wolever one issue that's come up with our current pretty-printer a few times is the behaviour with long lists of small items - e.g. `list(range(200))`. Currently, these get displayed one per line, which is often less convenient than the default repr, just because it takes up so much space. I've just tried `pprintpp` and it does the same thing by default. Any ideas on whether some improvement is possible without degrading the format of other results?

**Comment by wolever** [comment]
@takluyver so, I've actually put a bunch of thought into how that could be fixed, and I've just been stalled because I haven't come up with an algorithm I'm totally satisfied with.

My current best idea is:

1. stringify all the items in the collection (lists, sets, and other single-item iterables; dictionaries wouldn't change)
2. Check that all the items have "roughly similar" widths (ie, to make sure the table isn't going to look ridiculously silly)
3. Format the items into a table, optimizing the lines to have (as much as possible) the same number of items. ex:

```
[
    1, 2, 3,  4,  5,  6,
    7, 8, 9, 10, 11, 12
]
```

or possibly numpy style:

```
[1, 2, 3,  4,  5,  6
 7, 8, 9, 10, 11, 12]
```

I believe this will work well with simple cases (numbers, short strings, small heterogeneous lists)... and worst case it will regress back to what's happening now.

**Comment by takluyver** [comment]
That's further than we got with it. I think a solution that works for simple cases and has the current behaviour for more complex cases is probably fine. I don't think there are many complex cases where the items' reprs are short enough for this to come up.

**Comment by yongzx** [comment]
I would like to work on this issue. Is there anyone working on it?

**Comment by takluyver** [comment]
No, I don't think anyone's working on it. There are a few bits to it - the simplest one is just to document the existing APIs for registering pretty-printers. That probably means summarising some of the information from [here](http://ipython.readthedocs.io/en/stable/api/generated/IPython.lib.pretty.html) to a new section in [this doc](http://ipython.readthedocs.io/en/stable/config/integrating.html).

Beyond that... there's a design decision about making the pretty-printer configurable and/or switching to pprintpp by default. There are competing principles here: pprintpp may be the best thing 'out of the box' for new users, but switching breaks consistency, especially for people who have already got code extending `IPython.lib.pretty`. Flexibility argues for making it configurable, but that always increases complexity.

Given that this issue has gone almost 2 years with no comments, I'd be inclined to say that no-one's clamouring for major changes, so we should just document what we've got.

**Comment by mpenkov** [comment]
I'll do this for hacktoberfest.
