### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#9239]
with IPtyhon dropping gui_banner, this mean that IPython master require ipykernel > master (future 4.2 or alike)

we need to update dependency number in setup.py.

**Comment by minrk** [comment]
Doing this here would mean the `ipython[kernel]` package depending on `ipykernel>=4.3.0.dev0` (dev is required, since `1.0.dev < 1.0`). Since IPython itself doesn't depend on any version of ipykernel.

I'm not sure the breakage caused by removing unused keys is really greater than the benefit of their absence.

**Comment by Carreau** [comment]
The problem is, if you update IPython without updating ipykernel, all your kernels are dying and it's hard to debug. 

ipykernel is incompatible with IPython master and 5.0

One the other solution is to release ipykernel soon, to make sure people are up to date before next upgrade of IPython.. 

A last solution is to reintroduve the gui_banner key to **not die** and remove it much later.

**Comment by takluyver** [comment]
If you're running from master, you're probably not installing the backwards-compatibility extras like `ipython[kernel]` anyway, so you wouldn't pick up that dependency. And I don't think we should add a regular install dependency on ipykernel, because IPython doesn't depend on ipykernel, and saying it does creates a circular dependency.

One of the consequences of splitting up the repos is that if you run from master, stuff will break sometimes when repos get out of sync. It should decrease over time as we decouple things, but when it happens, I think we have to live with it.
