### ISSUE TITLE
ImportError: bad magic number in 'jinja2': b'\x03\xf3\r\n'

### ISSUE THREAD

**Issue by r00tr4t** [ipython/ipython#9258]
This is what i get on my ArcLinux machine after installing with pacman -S jupyter-notebook.
```
$ jupyter-notebook 
Traceback (most recent call last):
  File "/usr/bin/jupyter-notebook", line 3, in <module>
    from notebook.notebookapp import main
  File "/usr/lib/python3.5/site-packages/notebook/notebookapp.py", line 28, in <module>
    from jinja2 import Environment, FileSystemLoader
ImportError: bad magic number in 'jinja2': b'\x03\xf3\r\n'
```
`
$ python -V

Python 3.5.1
`

**Comment by takluyver** [comment]
That's very unlikely to be something we can control. It's finding a bad file for Jinja, one of the dependencies. It may be finding a `.pyc` file created by Python 2, for instance. Check if you have `$PYTHONPATH` set, and if so, try unsetting it. Otherwise, it could be a packaging issue - the notebook should depend on jinja2 for the relevant Python version.

**Comment by r00tr4t** [comment]
Wow. Thanks you was absolutely right on the $PYTHONPATH. 
Think my .bashrc just copied over from my old computer and then i needed to haw $PYTHONPATH to run OpenShot video editor... 

Thanks million =)

**Comment by takluyver** [comment]
No problem.

**Comment by ItaloPerez2019** [comment]
> Wow. Thanks you was absolutely right on the $PYTHONPATH.

How do set the path
