### ISSUE TITLE
Can't quit `less` without using Ctrl-C: pager quit is effectively broken.

### ISSUE THREAD

**Issue by fperez** [ipython/ipython#9391]
If I run `!less <somefile>`, issuing `q` fails to quit it. I have to issue `Ctrl-C` to quit.  This is pretty problematic since `less` is used by the pager for long output.

**Comment by takluyver** [comment]
Do you see this when it's actually our own pager as well? I can reproduce it by doing `!less`, but the pager that comes up for e.g. `numpy??` works as normal.

**Comment by fperez** [comment]
Ah, sorry! Invalid extrapolation: I hadn't realized that you'd switched to a native pager, and assumed (without testing) that the problem with calling `!less` would also be present with `?`. Indeed, that works fine, so it's less critical than I thought, though still a bug (I found it b/c it actually hit me in real-world use).

**Comment by takluyver** [comment]
I don't think we've switched the pager - it is still using less internally, but some difference in how it's being invoked is apparently making it work.

**Comment by jboucasier** [comment]
I work on Linux, I don't know how `pts` works on other plateforms.

For me this bug happens not only for `less`, but for all programs which need `pts` allocation.
For example, with `vim`, it is working by the magic `%edit`, but not with `!vim`.

For the magic, `vim` is launched by `subprocess.Popen`, and for the bang, from `pexpect.spawn`.

A workaround can be:
```
diff --git a/IPython/utils/_process_posix.py b/IPython/utils/_process_posix.py
index ac3a9a0..997ac9d 100644
--- a/IPython/utils/_process_posix.py
+++ b/IPython/utils/_process_posix.py
@@ -155,6 +155,7 @@ def system(self, cmd):
                 child = pexpect.spawnb(self.sh, args=['-c', cmd]) # Pexpect-U
             else:
                 child = pexpect.spawn(self.sh, args=['-c', cmd])  # Vanilla Pexpect
+            child.interact()
             flush = sys.stdout.flush
             while True:
                 # res is the index of the pattern that caused the match, so we
```

But the problem is not solved, `vim` with `!vim` is still launched with new `pts` with wrong size, but with `interact()` method, the keystrokes are send to the good `pts`.

**Comment by takluyver** [comment]
Aha! It shouldn't be going through pexpect.spawn() when you use IPython in a terminal, because it can just take over the terminal that you're already using. I've worked out what we're doing wrong, PR coming up...

**Comment by takluyver** [comment]
#9398 should fix this

**Comment by fperez** [comment]
Thanks! Confirming the fix works :)
