### ISSUE TITLE
[PTK] ControlSpace and start selection.

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#9425]
ControlSpace put the cursor on "start_selection" mode (defined in ptk/emacs.py). 
It' is not obvious, especially how to exit it. 

`CtrlC` DOes exit the mode, but does not immediately change the cursor blinking mode which is confusing. 

Also we might want selection mode to not be triggerable when the buffer is empty.

Not sure if it's an IPython, or a prompt_toolkit thing to fix.

**Comment by takluyver** [comment]
'Delete' is the only reliable way out of selection mode in my brief testing. Ping @jonathanslenders - I think we're missing something here.

**Comment by jonathanslenders** [comment]
I the Emacs world, ``ControlG`` is used for cancelling stuff. Reverse search, selection, etc...

- ``Control-Space`` (or ``control-@`` for terminals that don't know ``control-space``): enter selection mode.
- ``ControlW``: cut
- ``Meta-W``: copy
- ``ControlY``: paste
- ``ControlG``: cancel

FYI:
- ``ControlX``: Go to the start/end of a given line.
- ``ControlC`` Abort input
- ``ControlV`` Scroll down.

More info: https://www.gnu.org/software/emacs/manual/html_node/emacs/Clipboard.html
Prompt-toolkit does not yet have a "kill-ring" like Emacs, ``M-y`` is not yet implemented.

**Comment by jonathanslenders** [comment]
```
Also we might want selection mode to not be triggerable when the buffer is empty.
```
That's a good suggestion. I'll fix that.

**Comment by jonathanslenders** [comment]
FYI: last two weeks, I've been working a lot on improving and simplifying the code for the prompt-toolkit key bindings. Especially for Vi mode. There is now a clean separation between a binding that defines a Vi operation and a binding that defines a Vi text object or movement.
The good thing is that many more Vi bindings are working. Further, it becomes much easier to extend a key binding. It is easy to say: "I want a binding for Emacs selection mode", or "I want to define a binding to create a Vi text object".

The bad thing is that in order to make this simplification, I had to put an ``editing_mode`` attribute in the ``CommandLineInterface`` class. This variable defines whether Vi, Emacs (or maybe even something else) is active. So, the ``enable_vi_mode`` for the ``KeyBindingManager`` argument isn't used anymore. I keep it to make sure that it doesn't break anything, but it means that this is simply ignored.

I hope to finish it during the next few days/next week. Then I'll push a new release numbered "1.0.0".  Where the major version stays as long as no backward-incompatible changes are done. (Hopefully for a very long time.) When finished, I open a new IPython pull request.

**Comment by takluyver** [comment]
As always, thanks @jonathanslenders - that's super informative :-)
