### ISSUE TITLE
Rollback jedi integration for 5.0 ?

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#9474]
Seeing that 5.0 will be LTS, and that we 
1) have a few bug with our integration, 
2) current jedi breal `ipython foo.py > out` at it init colorama,

Should we revert to old IPython completion for 5.0 ? That would be also a nice feature to have for Python 3 only.

**Comment by takluyver** [comment]
If we're planning to do 5.0 soonish, I think this probably makes sense. I was keen to make the prompt_toolkit changes before 5.0 because I didn't want to be stuck supporting readline installation with the LTS, but I'm not sure there are any equivalent issues with completion.

If 5.0 is still some way off, though, then I'd consider leaving the jedi stuff in and trying to iron out the bugs for a bit longer.

**Comment by Carreau** [comment]
Well, I'd like to release 5.0 before SciPy, so that would mean release in a month-ish a little more, so probably beta before right ?

I'll work on removing jedi stuff, and then there should be only a couple of major issues left.

**Comment by Carreau** [comment]
Closed by #9476
