### ISSUE TITLE
Completion usability: don't pop up dialog for single completion

### ISSUE THREAD

**Issue by fperez** [ipython/ipython#9540]
Tab completion currently has a serious usability problem compared to the old (albeit more limited) readline one: when there's a single completion it still pops up the dialog, which is very distracting as it stops your flow to read irrelevant information.

We should fix this before 5.0 goes out...

**Comment by takluyver** [comment]
Ping @jonathanslenders

**Comment by Carreau** [comment]
Is that critical ? the fix is 2 lines in prompt toolkit, and needs us to subclass Buffer and hack quite a bit around in IPython itself ?

**Comment by Carreau** [comment]
There will though be another annoying side effect, likely due to an IPython "bug". 
As PTK, is complete "as you type", typing `im<tab>` would autocomplete to `import`, and try to keep completing. But at this stage, as `import|` try to complete, return **only** `importlib`, so in the end `imp<tab>` complete to `importlib`. 

So the fix is likely a bit more involved.

**Comment by jonathanslenders** [comment]
See: https://github.com/jonathanslenders/python-prompt-toolkit/pull/311
I made a fix, but with some remarks.

**Comment by Carreau** [comment]
Marking as 5.1, as non critical.

**Comment by jorisvandenbossche** [comment]
A related remark about this: due to the completion dialog popping up, I cannot just 'enter' to execute the command.

An example workflow (to check the version of a library, but of course is legit for all cases where there is only one possibility but you just want to complete to save typing) which worked previously: 
type `pd.__v` 
-> press 'tab' (completed to `pd.__version__`) 
-> press 'enter' 
-> you get the result

This workflow is now broken, because you get a completion dialog after pressing tab, and then Enter does not work anymore to execute. I either have to press 'Escape' to remove the dialog, or to press 'down button' to select the the first and only completion suggestion, before 'Enter' gives you the result.

Personally I find this quite disturbing for this (I think common) workflow (and thus rather critical for 5.0)

Tested with 5.0.0b3 on Windows

**Comment by Carreau** [comment]
> A related remark about this: due to the completion dialog popping up, I cannot just 'enter' to execute the command.
> 
> An example workflow (to check the version of a library, but of course is legit for all cases where there is only one possibility but you just want to complete to save typing) which worked previously: 
> type pd.__v 
> -> press 'tab' (completed to pd.__version__) 
> -> press 'enter' 
> -> you get the result
> 
> This workflow is now broken, because you get a completion dialog after pressing tab, and then Enter does not work anymore to execute. I either have to press 'Escape' to remove the dialog, or to press 'down button' to select the the first and only completion suggestion, before 'Enter' gives you the result.
> 
> Personally I find this quite disturbing for this (I think common) workflow (and thus rather critical for 5.0)
> 
> Tested with 5.0.0b3 on Windows

The exact opposite was requested in beta1, several time. Enter should pick up a completion and dismiss the menu, not execute. 

The problem with "only one completion" is [in the changelog](https://github.com/ipython/ipython/blob/master/docs/source/whatsnew/version5.rst#known-issues):

> Known Issues:
> ...
> Dialog completion pop up even with a single completion. Cf :ghissue:`9540`. This would automatically be resolved with the next minor revision of prompt_toolkit
> ...

Here is how it will look like:

![comp](https://cloud.githubusercontent.com/assets/335567/15971336/73291392-2eed-11e6-9f70-4c6f21fd3e1b.gif)

**Comment by jorisvandenbossche** [comment]
> The problem with "only one completion" is in the changelog:

>    Known Issues:
    ...
    Dialog completion pop up even with a single completion. Cf :ghissue:9540. This would automatically be resolved with the next minor revision of prompt_toolkit
    ...

Great, that will solve the issue!

> The exact opposite was requested in beta1, several time. Enter should pick up a completion and dismiss the menu, not execute. 

That's certainly OK, but would it then be possible that the first item is selected by default? Because now, Enter does nothing right after pressing tab (you first have to do press down or another tab to select the first item, before Enter has any effect).

For example, to get an attribute that is first in the completion list was previously `Type -> Tab -> Enter`, which has now become `Type -> Tab -> Tab -> Enter -> Enter`. If the first item of the completion list, that would eliminate one of the extra key strokes.

**Comment by jonathanslenders** [comment]
```
OK, but would it then be possible that the first item is selected by default?
```

That's a valid request. Unlike several other prompt-toolkit based CLIs, IPython doesn't use the ``complete_while_typing`` option which generates completions as you type. When this is enabled, you don't want to automatically select the first completion, and pressing tab is required. In the case of IPython, use user explicitely presses tab, so in that case it makes sense to select the first completion by default. (Shift-tab can be used to undo this.)

Any objections against? I can do this in the next minor version of prompt-toolkit as well. If not desired, it's also always possible to override.

**Comment by Carreau** [comment]
> IPython doesn't use the complete_while_typing

For now :-) 

I'm planning on adding that later , we need to keep a few new features for next versions.


> Any objections against? I can do this in the next minor version of prompt-toolkit as well. If not desired, it's also always possible to override.

No objections.

**Comment by takluyver** [comment]
I think I initially enabled `complete_while_typing`,  but then found it was mutually exclusive with some other feature which we wanted, so I disabled it again. I forget what that feature was, though...

**Comment by jonathanslenders** [comment]
I added the following code to prompt_toolkit which displays autocompletion just like readline does: https://github.com/jonathanslenders/python-prompt-toolkit/commit/321b893983a7d43136a51c46abbfc079afe3cddf

There is an example: https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/examples/autocompletion-like-readline.py

The only code to be added in order to activate this:
```
from prompt_toolkit.key_binding.bindings.completion import display_completions_like_readline
key_bindings_manager.registry.add_binding(Keys.ControlI)(display_completions_like_readline)
```
(For this, ``complete_while_typing`` needs to be disabled, because both are incompatible.)

Tomorrow, I do some more tests, and hopefully I can do a new prompt-toolkit release then.

**Comment by takluyver** [comment]
Great, thanks. Once the new PTK is out, we may want to add an option to switch to that kind of completions for the people who're upset by the change.

The original issue (displaying the completion dropdown when there's only one completion) and the later request (selecting the first item when the completions dropdown appears) are fixed in PTK master, so I'm closing this issue.

**Comment by fperez** [comment]
Thanks everyone, and esp. to @jonathanslenders for being so responsive on the PTK side! Once we refine the user experience to smooth these remaining sharp edges, I think the IPython with PTK release is really going to make lots of folks very happy. Looking forward to it!

**Comment by jonathanslenders** [comment]
prompt-toolkit==1.0.1 has been released with the fixes you've been asking for. Let me know how this works. If something is not yet exactly as we want, we can still release a 1.0.2.

Maybe 1.0.1 can be put in the setup.py as minimal requirement. (up to you).

**Comment by Carreau** [comment]
> Maybe 1.0.1 can be put in the setup.py as minimal requirement. (up to you).

Yes we'll do that in #9624 !
