### ISSUE TITLE
Multi line paste not working anymore in 5.0 beta

### ISSUE THREAD

**Issue by jorisvandenbossche** [ipython/ipython#9600]
Copy the below text in the new ipython console:

```
x = 1
y = 2
```

and I only see the first line pasted.

I am using Windows 7, cmd command prompt, and using right clicking to paste. With previous versions of ipython this works (directly executing all but the last line, since there was no multi-line input).

**Comment by jorisvandenbossche** [comment]
Strange thing, if I try to copy multiple lines:

```
x = 1
y = 2
z = 3
```

then the first two (or all but the last) lines are concatenated and of course give a Syntax Error. Result of pasting the above:

```
In [33]: x = 1y = 2
  File "<ipython-input-33-68a99508cab0>", line 1
    x = 1y = 2
         ^
SyntaxError: invalid syntax
```

**Comment by takluyver** [comment]
@jonathanslenders any idea what could be up with pasting on Windows? I wonder if it's a line-ending issue?

**Comment by klonuo** [comment]
I can reproduce this too:

```pytb
In [3]: x = 1y = 2
  File "<ipython-input-3-68a99508cab0>", line 1
    x = 1y = 2
         ^
SyntaxError: invalid syntax
```

pasting same in opened triple quotes works:

```python
In [4]: a = '''x = 1
   ...: y = 2
   ...: '''

In [5]: a
Out[5]: 'x = 1\ny = 2\n'
```

**Comment by Carreau** [comment]
Can both of you try with PTK master ?

**Comment by jorisvandenbossche** [comment]
I get the same on prompt_toolkit master, but, I do get some errors with master when using any arrow key

**Comment by Carreau** [comment]
> I get the same on prompt_toolkit master, but, I do get some errors with master when using any arrow key

If you have errors on IPython/ptk-master can you post them here ?

**Comment by jorisvandenbossche** [comment]
Just opened an issue at ptk: https://github.com/jonathanslenders/python-prompt-toolkit/issues/316

**Comment by jonathanslenders** [comment]
The bug regarding the pasting is probably in this key binding (Ctrl-J). I can reproduce it, but it doesn't happen for ptpython.

https://github.com/ipython/ipython/blob/master/IPython/terminal/ptshell.py#L183

**Comment by jonathanslenders** [comment]
How do you feel if I can make pasting on Windows 99.9% accurate, but not 100%?

By this I mean, as far as I know, there is no way to detect when a user is pasting text, rather than typing fast. However, when pasting text, one ``ReadConsoleInputW`` will probably return multiple keys. (Up to 1024, according to the current setting.) This means, that if a user is pasting 1025 characters from which the last is a newline, then we will receive first one chunk of 1024 characters; process these; and later one single newline and process that separate. This means that in this particular case, it will be really hard to know whether this last newline was pasted or not. However, in the other cases, we can be rather confident, and emulate bracketed paste.

**Comment by jonathanslenders** [comment]
Proof of concept for a possible fix in prompt-toolkit: https://github.com/jonathanslenders/python-prompt-toolkit/pull/318
(This should fix multiline paste on Windows, but probably still breaks paste in some situations in Linux. Still working on that.)

Note that the fix above does not try to interpret pasting as something different from typing normal text. This fix simply ensures that on Win32, we only read events from the input device until the CLI is put into the "done" state. (which is when it has to return a result to IPython). That way, all the following input will be preserved until the next ``prompt()`` call.

Next step, if we want to, is to discover that a newline is part of a larger sequence of text, and if so: consider it a paste. After thinking a lot about this, I think it is possible, but there are some edge cases, and it makes me wonder whether it's worth the effort. It comes down to tracing whether a key press was preceded by another key press or is followed by another keypress without any delay. I want a universal solution which also handles the case of a unix terminal without bracketed paste. And the hard thing there is that one key press can match multiple characters at the input stream, and so we have several layers of abstraction through which we have to track this information.

**Comment by jonathanslenders** [comment]
New implementation: https://github.com/jonathanslenders/python-prompt-toolkit/pull/319

I'd appreciate if anyone with a Windows system can test this branch. It emulates bracketed paste on Windows. That means that if the input is detected as a paste, no indentation is added, nothing is automatically executed and all text is kept in one input field.

**Comment by jorisvandenbossche** [comment]
@jonathanslenders tested it, and seems to work! (at least for the simple paste cases I filed this issue for)

**Comment by stonebig** [comment]
ok. On Windows7/ Python3.5/IPython5.0.0b3/jupyter-console5.0.0b1, It works in:
-  jupyter-console, 
- ptpython.

**Comment by takluyver** [comment]
There's something I haven't understood: if pasting text acts just like
typing it, why wouldn't pasting a newline act like typing one? Does return
generate a different character?

Can we pick up ctrl+v on windows? Maybe we can use that to offer another
way to paste into the terminal.

**Comment by klonuo** [comment]
I didnt try new implementation but though to comment regardless.

I dont fully understand Jonathan comments, the same as I dont understand why pasting mulitline string in opened triple quotes works, while simple paste on command line doesnt work?

**Comment by takluyver** [comment]
> So, what I do on windows is make an assumption: " if ReadConsoleInputW returns at least one \r character, along with at least one other textual character, then we turn it into a paste event. "

To clarify, is this description what you did in response to this issue, or was this a mechanism that was already in place and something was going wrong with it?

If when @jorisvandenbossche found this issue pasting was just treated as typing fast, I'm having a hard time understanding how that would cause the symptoms he described. I understand why lines would be lost when the 'return' triggers IPython's execution, but I'm not sure why newlines would be lost to concatenate lines into one.

> So, what if a user types really fast, and is able to fill the input buffer faster than we can read from it? On my Windows system, this never happened,

The situation I'd be concerned about is not freakishly fast users, but the possibility that our event loop could be running slow for some reason. E.g. could this occur if you're using an input hook to integrate with a GUI event loop, and reading input gets delayed a few milliseconds?

If we can detect Ctrl-V in Windows, we already have [code](https://github.com/ipython/ipython/blob/master/IPython/lib/clipboard.py) for getting data from the clipboard. That could be more convenient for users, and it might be easier to tell all users 'paste like this' than explain the limitations of cmd-native paste if it ever goes wrong.

**Comment by takluyver** [comment]
> E.g. could this occur if you're using an input hook to integrate with a GUI event loop, and reading input gets delayed a few milliseconds?

Thinking about this some more, could even background threads potentially interfere, due to the GIL?

**Comment by jonathanslenders** [comment]
This was an indirect response to the issue where pasted lines were concatenated into one line.

The concatenation was caused by the fact that incoming keys were processed in bulk. We did not return to the event loop after a newline has set a return value in the CommandLineInterface. Instead, we did set the return value, but processed the other keys using the same input buffer. This is wrong, the CLI should always quit after a return value has been set.
This was easy to fix, however by fixing this, I created a new issue. The one where all input on the input buffer after the "enter" key press would be discarded. There is no reliable way to push information that has been read back into the input stream. (Remember, we use a lower level I/O interface, than ``sys.stdin``.)

By treating this as a paste event, I could avoid triggering the key binding for "Enter" and make sure that nothing would be discarded.

Background threads could interfere. Everything that blocks the main I/O loop could result in accumulating key presses in the input buffer. However, usually, a user stops typing if he doesn't see any feedback. (And we only display feedback in the next run of the event loop.) Further, a user doesn't easily press enter if he did not see any feedback. But, as I said, if ever this happens, the resulting behavior is acceptable.

I know, not 100% perfect, but probably 99.9%. I'll see whether I come up with something different. If not, and we're in doubt, I'll maybe merge it, but disable this behavior by default.

**Comment by takluyver** [comment]
OK, I understand now. Thanks for taking the time to explain it all.

I think it probably makes sense for you to implement that in PTK, and us to add a Ctrl-V shortcut in IPython (only for Windows? Or for all platforms?). I know Ctrl-V isn't the only way to paste, but if it works and it's convenient, it reduces the likelihood of people hitting edge cases with the native paste handling.

**Comment by jonathanslenders** [comment]
Adding ``Ctrl-V`` on Windows is much more trivial than on the other platforms. Actually, for a VT terminal, you can't do it reliably. (It won't work through telnet/ssh, or you would paste something from the clipboard of the remote server.) Pyperclip (https://github.com/asweigart/pyperclip) tries to do this.

It could make sense, except if somebody would use Vi mode and expect quoted insert or block selection to work.

**Comment by Carreau** [comment]
Can we consider this one close now ?

**Comment by takluyver** [comment]
I think so.
