### ISSUE TITLE
"Basic Numerical Integration: the Trapezoid Rule" example is wrong

### ISSUE THREAD

**Issue by boffi** [ipython/ipython#9641]
For a low order polynomial the trapezoid rule is exact... Your problem is that the intervals of integration are _different_ for `quad` and `trapz`.

Either change the interval of integration for `quad`  (as in `quad(f, 1.0, 8.5)`) or, imo better, change the sampling of `xint` and `yint` to `40` (as, e.g.,  in `x[np.logical_and(x>=a, x<=b)][::40]`).

**Comment by takluyver** [comment]
Thanks, do you want to make a pull request to fix it?

**Comment by thesageinpilani** [comment]
I am a beginner and interested in fixing this issue can you please guide me where the file is present and please explain more about the issue.

**Comment by takluyver** [comment]
The file's here:
https://github.com/ipython/ipython/blob/master/examples/IPython%20Kernel/Trapezoid%20Rule.ipynb

I don't understand the issue well enough to explain it any better, though.

**Comment by lakshayg** [comment]
@boffi It might be the case that I did not understand the problem properly but I believe that the example in the notebook is correct for the following reasons:

> For a low order polynomial the trapezoid rule is exact...

1. I belive that by low order polynomials you mean the polynomials with degree less that 2. The [wikipedia page on trapezoidal rule](https://en.wikipedia.org/wiki/Trapezoidal_rule#Error_analysis) states that the error is proprtional to `f''(c)` where `a < c < b`. Since the example involves a 3rd order polynomial, the evaluated integral won't be exact.
2. On increasing the number of intermediate points the error converges to 0.

Please let me know if I missed anything otherwise this issue can be closed.

**Comment by ian-r-rose** [comment]
I agree @lakshayg , the example looks correct to me.

**Comment by boffi** [comment]
In my vague recollection (a year ago...) the example was changed
shortly after my heads up, but of course I may be wrong. My
recollections notwithstanding, now the example is fine and the issue
should be closed. Thank you very much, ciao g

**Comment by takluyver** [comment]
Thanks all!
