### ISSUE TITLE
`--colors` flag seems to be ignored, `%colors` doesn't work

### ISSUE THREAD

**Issue by fperez** [ipython/ipython#9648]
See:

![image](https://cloud.githubusercontent.com/assets/57394/16251033/6a34f510-37d7-11e6-9092-29fe74cf605c.png)

I can't seem to get the no-color or LightBG schemes to work. I know there's a new color system in place, but

a) the old ones should be grandfathered in and still work
b) nocolor should still be available
c) the `%colors` magic still only lists the old ones and doesn't actually work.

**Comment by Carreau** [comment]
That's not completely totally accurate, `%colors` and `%nocolors` still work, they affect the highlighting of the pager and debugger and affect the kernel side of IPython (ie they do affect the notebook rendering in the pager, and a few other things displayed.) 

![screen shot 2016-06-22 at 16 04 19](https://cloud.githubusercontent.com/assets/335567/16286732/27c97928-3893-11e6-967d-77d641fd7e17.png)


The prompt color are now govern by pygments/prompt_toolkit:

```
--TerminalInteractiveShell.highlighting_style=<Unicode>
    Default: 'default'
    The name of a Pygments style to use for syntax highlighting:  paraiso-light,
    xcode, lovelace, borland, monokai, emacs, algol_nu, algol, perldoc, autumn,
    colorful, default, tango, manni, igor, friendly, murphy, native, fruity,
    vim, paraiso-dark, bw, rrt, trac, pastie, arduino, vs
```

![screen shot 2016-06-22 at 16 07 49](https://cloud.githubusercontent.com/assets/335567/16286789/7f16b538-3893-11e6-9750-fdd02afd8aa6.png)

They are partially governed by `--TerminalInteractiveShell.highlighting_style` which also uses pygments to highlight. 

We have to otherwise you couldn't get the "as you type" highlighting. 

It *could* be made into a single options that is consistent (we already have some work to do that), but that a tremendous amount of work as we would need in particular to completely refactor the debugger, to yield pairs of `(TokenType, tokens)` instead of doing the string formatting manually, and honestly after having [tried to do it](https://github.com/ipython/ipython/pull/9246/files) it is a gigantic pain on old Python versions [you know what I mean] , and things get even simpler if you can use `yiled from`. 

We'll try to make better docs for that, and restore a no coloring at all[1], but the separation of the 2 options IMHO : 
  - make sens:
  - And would be too much work for the small benefit. 

[1]: for **testing** purpose, and when using IPython as a subprocess, you want to use `ipython --simple-prompt` that **completely deactivate prompt_toolkit**, that is to say no completion, no color, no multiline ! But that's the price to pay to not depend on readline anymore. It does that automatically if not a TTY. 

Side info:

- The available themes are dynamics so might vary on your system. 
- docstrings could list themes, but Dynamics docstrings are a pain on Python 2, if at all possible. 
- We [are discussing](https://github.com/xonsh/xonsh/issues/726#issuecomment-227503678) a set of themes that include completion menu, prompt ... etc to share across many projects, we would like to have designer working on that. I've pinged Brian on a few issues so see if we could borrow student, but he so far did not replied. 
 - Some of the readability issues of color and design of above theme that suit everyone requires a new release of pygments. 
 - getting *exactly* the same themes as IPython 4.x without a new pygments is close to impossible, or the required solution is not worth the effort.

**Comment by fperez** [comment]
For the record on this issue, we seem to have a good compromise solution to ensure we don't break existing habits/aliases/etc...  The `--colors` option will map to hardcoded colors for lightbg/linux + a choice of pygments theme ('default' for 'lightbg' and 'monokai' for 'linux').  This will ensure prompt and color readability with the old choices, while allowing users to do full-blown theme selection if desired with the highlight style options.

**Comment by Carreau** [comment]
See #9655
