### ISSUE TITLE
Spectral Python Hypercube not working in IPython

### ISSUE THREAD

**Issue by MaheshSolankar** [ipython/ipython#9669]
Error :+1: 
C:\Python27\Lib\site-packages\spectral\graphics\graphics.py.py:786: UserWarning:
There is no current wx.App object - creating one now.
![ipython](https://cloud.githubusercontent.com/assets/20036902/16403894/6e5754f4-3d17-11e6-9c76-e3fc9e7e95fb.png)

**Comment by takluyver** [comment]
The message is a warning, not an error - that means it is continuing doing whatever it is doing. It's not coming from our code, but from the `spectral` package. And it's not clear what code you're running and what it's supposed to do. I'm closing this as it seems unlikely that it is something to be fixed in IPython. If you can clarify what's going on and still think it's a problem in IPython (and if you update to IPython 4 and still see it), then we can reopen this.

**Comment by iqbalhabibie** [comment]
I am using python2.7.13 and using ipython pyylab
ipython --pylab

and using this image from this website http://www.spectralpython.net/user_guide_intro.html


In [18]: data = open_image('92AV3C.lan').load()

In [19]: gt = open_image('92AV3GT.GIS').read_band(0)

In [20]: pc = principal_components(data)
Covariance.....done

In [21]: xdata = pc.transform(data)

In [22]: w = view_nd(xdata[:,:,:15], classes=gt)

c:\python2.7.13\lib\site-packages\spectral-0.18-py2.7.egg\spectral\graphics\graphics.py:786: UserWarning:
There is no current wx.App object - creating one now.

but there is an error like this. How to solve this?
