### ISSUE TITLE
IPython 5 on Windows fails to show bright\light colors

### ISSUE THREAD

**Issue by temp4746** [ipython/ipython#9723]
Anywhere where IPython tries to use bright\light colors in a Windows terminal (Windows 10) they show as the dark\normal color. This includes prompt numbers and is especially bothersome where the dark blue colors is used which is extremely hard to see on dark terminal backgrounds.

**Comment by xflr6** [comment]
Same here under Windows 7 (compare the prompt number):
![snap1](https://cloud.githubusercontent.com/assets/6342379/16684636/7d579760-4506-11e6-85d5-47f3b3771971.png)
![snap2](https://cloud.githubusercontent.com/assets/6342379/16684639/80378c88-4506-11e6-8a31-f80729580f1d.png)

**Comment by klonuo** [comment]
Screenshot with color background:

![clipboard01](https://cloud.githubusercontent.com/assets/361447/16685012/88daa2a6-4508-11e6-8eed-9194311a7dfd.png)

Here I type `os.<tab>`, then type `path.<tab>` (background isn't cleared)

**Comment by klonuo** [comment]
I do have color, unlike above reporters, because of my config file:

```python
c.TerminalInteractiveShell.highlighting_style_overrides = {
    Token.Prompt: '#ansigreen',
    Token.PromptNum: '#ansidarkgreen bold',
    Token.OutPrompt: '#ansired',
    Token.OutPromptNum: '#ansidarkred bold',

    Token.Number: '#007700',
    Token.Operator: 'noinherit',
    Token.String: '#BB6622',
    Token.Name.Function: '#2080D0',
    Token.Name.Class: 'bold #2080D0',
    Token.Name.Namespace: 'bold #2080D0'
}
```

As a side note we could enhance documentation further, with article about customizing colors with newly introduces prompt-toolkit.

**Comment by xflr6** [comment]
@klonuo your example uses a diferent console (Windows PowerShell instead of the plain console `cmd.exe`), which might be is the reason the colors work for that case (yet background clearing fails).

**Comment by klonuo** [comment]
@xflr6 It's the same console (conhost), but different "shell". I used PS as I knew it had colored background.

**Comment by temp4746** [comment]
It seems that due to the limited color capability of the Windows console (16 color palette) prompt-toolkit is converting the RGB colors to one of the 16 builtin colors but the conversion doesn't seem to get it right for the bright colors.

Also the default Pygments style that is used seems to use some dark colors for example dark blue, which is unusable on a black background terminal. (IPython before 5 used to use the lighter blue). Try reading this:

![capture](https://cloud.githubusercontent.com/assets/2670892/16738983/c36bc87e-47a0-11e6-87cb-72e9a4b98edf.PNG)

This might mean that we need to tweak the default Pygments style used to use lighter colors on dark terminals. Pygments has a TerminalFormatter which has a dark/light bg argument but that class doesn't use the standard Pygments styles which prompt-toolkit does.

For now, unless I built a custom color configuration that essentially restores IPython before 5 colors, this version is unusable on Windows. This can hurt newcomers quite badly too...

**Comment by takluyver** [comment]
I didn't think the colours in the oinspect output (`os.path.exists??`) had changed for 5.0. @Carreau, could your changes to the colour system have affected the ANSI codes we produce? Otherwise, it could be a difference in how the ANSI colour codes are translated to Windows API calls; previously pyreadline was responsible for that translation, now colorama is.

We can't in general detect what the background colour is, so we try to make the default colours visible on both black and white. This is complicated by the fact that the same colours get rendered differently in different systems. Maybe we should assume that there's a dark background on Windows, though - I think it's pretty unusual for Windows users to have a light background command window.

**Comment by Carreau** [comment]
Yeah, no this part is still weird, and still hook into the old PyColorize stuff (that still needs to refactor, and being nuked for next release and use pygments), but right now, yes the "Source" thing is limited to old colors.

**Comment by ktritz** [comment]
![screenshot 2016-07-14 11 31 25](https://cloud.githubusercontent.com/assets/5316449/16845367/a15e6030-49b6-11e6-841c-b10d6637ca87.png)

Light background 'cmd.exe' terminal in Windows 10. Prompt comes up with a black background. I assume this is a similar issue here, any fix?

**Comment by takluyver** [comment]
Crap, did they really change the default cmd.exe background in Windows 10?

**Comment by klonuo** [comment]
@takluyver No :D @ktritz probably selected white background from one of available color, while it's not ColorTable00 which is assumed as background I guess by PTK.

**Comment by ktritz** [comment]
Correct, I changed the cmd.exe color 'defaults' in the system menu. Ipython
doesn't appear to play nice with the change.

**Comment by takluyver** [comment]
Ah, OK. So we can still assume a black background in general for Windows.

Can you try:

1. `%colors lightbg` - this probably won't work, but you never know.
2. Get some help (e.g. `zip?`) and take a screenshot - those colours are produced in a different way, and I want to see if they work.

**Comment by ktritz** [comment]
![screenshot 2016-07-14 12 46 26](https://cloud.githubusercontent.com/assets/5316449/16847870/186fb282-49c1-11e6-9ca2-97f5130d7bda.png)

Here you go. The prompt changed color using %colors lightbg, but the background stayed black. Zip help displayed properly.

**Comment by takluyver** [comment]
OK, then it appears that the fixed black background in the prompts is something prompt_toolkit does. @jonathanslenders , have you come across this before?

**Comment by lsorber** [comment]
Having the same issue as @ktritz on Windows 10. IPython 5 seems to reuse the command prompt font color, but overrides the background color to black.

**Comment by jonathanslenders** [comment]
If I understand correctly, people can change the colors in two ways. They can choose another color from the palette to use as foreground/background, but they can also change the value of each color. I think this issue happens in the first case. So far, I haven't been able to work on this issue, but coming Saturday, I should have most of my day for coding. :-)

**Comment by Carreau** [comment]
I'm trying to borrow a windows machine to work on that as well.

**Comment by jonathanslenders** [comment]
Hi all, this commit should fix it: https://github.com/jonathanslenders/python-prompt-toolkit/commit/a9df2a24ed54eae356e622cd4cc0ddf3c4a8c008

Can you try again after checking out the latest commit from prompt-toolkit master?

**Comment by ktritz** [comment]
That fixes the issue for me.

Thanks.

**Comment by takluyver** [comment]
Thanks @jonathanslenders for another quick response :-)

**Comment by rgom** [comment]
Hi all,
thank you for all the work.

Is the issue mentioned by ktritz the same as original one? I'm asking, because I've only downloaded the win32_output.py and replaced under site-packages and I'm still having original issue with some colors being unreadable (they were fine in IPython 4).

![s](https://cloud.githubusercontent.com/assets/8234247/17207335/6a5bfe36-54b4-11e6-8780-f2592fca4c2b.png)

Is there anything I'm missing? Should I customize colors somehow?

Again, please look at another screenshot showing differences - in both cases comment is unreadable.

![s2](https://cloud.githubusercontent.com/assets/8234247/17207486/23be7d7c-54b5-11e6-847b-05ea3558a773.png)

Regards,
Robert

**Comment by jonathanslenders** [comment]
FYI: prompt_toolkit 1.0.4 has been released, which contains these fixes.

@rgom: regarding the first screenshot and the colors of the comment: I think IPython could pick a slightly different colorscheme when running on Windows. But also keep in mind that Windows consoles only have 16 colors, which are configurable. IPython does not have that much control of which actual colors the user assigns to these 16 colors.

@takluyver, not sure if we could use some slightly different colors for Windows. For ptpython, I have hardcoded a color scheme that seems to work well on Windows: https://github.com/jonathanslenders/ptpython/blob/master/ptpython/style.py#L52

**Comment by takluyver** [comment]
I'm happy for us to import those as the defaults on Windows if it's going to make people's lives easier. Windows users, can you try plugging the colours @jonathanslenders linked into [this code](https://github.com/ipython/ipython/blob/6a38355038fef923c2177159f9f5b9524f6beab2/IPython/terminal/interactiveshell.py#L272) and see if you like the results?

**Comment by takluyver** [comment]
Oh, but that won't affect the `os.paths.exists??` output at all, as far as I'm aware, because that's rendered through a different pathway. Any changes to that are, I guess, the result of differences between pyreadline and colorama (which we switched to). For those, try changing things [here](https://github.com/ipython/ipython/blob/6a38355038fef923c2177159f9f5b9524f6beab2/IPython/utils/PyColorize.py#L125).

**Comment by rgom** [comment]
Thank you very much for the effort.
However, from my point of view this is a regression, because default colors make some things unreadable (they were fine in 4.x IIRC).
I will try to use provided snippets, but that's not easy - I have to put some code in some files to have desired effect:
- is there any single place to change some 'theme'?
- entering "ipython customize colors" leads to nowhere. I couldn't find a single place describing format and place which I should change:
-- should that be console (http://jupyter-console.readthedocs.io/en/latest/config_options.html) or terminal (http://ipython.readthedocs.io/en/stable/config/options/terminal.html)
-- what's the format, as plain "InteractiveShell.colors='Linux'" in .jupyter_console_config.py leads to NameError

Current status is that after entering %colors linux docstrings are more readable, but that doesn't solve prompt issue:

In [7]: from collect

collect colors are different than those in docstrings

Sorry for being chaotic and/or inaccurate, I'm writing things from ordinary Windows ipython/jupyter perspective.

Regards,
Robert

**Comment by takluyver** [comment]
We have two separate colouring systems because of how the code has developed; we know this makes it confusing, and we do want to unify them, but that's where we are now.

None of the core developers normally use Windows, so it's easier for Windows-specific problems to creep in, especially in things like colours that can't easily be tested. I'll try to boot up my Windows partition later today and have a fiddle.

**Comment by rgom** [comment]
Please let me know if I can help further in any way.

Robert

**Comment by rgom** [comment]
As a side note when I invoked "%colors linux" then things in docstrings were better (but those in prompt weren't).
I've tried to have the same effect with:

c = get_config()
c.InteractiveShell.colors='linux'

in jupyter_console_config.py, but despite the file being executed (as I could see from some errors), there was no effect at all. That's not limited to colors, though, because "c.InteractiveShell.prompt_in1 = 'ala '" was a no-op as well.

Robert

**Comment by takluyver** [comment]
The colours in the inspection output are generated in IPython, not jupyter_console. The `prompt_in1` setting is no longer used since the switch to prompt_toolkit.

**Comment by takluyver** [comment]
@rgom, can you try out #9838 ?

**Comment by rgom** [comment]
Great, thank you.
Now colours in inspection are just fine (by default).
But they are inconsistent with prompt, as can be seen here:
![ipython-next](https://cloud.githubusercontent.com/assets/8234247/17427753/41c0c896-5ae3-11e6-9f19-13933d8df6f0.png)
(compare "os" in "import os" with docstrings below)

1. Can the defaults be changed?
2. Can I change them in my configuration? (Tried to use @klonuo snippet in jupyter_console_config, but without effect).

Regards,
Robert

**Comment by rgom** [comment]
Well...
I used to launch ipython with "ipython console".
That recently resulted in "Subcommand `ipython console` is deprecated and will be removed in future versions." warning.
So I've changed the launcher to "jupyter console".
And in such invocation mode prompt settings from jupyter and ipython were basically ignored.
Then I accidentally started ipython with "ipython" and lo and behold - colors are perfect.

Is this a bug?

Regards,
Robert

**Comment by Carreau** [comment]
Jupyter console and IPython despite looking similar are 2 different beasts.
The former une use 2 processes and run non python kernels, the later one
can allow things like'!vim' to work. So yes the difference is expected.

**Comment by takluyver** [comment]
And this is extra confusing in this case - when you use jupyter_console, the prompt colours are generated in the frontend, so they're configured as part of jupyter_console,  but the traceback and inspection colours are generated by the kernel, so they're configured as part of IPython. :unamused:

**Comment by mdyzma** [comment]
I have related issue, but my IPython is on Linux (Ubuntu 14.04). When I connect to Linux machine via ssh and start ipython, the prompt and all I type has terrible grayish background.

![ipyton](https://cloud.githubusercontent.com/assets/7068916/18004440/438b15de-6b94-11e6-9589-f5c0fa59ab73.png)

Any ideas how to get rid of it? Local machine ipython works well.

**Comment by takluyver** [comment]
Maybe putty would give better results? If IPython is running on Linux, prompt_toolkit will use vt100 formatting, and then it's up to the ssh client (I guess) to turn them into Windows API calls. Putty may do a better job of terminal emulation.

**Comment by Kevin-He-DVHS** [comment]
@mdyzma I just found out this bug you described (Terrible grayish background). It seems that the escape sequence `ESC [ 0 m` (Expected Action: All Attributes off) does not clear the background color properly in IPython if there was a background color applied. It sets the background color to gray instead. Strangely, the grayish background color only exists on colored characters.
Try running
```python
print('\x1b[49m')
```
in the prompt to clear the background color. This sends the escape sequence `ESC [ 49 m` to the terminal which force resets the background color.

**Comment by jonathanslenders** [comment]
Hi @Kevin-He-DVHS,
This sounds like something I should fix in prompt_toolkit, is that right?

This is the relevant line: https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/prompt_toolkit/output/vt100.py#L491

Can any of you try adding this escape sequence to that line and see whether it works?

**Comment by Kevin-He-DVHS** [comment]
@jonathanslenders You have misunderstood my issue. I just found out that it is a [colorama](https://github.com/tartley/colorama) related issue. As IPython depends on it. I'm going to open an issue on their GitHub site.

**Comment by jonathanslenders** [comment]
@Kevin-He-DVHS: ok :-)
