### ISSUE TITLE
IPython 5 can't disable auto indention with %autoindent magic command

### ISSUE THREAD

**Issue by hoffmann** [ipython/ipython#9888]
In IPython4 it was possible to disable automatic indention (for examlple after a colon) with the %autoindent magic command.

In IPython 5 and the swith to prompt_toolkit disabling auto indention with the magic command has no effect.

**Comment by takluyver** [comment]
IPython 5 also removes the main reason why you would disable autoindent: pasting multiline blocks of code no longer gets messed up with autoindentation on. Maybe we should drop the `%autoindent` magic? The fact that this is the only issue reported about it in several months suggests that not many people are trying to use it.

**Comment by Carreau** [comment]
so `autoindent` works in relation with `continue_prompt`  which turned out [this discussion](https://mail.scipy.org/pipermail/ipython-user/2012-August/010848.html) which let to at least [this](https://bitbucket.org/birkenfeld/ipython-physics/src/71b2d850da00/physics.py?fileviewer=file-view-default) using it. Is related to [this issue](https://github.com/ipython/ipython/issues/1491) and [this PR](https://github.com/sympy/sympy/pull/1470) that ends up not using it. 

So I'm all for deprecating in loudly deprecate in the 5.x/5.2+ series and slowly chop it of if we have no complaint back.
