### ISSUE TITLE
prompt_toolkit: color changed also for background output to stdout/stderr

### ISSUE THREAD

**Issue by eudoxos** [ipython/ipython#9923]
prompt_toolkit sets console color when there is no user-input, and any messages written directly to stdout/stderr by a different thread appear in this color. Previously (IPython<5.x), these messages had the plain (uncolored) style, all the while the prompt (or custom prompt) was colored. This is the old behavior (IPython 3.2.3 with readline and custom prompt)
![prompt-old](https://cloud.githubusercontent.com/assets/1029876/18126524/ccbba25c-6f7b-11e6-83e7-6b016ddd64de.png)
while this is what happens with IPython 5.1.0 (notice how the warning from FlowAnalysis at the bottom is green, not grey as before):
![prompt](https://cloud.githubusercontent.com/assets/1029876/18126461/87667efc-6f7b-11e6-8598-78dbef498b66.png)

Is this change intentional? What is the way to go back to the old behavior?

I tried inserting empty token with generic color at the end of the prompt:

    from IPython.terminal.prompts import Prompts, Token
    class WooPrompt(Prompts):
       def in_prompt_tokens(self,cli=None): return [(Token.Prompt,'Woo ['),(Token.PromptNum,str(self.shell.execution_count)),(Token.Prompt,']: '),(Token.Generic,'')]
        #...

but the output is still green.

**Comment by minrk** [comment]
No, that's not intentional, it's probably just something not handled correctly due to the threads involved.

**Comment by takluyver** [comment]
The protocol used for terminals is stateful, so stuff printed from background threads without care is liable to get messed up. prompt_toolkit has a [patch_stdout_context](http://python-prompt-toolkit.readthedocs.io/en/latest/pages/reference.html#prompt_toolkit.interface.CommandLineInterface.patch_stdout_context) method which will make printed text from Python code appear above the prompt, but I doubt it's thread safe.

**Comment by eudoxos** [comment]
My particular case is a background `std::thread` (on Linux, that means pthread; it is spawned from a c++ extension module); not sure whether `sys.stdout` and `sys.stderr` will be effective (maybe it will).

A sufficient approach would be to set the terminal state to neutral color after the prompt it displayed and user input is awaited. Mixing user typing into prompt and bg thread outputting at the same time is not something that worries me, that will be always messy.

**Comment by takluyver** [comment]
sys.stdout/stderr will only affect it if it uses Python machinery to produce output; if it's doing output the normal way in C++, it won't.

I don't think there's anything we can do about that in IPython; you could try petitioning @jonathanslenders, but I'd consider the formatting of output from background threads to be out of scope, so that the foreground thread can assume it has exclusive use of the terminal.

You could send the data over to the foreground thread by some means, and then use an inputhook to display it from the main event loop.

**Comment by jonathanslenders** [comment]
Hi all,

I fixed the color issue in prompt_toolkit: 47a6adf16ffb5c2306be0c833fb2784d406b8932
However, of course everything is printed where the cursor is at that point. (Unless ``patch_stdout=True`` has been set.)

It's not perfect, because the terminal is indeed stateful, and background threads are not supposed to print to stdout, but it's the best that we can do.

**Comment by takluyver** [comment]
Thanks Jonathan. Closing the issue as there's nothing more for us to do.

**Comment by eudoxos** [comment]
Thanks, @jonathanslenders, works perfectly now. Cheers!
