### ISSUE TITLE
is_event_loop_running_qt4 seems broken in IPython 5

### ISSUE THREAD

**Issue by titusjan** [ipython/ipython#9974]
In IPython 4 I can test if the Qt event loop has already been started by IPython (if this is the case, IPython remains responsive while my Qt application runs at the same time). However, in IPython 5 this doesn't work anymore. The `is_event_loop_running_qt4` function returns False, even when I use the `%gui qt` magic or equivalent command line option.

The logic I use for detecting this is:

```
import sys
from PyQt4 import QtGui

def in_ipython():
    "Returns True if IPython is running, False for the regular Python."
    try:
        from IPython.core.getipython import get_ipython
    except ImportError:
        return False
    else:
        return get_ipython() is not None

def get_qapp(*args, **kwargs):
    "Gets the global Qt application object. Creates one if it doesn't exist."
    qApp = QtGui.QApplication.instance()
    if qApp:
        print("Returning existing QApplication")
        return qApp
    else:
        print("Creating new QApplication")
        return QtGui.QApplication(*args, **kwargs)

def start_qt_event_loop(qApp):
    """ Starts the eventloop if it's not yet running."""
    if in_ipython():
        try:
            from IPython.lib.guisupport import is_event_loop_running_qt4, start_event_loop_qt4
            if is_event_loop_running_qt4(qApp):
                print("IPython event loop already running. GUI integration possible.")
            else:
                print("Starting (non-interactive) IPython event loop")
                start_event_loop_qt4(qApp)
            return
        except Exception as ex:
            print("Falling back on non-interactive event loop: {}".format(ex))

    print("Starting (non-interactive) event loop")
    return qApp.exec_()

if __name__ == "__main__":
    qApp = get_qapp(sys.argv)
    start_qt_event_loop(qApp)
```

I run this program with the `--gui=qt` and `-i` options so that IPython starts the Qt event loop, starts my GUI, and remains interactive afterwards.

When running this program in IPython 4.2.1 it prints _"IPython event loop already running. GUI integration possible."_ as expected. In IPython 5.1.0 it prints _"Starting (non-interactive) IPython event loop"_ and the IPython prompt becomes unresponsive.

So, how can I detect if the event loop is already running? And is the `is_event_loop_running_qt4` function obsolete? Or will there be a `is_event_loop_running_qt5` for Qt5?

Thanks in advance and please let me know if you need more information.

**Comment by takluyver** [comment]
I overlooked the APIs in `IPython.lib.guisupport` when updating the input hooks for prompt_toolkit and IPython 5. I'm looking now at what might make sense for them.

**Comment by takluyver** [comment]
Can you have a try with #9976?

**Comment by titusjan** [comment]
I have tested  your pull request and it works for me. Thank you for your quick response.

I still have one question though. What is the best way for me to handle Qt5?

**Comment by takluyver** [comment]
Despite the naming, the `_qt4` functions will also work for PyQt5. Ensure that you have imported `PyQt5.QtCore` before calling those functions, and it will detect that.

**Comment by titusjan** [comment]
Ok, thanks again.

**Comment by bergtholdt** [comment]
Hi,

I'm using ipython 5.3 and it is not working when connected to a kernel:

```python
(plab35) C:\Users\dep14422>ipython
Python 3.5.2 | packaged by conda-forge | (default, Jun 30 2016, 17:50:59) [MSC v.1900 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 5.3.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
Ready

In [1]: import IPython.lib.guisupport

In [2]: IPython.lib.guisupport.is_event_loop_running_qt4()

In [3]: gui qt

In [4]: IPython.lib.guisupport.is_event_loop_running_qt4()
Out[4]: True

In [5]: exit

(plab35) C:\Users\dep14422>jupyter console
Jupyter console 5.1.0

Python 3.5.2 | packaged by conda-forge | (default, Jun 30 2016, 17:50:59) [MSC v.1900 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 5.3.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.



In [1]: import IPython.lib.guisupport
Ready

In [2]: IPython.lib.guisupport.is_event_loop_running_qt4()

In [3]: gui qt

In [4]: IPython.lib.guisupport.is_event_loop_running_qt4()

In [5]: exit
Shutting down kernel
```

The problem is that in shell implementation in zmqshell.py of the ipykernel, the active_eventloop is not set in the enable_gui method (it is for the  iteractiveshell.py). So is_event_loo_running_qt4 returns None. A solution could be to return the loop in ipykernel.eventloops enable_gui and set active_eventloop in the ZMQInteractiveShell enable_gui method.

**Comment by bergtholdt** [comment]
I created a PR #232 for this

**Comment by bergtholdt** [comment]
So, while the mentioned PR sets the ``active_eventloop`` attribute on the shell, it prevents the loop from actually being started. E.g. loop_qt4 in ``ipykernel.eventloops`` gets run after ``shell.enable_gui``, and uses ``start_event_loop_qt4``, which checks for ``is_event_loop_running_qt4`` and since the ``active_eventloop`` is set by then, will actually not start the loop. Since loop_qt4 also does not return while the eventloop is running, there is also no way of setting the ``active_eventloop`` attribute after that. So I created another PR #10419 here that simply checks if the shell is attached to a kernel and if not uses the new method, otherwise uses the old method, since kernels start the loop using ``guisupport.start_event_loop_XXX``. I think it is still ok to use  PR ipython/ipykernel#232 for setting the ``active_eventloop`` attribute.
